export default [
  {
    contactName: "Alfredo Consarino",
    email: "studioconsarino@tiscali.it",
    telephone: "+39 338 1639848",
    address: "Via Duomo, 24",
    postcode: "88100",
    city: "Catanzaro",
    legalPracticeAreas: "Criminal",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Francesco Mortelliti",
    organisationName: "Studio Legale Mortelliti",
    email: "info@studiolegalemortelliti.it",
    website: "http://www.studiolegalemortelliti.it",
    telephone: "+39 0965 1870750",
    address: "Via del Torrione, 1-S",
    postcode: "89123",
    city: "Reggio Calabria",
    legalPracticeAreas: "Criminal; Intellectual property; International",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Paolo Zagami",
    organisationName: "Studio Legale Internazionale Zagamilaw",
    email: "reggiocalabria@zagamilaw.com",
    website: "http://www.zagamilaw.com",
    telephone: "+39 339 7554723",
    address: "Via degli Arconti, 25",
    postcode: "89127",
    city: "Reggio Calabria",
    legalPracticeAreas: "Corporate; International; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
];
