export default [
  {
    contactName: "Alessia Turci",
    lawFirmName: "studio Lexa",
    email: "a.turci@studiolexa.it",
    website: "http://www.studiolexa.it",
    telephone: "+39 349 8785925",
    address: "Viale Regina Margherita, 28 - 20122 Milano",
    legalPracticeAreas:
      "Domestic Abuse and Violence; Indecent Assault; Indecent Comunications; Rape; Sexual Misconduct in the work place; Health",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Alice Di Lallo",
    lawFirmName: "Studio Legale Di Nella",
    email: "alice.dilallo@dinellalex.it",
    website: "http://www.dinellalex.com",
    telephone: "+39 02 43982209",
    address: "Via Boccaccio, 4 - 22100 Milano",
    legalPracticeAreas:
      "Domestic Abuse and Violence; Indecent Comunications; Other",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Angela Ianni",
    lawFirmName: "Angela Ianni",
    email: "angelaianni@tiscali.it",
    website: "http://www.giuristeingenere.it",
    telephone: "+39 340 7163673",
    address: "Via Antonio Baiamonti, 10 - 00195 Roma",
    legalPracticeAreas: "Criminal; Personal injury",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Cecilia Cortesi Venturini",
    lawFirmName: "Studio Legale Venturini",
    email: "venturini_cortesi@iol.it",
    telephone: "+39 0521230167",
    address: "Via Farini, 15 - 43121 Parma",
    legalPracticeAreas: "Civil; Family; Women’s Rights",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Cristina Fasciotti",
    lawFirmName: "Cristina Fasciotti",
    email: "cristinafasciotti@studiofasciotti.com",
    website: "http://www.giuristeingenere.it",
    telephone: "+39 338 6645019",
    address: "Via Tibullo, 16 - 00193  Roma",
    legalPracticeAreas: "Family",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Elena Biaggioni",
    lawFirmName: "Stulio Legale Avv. Elena Biaggioni",
    email: "studio@biaggioni.it",
    telephone: "+39 0461 234100",
    address: "Via A. Diaz, 8 - 38122 Trento",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Emanuela Origlia",
    lawFirmName: "Avv. Emanuela Origlia",
    email: "avv.emanuelaoriglia@gmail.com",
    website: "http://www.giuristeingenere.it",
    telephone: "+39 347 6541358",
    address: "Corso Trieste, 149 - 00198 Roma",
    legalPracticeAreas: "Family; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Federica Podio",
    lawFirmName: "Avv. Federica Podio - Studio Legale",
    email: "federica.podio@studiolegalepodio.it",
    website: "http://www.studiolegalepodio.it",
    telephone: "+39 3398112309",
    address: "Corso Italia, 68 - 20122 Milano",
    legalPracticeAreas:
      "Domestic Abuse and Violence; Indecent Assault; Indecent Comunications; Rape; Health",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Francesca Manodori Sagredo",
    lawFirmName: "Studio legale FMS",
    email: "francescamanodori@libero.it",
    website: "http://www.giuristeingenere.it",
    telephone: "+39 333 4789054",
    address: "Via A. Mari, 53 - 00139 Roma",
    legalPracticeAreas: "Criminal; Family",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Loredana Severoni",
    lawFirmName: "Loredana Sevorini",
    email: "loredanaseveroni@gmail.com",
    website: "http://www.giuristeingenere.it",
    telephone: "+39 06 3729389; +39 393 0774415",
    address: "Via Fulcieri Paulucci de Calboli, 1 - 00195 Roma",
    legalPracticeAreas: "Family; Immigration; Personal injury",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Lucilla Longone",
    lawFirmName: "Longone",
    email: "lucilla.longone@tin.it",
    telephone: "+39 081 4238444",
    address: "Via dei Mille, 59 - 80121 Napoli",
    legalPracticeAreas: "Criminal",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Maria Carmen Napolitano",
    lawFirmName: "Studio Legale",
    email: "mcarmen68napolitano@gmail.com",
    telephone: "+39 339 1300555",
    address: "Via Di Novoli , 33/15 -  50127 Firenze",
    legalPracticeAreas: "Child Custody; Divorce; Family; Family Abuse",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Viviana Straccia",
    lawFirmName: "Viviana Straccia",
    email: "avv.vivianastraccia@gmail.com",
    website: "http://www.giuristeingenere.it",
    telephone: "+39 392 8294263",
    address: "Via Giuseppe Ferrari, 4 - 00195 Roma",
    legalPracticeAreas:
      "Bankruptcy; Criminal; Family; Immigration; Personal injury",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Viviana Minghelli",
    lawFirmName: "Studio Legale Minghelli",
    email: "vivianaminghelli@libero.it",
    website: "http://www.giuristeingenere.it",
    telephone: "+39 335 6380232",
    address: "Circonvallazione Clodia, 19 - 00195 Roma",
    legalPracticeAreas: "Bankruptcy; Criminal; Family",
    legalAid: "Yes",
    proBonoService: "No",
  },
];
