export default [
  {
    contactName: "Emmanuele Govoni",
    organisationName: "Govoni Law Firm",
    email: "govonilaw@gmail.com",
    website: "http://www.govonilaw.com",
    telephone: "+39 392 1376728",
    address: "Studio Legale Govoni, Via Gilbert Ferret, 86",
    postcode: "07041",
    city: "Alghero",
    legalPracticeAreas:
      "Corporate; Family; Immigration; Personal Injury; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Maurizio Loche",
    organisationName: "Loche Internatonal Law Firm",
    email: "ml@lochelawfirm.com",
    website: "http://www.lochelawfirm.com",
    telephone: "+39 070 663 222",
    address: "Viale Playa, 7",
    postcode: "09123",
    city: "Cagliari",
    legalPracticeAreas:
      "Bankruptcy; Commercial; Debt recovery; Inheritance; Litigation",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Nicola Nieddu",
    organisationName: "Studio legale - Law Firm Nieddu",
    email: "avv.nieddu@lawfirmsardinia.com",
    website: "http://www.lawfirmsardinia.com",
    telephone: "+39 347 9434693",
    address: "Via Carlo Alberto, 115",
    postcode: "07041",
    city: "Alghero",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Empoyment; Family; Immigration; International; Personal Injury; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Roberto Sanna",
    organisationName: "Studio Legale Sanna",
    email: "avvocatorobertosanna@gmail.com",
    website: "http://www.studiorobertosanna.com",
    telephone: "+39 333 8765065",
    address: "Viale Adua,  4",
    postcode: "07100",
    city: "Sassari",
    legalAid: "Yes",
    proBonoService: "No",
  },
];
