export default [
  {
    contactName: "Andrea Bucci",
    organisationName: "Studio Legale Bucci",
    email: "info@buccilex.com",
    website: "http://www.buccilex.com",
    telephone: "+39 051 267606",
    address: "Galleria del Leone, 2",
    postcode: "40125",
    city: "Bologna",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Family; Intellectual property; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Alessio Totaro",
    organisationName: "R&P Legal",
    email: "alessio.totaro@replegal.it",
    website: "http://www.replegal.it",
    telephone: "+39 051 232495",
    address: "Via D’Azeglio, 19",
    postcode: "40123",
    city: "Bologna",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Angelo Stirone",
    organisationName: "Studio Legale Gamberini Associazione Professionale",
    email: "avvocatostirone@gmail.com",
    website: "https://avvocatostironesl.com",
    telephone: "+39 333 8835684",
    address: "Piazza Calderini, 1",
    postcode: "40124",
    city: "Bologna",
    legalPracticeAreas: "Criminal; Immigration; International; Personal Injury",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Carlo Longanesi",
    organisationName: "Studio Legale Associato Ridolfi Ghighi Longanesi",
    email: "segreteria@rilomar.it",
    telephone: "+39 0544 35076 / +39 0544 38301",
    address: "Via Diaz, 47",
    postcode: "48121",
    city: "Ravenna",
    legalPracticeAreas:
      "Bankruptcy; Corporate; International; Maritime; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Cristina Maria Melito",
    organisationName: "M-Lawyers",
    email: "c.melito@m-lawyers.com",
    website: "http://www.m-lawyers.com",
    telephone: "+39 051 2264179",
    address: "Via Altabella, 19",
    postcode: "40126",
    city: "Bologna",
    legalPracticeAreas:
      "Employment; Family; Immigration; International; Italian Citizenship Applications; Real estate",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Domenico Antonio Multari",
    organisationName: "M-Lawyers",
    email: "d.multari@m-lawyers.com",
    website: "http://www.m-lawyers.com",
    telephone: "+39 051 264179",
    address: "Via Altabella, 19",
    postcode: "40126",
    city: "Bologna",
    legalPracticeAreas:
      "Advisory Services for relocations to Italy; Bankruptcy; Corporate; Family; Inheritance; International;  Italian Citizenship Applications; Real estate; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Gian Piero Rinaldi",
    organisationName: "Studio Legale Rinaldi",
    email: "info@rinaldilawfirm.com",
    website: "http://www.rinaldilawfirm.com",
    telephone: "+39 051 237870",
    address: "Galleria del Toro, 3",
    postcode: "40121",
    city: "Bologna",
    legalPracticeAreas: "Criminal; Business",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Jane Schorah",
    organisationName: "Fieldfisher Italy",
    email: "jane.schorah@fieldfisher.com",
    website: "https://www.fieldfisher.com/en/locations/italy",
    telephone: "+39 051 99711",
    address: "Viale Silvani, 6",
    postcode: "40122",
    city: "Bologna",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Intellectual property; International; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Manuela Tirini",
    organisationName: "Studio Legale Tirini Grassi",
    email: "manuela@tirinigrassi.it",
    website: "http://www.tirinigrassi.it",
    telephone: "+39 051 6446810",
    address: "Mura di Porta Saragozza, 4",
    postcode: "40123",
    city: "Bologna",
    legalPracticeAreas: "Family; International",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Marco Tomasi",
    organisationName: "Studio Legale Tomasi",
    email: "marco.tomasi@studiolegaletomasi.it",
    website: "http://www.studiolegaletomasi.it",
    telephone: "+39 393 6469299",
    address: "Via dell’Arcoveggio, 49/5",
    postcode: "40129",
    city: "Bologna",
    legalPracticeAreas:
      "Corporate; Commercial; Debt collection and Recovery; International Trade; Intellectual Property",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Michele Sacchi",
    organisationName: "Studio Legale Avv. Sacchi",
    email: "m.sacchi@sacchiconsulenze.com",
    website: "http://www.sacchiconsulenze.com",
    telephone: "+39 052 1575787",
    address: "Strada Mazzini, 43",
    postcode: "43121",
    city: "Parma",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Immigration; International; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Simon Cartwright",
    organisationName: "Studio Legale Cartwright Pescatore",
    email: "simon.cartwright@becp.eu",
    website: "http://www.becp.eu",
    telephone: "+39 054 2784519",
    address: "Via Dante, 26",
    postcode: "40125",
    city: "Bologna",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Intellectual property; International; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
];
