export default [
  {
    contactName: "Daniela Ajese",
    lawFirmName: "Studio Legale e Commerciale Ajese",
    email: "ajese@studioajese.it",
    website: "https://www.studioajese.it",
    telephone: "+39 041 961965",
    address: "Bia Bruno Maderna, 7",
    postcode: "30174",
    city: "Venezia",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Health; Intellectual property; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Domenico Carponi Schittar",
    lawFirmName: "Studio Carponi Schittar e Sportelli",
    email: "avvocaticarponisportelli@gmail.com",
    website: "https://studiocarponischittarsportelli.business.site",
    telephone: "+39 041 962475",
    address: "Via Feliasi, 57",
    postcode: "30174",
    city: "Mestre",
    legalPracticeAreas: "Criminal",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Enrico Tenerani",
    lawFirmName: "Studio Legale Tenerani",
    email: "avv.tenerani@email.it",
    website: "http://www.tenlegal.it",
    telephone: "+39 045 8347702",
    address: "Via Tonale, 13",
    postcode: "37126",
    city: "Verona",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Intellectual property; International; Maritime; Personal injury",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Giovanni Tretti",
    lawFirmName: "Studio Legale GTA",
    email: "giovanni.tretti@gtastudio.eu",
    website: "http://www.gtastudio.eu",
    telephone: "+39 042 4566112",
    address: "Viale Asiago, 113",
    postcode: "36061",
    city: "Bassano del Grappa",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Intellectual property; International; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Michele Stratta",
    lawFirmName: "Studio Legale Avv. Michele Stratta",
    email: "michele.stratta@hotmail.it",
    website: "http://www.studiolegalestratta.it",
    telephone: "+39 0444 326698",
    address: "Piazza Duomo, 5",
    postcode: "36100",
    city: "Vicenza",
    legalPracticeAreas: "Civil; Criminal Family; Citizenship; Immigration",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Roberto Barbalich",
    lawFirmName: "Barbalich Law Practice – Studio Legale Barbalich",
    email: "barbalichr@barbalich-law.eu",
    website: "http://www.barbalich-law.eu",
    telephone: "+39 041 244 0121",
    address: "Calle Cappello, 2453F",
    postcode: "30123",
    city: "Dorsoduro",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Intellectual Property; International; Real Estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
];
