export default [
  {
    contactName: "Angelo Lanzetta",
    email: "studio_lanzetta@libero.it",
    telephone: "+39 328 5950717",
    address: "Bernini Center - Piazza Bernini",
    postcode: "81031",
    city: "Aversa",
    legalPracticeAreas: "Criminal",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Lucilla Longone",
    organisationName: "Longone",
    email: "lucilla.longone@tin.it",
    telephone: "+39 081 4238444",
    address: "Via dei Mille, 59",
    postcode: "80121",
    city: "Napoli",
    legalPracticeAreas: "Criminal",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Elvira Marzano",
    organisationName: "Marzano Avvocati Associati",
    email: "ira@marzanolaw.it",
    website: "http://www.marzanolaw.it",
    telephone: "+39 089 224842",
    address: "Corso Garibaldi, 153/A",
    postcode: "84122",
    city: "Salerno",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Luigi Massa",
    organisationName: "Studio Legale Avv. Luigi Massa - NLP",
    email: "l.massa@nlpstudiolegale.it",
    website: "http://nlpstudiolegale.it",
    telephone: "+39 0823 808791",
    address: "Viale JF Kennedy, 13",
    postcode: "81031",
    city: "Aversa",
    legalPracticeAreas:
      "Bankruptcy; Civil; Litigation; Debt Collection; Insurance; Personal Data Litigation;  Insolvency Proceedings; Housing/Rental",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Francesco Mazzei",
    organisationName: "Studio Legale Mazzei",
    email: "mazzeif@tin.it",
    telephone: "+39 3470157425",
    address: "Via Gian vincenzo Quaranta, 1",
    postcode: "84123",
    city: "Salerno",
    legalPracticeAreas: "Family; International; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Giancarlo Pierpaolo Pezzuti",
    organisationName: "Studio Legale Pezzuti",
    email: "studiopezzuti@gmail.com",
    telephone: "+39 328 333 3080",
    address: "Piazza Eritrea, 3",
    postcode: "80122",
    city: "Napoli",
    legalPracticeAreas: "Criminal; Immigration; Family; Damage Responsibility",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Alfonso Scafuro",
    organisationName: "Studio Legale Scafuro",
    email: "alfonsoscafuro@studiolegalscafuro.com",
    website: "http://www.studiolegalescafuro.com",
    telephone: "+39 0892963195",
    address: "Via San Francesco, 29",
    postcode: "84081",
    city: "Baronissi",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Family; Immigration; Intellectual property; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Luigi Scalzo",
    organisationName: "Studio Legale Scalzo e Associati",
    email: "studiolegalescalzo@gmail.com",
    website: "https://www.linkedin.com/in/luigi-scalzo/",
    telephone: "+39 347 9256390",
    address: "Via Garibaldi, 4",
    postcode: "80040",
    city: "Cercola",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Immigration; Intellectual property; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Victor Sotunde",
    organisationName: "Studio Legale Castaldo, Magliulo & Associati",
    email: "v.sotunde@castaldomagliuloassociati.it",
    website: "http://www.castaldomagliuloassociati.it",
    telephone: "+39 081 5523200",
    address: "Via A. Depretis, 51",
    postcode: "80133",
    city: "Napoli",
    legalPracticeAreas: "International; Maritime",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Fiorella Zangaro",
    email: "avvfiorellazangaro@gmail.com",
    telephone: "+39 368 3501878",
    address: "Via dei Fiorentini, 61",
    postcode: "80133",
    city: "Napoli",
    legalPracticeAreas:
      "Corporate; Employment; Family; Personal Injury; Real Estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
];
