export default [
  {
    contactName: "Antonello Leogrande",
    organisationName: "AL&partners",
    email: "aletpartners@gmail.com",
    telephone: "+39 335 7469676",
    address: "Via Lido Bruno 80",
    postcode: "74122",
    city: "Taranto",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Davide Cupertino",
    organisationName: "Consulenti Italiani Law Firm",
    email: "info@consulentiitaliani.com",
    website: "http://www.consulentiitaliani.com",
    telephone: "+39 069291 5093",
    address: "Via Giovanni Pascoli, 7",
    postcode: "70021",
    city: "Acquaviva delle Fonti",
    legalPracticeAreas:
      "Criminal; Employment; Family; Immigration; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Giandomenico De Tullio",
    organisationName: "De Tullio Law Firm",
    email: "info@detulliolawfirm.com",
    website: "https://www.detulliolawfirm.com",
    telephone: "+39 080 4831785",
    address: "Corso Italia, 22",
    postcode: "74015",
    city: "Martina Franca",
    legalPracticeAreas: "Family; Immigration; International; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Giuseppe Stanisci",
    organisationName: "Stanisci Law Firm & Business",
    email: "avv.stanisci@hotmail.it",
    website: "https://www.studiolegalestanisci.eu/",
    telephone: "+39 339 2991782",
    address: "Via Padre Vito Buonsanto, 19",
    postcode: "72017",
    city: "Ostuni",
    legalPracticeAreas:
      "Corporate; Immigration; International; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "Depends on the case",
  },
  {
    contactName: "Luca Bruno",
    organisationName: "Luca Bruno",
    email: "avv.bruno@gmail.com",
    website: "https://www.francescopaolosisto.it/",
    telephone: "+39 334 962 9237",
    address: "Via Roberto da Bari, 36",
    postcode: "70122",
    city: "Bari",
    legalPracticeAreas: "Criminal; Civil",
    legalAid: "No",
    proBonoService: "No",
  },
];
