export default [
  {
    contactName: "Antonello Leogrande",
    lawFirmName: "AL&partners",
    email: "aletpartners@gmail.com",
    telephone: "+39 335 7469676",
    address: "Via Lido Bruno 80 - 74122 Taranto",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Davide Cupertino",
    lawFirmName: "Consulenti Italiani Law Firm",
    email: "info@consulentiitaliani.com",
    website: "http://www.consulentiitaliani.com",
    telephone: "+39 069291 5093",
    address: "Via Giovanni Pascoli, 7 - 70021 Acquaviva delle Fonti (BA)",
    legalPracticeAreas:
      "Criminal; Employment; Family; Immigration; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Giandomenico De Tullio",
    lawFirmName: "De Tullio Law Firm",
    email: "info@detulliolawfirm.com",
    website: "https://www.detulliolawfirm.com",
    telephone: "+39 080 4831785",
    address: "Corso Italia, 22 - 74015 Martina Franca (TA)",
    legalPracticeAreas: "Family; Immigration; International; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Giuseppe Stanisci",
    lawFirmName: "Stanisci Law Firm & Business",
    email: "avv.stanisci@hotmail.it",
    website: "https://www.studiolegalestanisci.eu/",
    telephone: "+39 339 2991782",
    address: "Via Padre Vito Buonsanto, 19 - 72017 Ostuni (BR)",
    legalPracticeAreas:
      "Corporate; Immigration; International; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "Depends on the case",
  },
  {
    contactName: "Luca Bruno",
    lawFirmName: "Luca Bruno",
    email: "avv.bruno@gmail.com",
    website: "https://www.francescopaolosisto.it/",
    telephone: "+39 334 962 9237",
    address: "Via Roberto da Bari, 36 - 70122 Bari",
    legalPracticeAreas: "Criminal; Civil",
    legalAid: "No",
    proBonoService: "No",
  },
];
