export default [
  {
    contactName: "Alessandra Ghilardi",
    lawFirmName: "Studio Legale Avv. Alessandra Ghilardi",
    email: "alessandra.ghilardi@pec.avvocatilucca.it",
    telephone: "+39 339 3865392",
    address: "Via Sciesa, 16/D",
    postcode: "55049",
    city: "Viareggio",
    legalPracticeAreas:
      "Bankruptcy; Family; Health; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Anna Sensi",
    email: "anna.sensi@gmail.com",
    telephone: "+39 349 561 4334",
    address: "Via delle Pappe, 12",
    postcode: "51100",
    city: "Pistoia",
    legalPracticeAreas: "Criminal; Immigration; International",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Carlo H. Mastellone",
    lawFirmName: "SLM - Studio Legale Mastellone",
    email: "c.mastellone@studiomastellone.it",
    website: "http://www.studiomastellone.it",
    telephone: "+39 055 214620040",
    address: "Via Gustavo Modena, 23",
    postcode: "50121",
    city: "Firenze",
    legalPracticeAreas:
      "Corporate; Immigration; International; Real estate; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Chiara Celesti",
    lawFirmName: "DS TAX & LEGAL",
    email: "celesti@dstaxlegal.it",
    website: "https://www.dstaxlegal.it/",
    telephone: "+39 055 5015902",
    address: "Via Alfonso La Marmora, 29",
    postcode: "50121",
    city: "Florence",
    legalPracticeAreas: "Real Estate; Corporate;Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Daniela Forti",
    lawFirmName: "Studio Legale Avv. Daniela Forti",
    email: "info@fortilawyerintuscany.com",
    website: "http://www.fortilawyerintuscany.com",
    telephone: "+39 348 8098799",
    address: "Via Aurelia Sud, 23",
    postcode: "55045",
    city: "Pietrasanta",
    legalPracticeAreas: "Corporate; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Elena Borsacchi",
    lawFirmName: "Studio Legale Barbieri Borsacchi & Partn.",
    email: "studio@barbieriborsacchi.com; avv.elenaborsacchi@gmail.com",
    website: "http://www.barbieriborsacchi.com/en/the-law-firm/",
    telephone: "+39 050 29039/48073/29459",
    address: "Via Paoli, 25",
    postcode: "56126",
    city: "Pisa",
    legalPracticeAreas:
      "Criminal; Family; Immigration; International; Personal injury",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Enrico Lattanzi",
    lawFirmName: "Studio Legale Lattanzi",
    email: "e.lattanzi@lattanzistudio.it",
    website: "http://www.lawfirminitaly.com",
    telephone: "+39 0583 584981",
    address: "Viale Giacomo Puccini, 75",
    postcode: "55100",
    city: "Lucca",
    legalPracticeAreas: "Civil; Real Estate; Property",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Federica Barone Bombagli",
    lawFirmName: "Studio Legale Barone Bombagli",
    email: "fbarone@studiolegalebarone.com",
    website: "http://www.studiolegalebarone.com",
    telephone: "+39 0577 46163",
    address: "Via dei Termini, 6",
    postcode: "53100",
    city: "Siena",
    legalPracticeAreas: "Civil; Real Estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Francesca Saracchi",
    lawFirmName: "Studio Legale Francesca Saracchi",
    email: "info@studiolegalefrancescasaracchi.com",
    website: "http://www.studiolegalefrancescasaracchi.com",
    telephone: "+39 327 0611563",
    address: "Corso Carlo Rosselli 27",
    postcode: "54033",
    city: "Carrara",
    legalPracticeAreas:
      "Bankrupcy; Corporate; Criminal; Employment; Family; Health; Immigration; Maritime; Personal Injury; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Francesca Sani; Francesca Baroncelli Poggi",
    lawFirmName: "Studio Legale Sani - Baroncelli Poggi",
    email:
      "f.baroncelli@firenzelegale.com;  f.sani@firenzelegale.com We Lawyers",
    website: "https://www.we-lawyers.com",
    telephone: "+39 055 0469320",
    address: "Piazza Nannotti, 11",
    postcode: "50136",
    city: "Florence",
    legalPracticeAreas:
      "Corporate; Contract; Criminal; E-commerce; Employment; Personal injury; Public procurement; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Francesco Chianini",
    lawFirmName: "Studio Legale Chianini",
    email: "avv.chianini@libero.it",
    telephone: "+39 057 5355201",
    address: "Via Fulvio Croce, 13",
    postcode: "52100",
    city: "Arezzo",
    legalPracticeAreas:
      "Bankruptcy; Criminal; Family; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Francesco Maresca",
    lawFirmName: "Studio Legale Maresca",
    email: "avv.fmaresca@gmail.com",
    website: "http://www.avvocatofrancescomaresca.it",
    telephone: "+39 335 7059597; +39 055 217571",
    address: "Via dei Vecchietti, 1",
    postcode: "50123",
    city: "Firenze",
    legalPracticeAreas: "Bankruptcy; Corporate; Criminal; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Francesco Petitti",
    lawFirmName: "Avvocato Francesco Petitti",
    email: "francescopetitti@virgilio.it",
    website: "http://www.linkedin.com/in/francesco-petitti-30929432",
    telephone: "+39 320 3005860",
    address: "Scali D’Azeglio n. 20",
    postcode: "57123",
    city: "Livorno",
    legalPracticeAreas: "Corporate; Health; International; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Giampaolo Benedetti Pearson",
    lawFirmName: "BBPLegal",
    email: "g.benedettipearson@bbplegal.it",
    website: "http://www.bbplegal.it",
    telephone: "+39 050 6203219",
    address: "Corso Matteotti, 16",
    postcode: "56021",
    city: "Cascina",
    legalPracticeAreas:
      "Corporate; Family; Intellectual property; International",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Gian Franco Borio",
    lawFirmName: "Studio Avv. Gian Franco Borio",
    email: "gfborio@dinonet.it",
    telephone: "+39 055 6532144",
    address: "Via Finlandia, 20",
    postcode: "50126",
    city: "Firenze",
    legalPracticeAreas:
      "Corporate; Employment; Immigration; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Lorenzo Contri OBE",
    lawFirmName: "Studio Legale Contri Associazione Professionale",
    email: "l.contri@studiolegalecontri.it",
    website: "http://www.studiolegalecontri.it",
    telephone: "+39 055 578005",
    address: "Via Pico della Mirandola, 9",
    postcode: "",
    city: "Firenze",
    legalPracticeAreas:
      "Corporate; Family; Intellectual property; International; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Margaret MacLeod",
    lawFirmName: "Belmonte-MacLeod Lawyers",
    email: "margaret.macleod@tuscanylawyers.com",
    website: "http://www.tuscanylawyers.com",
    telephone: "+39 327 5558129",
    address: "Via Ristoro d’Arezzo, 77",
    postcode: "52100",
    city: "Arezzo",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Immigration; Intellectual property; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Maria Grazia Antoci",
    lawFirmName: "Studio Legale Antoci",
    email: "studiolegale@antoci.eu",
    website: "http://www.antoci.eu",
    telephone: "+39 3474198281",
    address: "Lungarno Amerigo Vespucci, 58",
    postcode: "50123",
    city: "Firenze",
    legalPracticeAreas:
      "Cross-border succession; Family; Health; Immigration; International; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Mariangela Marrangoni",
    lawFirmName: "Studio Legale Marrangoni",
    email: "avvocatomarrangoni@gmail.com",
    website: "http://www.studiolegalemarrangoni.it",
    telephone: "+39  338 6805009",
    address: "Pod. Casino della Rosa, 15",
    postcode: "53020",
    city: "Trequanda",
    legalPracticeAreas:
      "Corporate; Family; Immigration; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Massimo Miniati Paoli",
    lawFirmName: "Studio Legale Miniati Paoli",
    email: "studio@miniatipaoli.it",
    website: "http://www.miniatipaoli.it",
    telephone: "+39 055 2477363",
    address: "Via della Colonna, 19",
    postcode: "50121",
    city: "Firenze",
    legalPracticeAreas:
      "Bankruptcy; Criminal; Family; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Piermarco Sibillia",
    lawFirmName: "SLVB",
    email: "sibillia@slvb.it",
    website: "http://www.slvb.it",
    telephone: "+39 055 489504",
    address: "Via Bolognese, 55",
    postcode: "50139",
    city: "Firenze",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Family; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Simone Calzolai",
    lawFirmName: "Studio Legale Calzolai - Law Firm",
    email:
      "avv.calzolai@studiolegalecalzolai.it; segreteria@studiolegalecalzolai.it",
    website: "http://www.studiolegalecalzolai.it",
    telephone: "+39 0574 1826341",
    address: "Via Toscana, 2/F",
    postcode: "59100",
    city: "Prato",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Health; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Stefano Dorigo",
    lawFirmName: "DS TAX & LEGAL",
    email: "dorigo@dstaxlegal.it",
    website: "https://www.dstaxlegal.it/",
    telephone: "+39 055 5015902",
    address: "Via Alfonso La Marmora, 29",
    postcode: "50121",
    city: "Florence",
    legalPracticeAreas: "Tax; International; Corporate; Criminal; Real Estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Vieri Adriani",
    lawFirmName: "Studio Legale Avvocato Vieri Adriani",
    email: "vieriavvadriani@gmail.com",
    website: "http://www.vieriavvocatoadriani.it",
    telephone: "+39 340 2650014",
    address: "Va Lorenzo il Magnifico, 46",
    postcode: "50129",
    city: "Firenze",
    legalPracticeAreas: "Criminal; Personal injury",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
];
