export default [
  {
    contactName: "Alessandro Spinnato",
    organisationName: "Spinnato Law Firm",
    email: "info@spinnatolawfirm.com",
    website: "http://spinnatolawfirm.com",
    telephone: "+39 347 4908130",
    address: "Salita Salvatore Viale 1/28",
    postcode: "16128",
    city: "Genova",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; International; Maritime; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Alessandro Bartoli",
    organisationName: "Castagneto-Bartolotta-D’Harcourt-Bartoli",
    email: "alessandro.bartoli@saurolex.it; segreteria@saurolex.it",
    telephone: "+39 019 815190; +39 347 4713050",
    address: "Via Nazario Sauro 3/1 S",
    postcode: "17100",
    city: "Savona",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Intellectual property; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Alessandro Bartoli",
    organisationName:
      "Castagneto-Bartolotta-D’Harcourt-Bartoli (Branch Office)",
    email: "alessandro.bartoli@saurolex.it; segreteria@saurolex.it",
    telephone: "+39 019 815190; +39 347 4713050",
    address: "Piazza della Vittoria",
    postcode: "17014",
    city: "Cairo Montenotte",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Intellectual property; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Andrea Pericu",
    organisationName: "Bettini Formigaro Pericu",
    email: "andreapericu@bfplex.com",
    website: "http://www.bfplex.com",
    telephone: "+39 010 581746",
    address: "Via Martin Piaggio, 17",
    postcode: "16128",
    city: "Genova",
    legalPracticeAreas:
      "Bankruptcy; Health; Intellectual property; International; Maritime; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Andrea Sciello",
    organisationName: "Avvocato Andrea Sciello",
    email: "andreasciello@hotmail.it",
    telephone: "+39 335 337786",
    address: "Via Fieschi, 2/26B",
    postcode: "16121",
    city: "Genova",
    legalPracticeAreas: "Criminal",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Carla Borachia",
    organisationName: "Studio Legale Borachia",
    email: "avvocatiborachia@gmail.com",
    telephone: "+39 0187 737149",
    address: "Via U. Rattazzi, 29",
    postcode: "19121",
    city: "La Spezia",
    legalPracticeAreas: "Family; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Mario Stefano Zani",
    email: "mario_zani@fastwebnet.it",
    telephone: "+39 347 8518106",
    address: "Vico San Matteo, 2/45",
    postcode: "16123",
    city: "Genova",
    legalPracticeAreas: "Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Maurizio Dardani",
    organisationName: "Dardani Studio Legale",
    email: "maurizio.dardani@dardani.it",
    website: "http://www.dardani.it",
    telephone: "+39 010 5761816",
    address: "Salita di Santa Caterina, 10/8A",
    postcode: "16123",
    city: "Genova",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Intellectual property; International; Maritime",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Umberto Illuzzi",
    organisationName: "Umberto Illuzzi",
    email: "studio@assoprof.net",
    website: "http://www.assoprof.net",
    telephone: "+39 010 530091",
    address: "Via S. Vincenzo, 2",
    postcode: "16121",
    city: "Genova",
    legalPracticeAreas: "Fiscal",
    legalAid: "No",
    proBonoService: "No",
  },
];
