export default [
  {
    contactName: "Aldo Sam",
    organisationName: "Studio Legale Avv. Aldo Sam",
    email: "aldo.sam@fastwebnet.it",
    website: "https://studiolegalesamaldo.myadj.it/v/studiolegalesamaldo",
    telephone: "+39 0434 208523",
    address: "Piazzetta dei Domenicani 9/A",
    postcode: "33170",
    city: "Pordenone",
    legalPracticeAreas:
      "Criminal; Family; Health; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Francesco Furlan",
    organisationName: "Studio Legale Furlan",
    email: "francesco.furlan@avvocatofurlan.eu",
    telephone: "+39 349 3564891",
    address: "Studio Legale Furlan, Vicolo del Forno 11",
    postcode: "33170",
    city: "Pordenone",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Immigration; International; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Luca Colombaro",
    email: "colombaro@studiolegale98.it",
    telephone: "+39 0434 522018",
    address: "Via Bertossi, 5",
    postcode: "33170",
    city: "Pordenone",
    legalPracticeAreas: "Criminal; Employment; Personal Injury",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Michela Brusadin",
    organisationName: "Michela Brusadin Law Firm",
    email: "brusadin.michela@gmail.com",
    telephone: "+39 338 4902693",
    address: "Via San Quirino, 11",
    postcode: "33170",
    city: "Pordenone",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Family; Intellectual property; International",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
];
