export default [
  {
    contactName: "Anna Maria Fiasconaro",
    lawFirmName: "Studio Legale Fiasconaro",
    email: "a.fiasconaro@studiolegalefiasconaro.it",
    website: "http://www.studiolegalefiasconaro.it",
    telephone: "+39 333 8974445",
    address: "Via Siracisa, 7",
    postcode: "90141",
    city: "Palermo",
    legalPracticeAreas: "Corporate; Family; International; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Antonino Chiaramonte",
    lawFirmName: "Studio Legale Chiaramonte",
    email: "achiaramonte@studiolegalechiaramonte.it",
    website: "http://www.studiolegalechiaramonte.it",
    telephone: "+39 389 5104275",
    address: "Corso Camillo Finocchiaro Aprile, 124",
    postcode: "90138",
    city: "Palermo",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; International; Maritime; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Donatella Sicomo",
    lawFirmName: "Studio Legale Internazionale Arnone&Sicomo",
    email: "donatella.sicomo@arnonesicomo.com",
    website: "http://www.arnonesicomo.it",
    telephone: "+39 333 2454773",
    address: "Piazzetta Francesco Bagnasco, 31",
    postcode: "90141",
    city: "Palermo",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Personal Injury; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Giuseppe Coppola",
    lawFirmName: "Coppolalaw",
    email: "info@coppolastudiolegale.com",
    website: "http://www.coppolaw.com",
    telephone: "+39 334 3756736",
    address: "Via Marchese Roccaforte, 66",
    postcode: "90143",
    city: "Palermo",
    legalPracticeAreas:
      "Administrative; Family; International; Real Estate; Maritime; Corporate; Employment; Health; Immigration; Intellectual Property; Personal injury; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Manlio Gervasi",
    lawFirmName: "c_legal",
    email: "m.gervasi@c-legal.it",
    website: "http://www.c-legal.it",
    telephone: "+39 338 4558766",
    address: "Via Americo Amari, 8",
    postcode: "90139",
    city: "Palermo",
    legalPracticeAreas: "Corporate; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Marco Mendola",
    lawFirmName: "Vegna&Mendola - Studio Legale Internazionale",
    email: "marco.mendola@vemlegal.com",
    website: "http://www.vemlegal.com",
    telephone: "+39 339 6895999",
    address: "Via Duca della Verdura, 4",
    postcode: "90143",
    city: "Palermo",
    legalPracticeAreas:
      "Corporate; Criminal; Family; International; Labour; Litigation; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Serena Torrente",
    lawFirmName: "Luxury Law",
    email: "info@luxury-law.com",
    website: "https://www.luxury-law.com",
    telephone: "+39 3271260285",
    address: "Via Velletri, 1A",
    postcode: "91016",
    city: "Trapani",
    legalPracticeAreas:
      "Criminal; Immigration; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
];
