export default [
  {
    contactName: "Davide Cupertino",
    organisationName: "Consulenti Italiani",
    email: "info@consulentiitaliani.com",
    website: "https://www.consulentiitaliani.com/contact-us",
    telephone: "+39 080 9697816",
    address: "Based in London with offices in Puglia and Milan",
    legalAid: "No",
    proBonoService: "No",
    description: "Solicitor of the Supreme Court of England and Wales",
  },
  {
    contactName: "Antonio Golino",
    organisationName: "Clifford Chance",
    email: "Antonio.Golino@CliffordChance.com",
    website:
      "https://www.cliffordchance.com/content/cliffordchance/people_and_places/people/partners/it/antonio_golino.html",
    telephone: "+39 02 80634 1",
    address: "Milan",
    legalAid: "No",
    proBonoService: "No",
    description:
      "Solicitor of the Supreme Court of England and Wales, qualified Italian lawyer registered at the Ordine degli Avvocati di Milano (Bar Council of Milan). Does not generally offer notarial services.",
  },
  {
    contactName: "Richard Hamilton",
    organisationName: "Gianni Origoni Grippo Capelli Partners",
    email: "RHamilton@gop.it",
    website: "http://www.gop.it/people_view.php?id=324",
    telephone: "+39 02 7637 4507",
    address: "Milan",
    legalAid: "No",
    proBonoService: "No",
    description:
      "Solicitor of the Supreme Court of England and Wales, qualified Italian lawyer registered at the Ordine degli Avvocati di Milano (Bar Council of Milan)",
  },
  {
    contactName: "Colin Jamieson",
    organisationName: "Studio Legale Tributario Avv. Colin Jamieson",
    email: "colin@taxing.it",
    website: "http://www.taxing.it",
    telephone: "+39 02 488 3945",
    address: "Milan",
    legalAid: "No",
    proBonoService: "No",
    description:
      "Solicitor of the Supreme Court of England and Wales, qualified Italian lawyer registered at the Ordine degli Avvocati di Milano (Bar Council of Milan)",
  },
  {
    contactName: "Anamaria Marin",
    organisationName: "SLCG Studio Legale Associato",
    email: "amarin@slcg.it",
    website: "http://www.slcg.it/",
    telephone: "+39 02 720 80153",
    address: "Milan",
    legalAid: "No",
    proBonoService: "No",
    description: "Solicitor of the Supreme Court of England and Wales",
  },
  {
    contactName: "Gian Pietro Pilliu",
    email: "pilliugianpietro@gmail.com",
    telephone: "+39 02 72021514",
    address: "Milan",
    legalAid: "No",
    proBonoService: "No",
    description:
      "Solicitor of the Supreme Court in England and Wales, qualified Italian lawyer registered at the Ordine degli Avvocati di Milano (Bar Council of Milan)",
  },
  {
    contactName: "Luca Salerno",
    organisationName: "Hanover Bond Law",
    email: "ls@hanoverbondlaw.com",
    website: "https://www.hanoverbondlaw.com/team-details/?id=16",
    telephone: "+44 (0)20 3031 6647",
    address: "Based in London with office in Milan",
    legalAid: "No",
    proBonoService: "No",
    description:
      "Solicitor of the Supreme Court in England and Wales, qualified Italian lawyer registered at the Ordine degli Avvocati di Milano (Bar Council of Milan)",
  },
  {
    contactName: "Stefano Sciolla",
    organisationName: "Latham & Watkins llp",
    email: "stefano.sciolla@lw.com",
    website: "https://www.lw.com/people/stefano-sciolla",
    telephone: "+39 02 30462102",
    address: "Milan",
    legalAid: "No",
    proBonoService: "No",
    description:
      "Solicitor of the Supreme Court of England and Wales, qualified Italian lawyer registered at the Ordine degli Avvocati di Milano (Bar Council of Milan). Does not generally offer notarial services.",
  },
  {
    contactName: "Ian Tully",
    organisationName: "Curtis, Mallet-Prevost, Colt & Mosle llp",
    email: "itully@curtis.com",
    website: "http://www.curtis.com/sitecontent.cfm?pageid=8&itemid=279",
    telephone: "+39 02 762 320 28",
    address: "Milan",
    legalAid: "No",
    proBonoService: "No",
    description:
      "Solicitor of the Supreme Court of England and Wales, qualified Italian lawyer registered with the Consiglio dell’Ordine degli Avvocati di Milano (Bar Council of Milan)",
  },
  {
    contactName: "Filippo Zuti Giachetti",
    organisationName: "BASP Bei-Ariani-Salvatori & Partners",
    email: "Filippo.zutigiachetti@basp.it",
    website: "http://www.basp.it",
    telephone: "+39 055 0948210",
    address: "Milan and Florence",
    legalAid: "No",
    proBonoService: "No",
    description:
      "Solicitor of the Supreme Court of England and Wales and qualified Italian lawyer",
  },
  {
    contactName: "Fernanda Stefani Araujo",
    organisationName: "Giambrone Law Firm",
    email: "Fernanda.stefani@giambronelaw.com",
    website: "https://www.giambronelaw.com",
    telephone: "+39 02 9475 4184; +39 338 247 6424; +44 (0)7383 828368",
    address: "Milan, Rome",
    legalAid: "No",
    proBonoService: "No",
    description:
      "Solicitor of the Supreme Court of England and Wales and Avvocato Stabilito in the Ordine degli Avvocati di Trapani",
  },
];
