export default [
  {
    contactName: "Andrea Colorio",
    lawFirmName: "Platter Ausserer Bauer + Partner",
    email: "colorio@pmab.it",
    website: "http://www.pmab.it",
    telephone: "+39 3471131314",
    address: "Via Alto Adige, 40",
    postcode: "39100",
    city: "Bolzano",
    legalPracticeAreas: "Corporate; Intellectual property; International; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Carlo Alberto Boscarolli",
    lawFirmName: "Studio Legale Associato Boscarolli",
    email: "avvocati@boscarolli.it",
    website: "http://www.boscarolli.it",
    telephone: "+39 0471 266300",
    address: "Via Orazio, 33",
    postcode: "39100",
    city: "Bolzano",
    legalPracticeAreas: "Criminal; Family; Health; Personal injury",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Elena Biaggioni",
    lawFirmName: "Studio Legale Avv. Elena Biaggioni",
    email: "studio@biaggioni.it",
    telephone: "+39 0461 234100",
    address: "Via A. Diaz, 8",
    postcode: "38122",
    city: "Trento",
    legalPracticeAreas: "Criminal",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Nicola Canestrini",
    lawFirmName: "canestriniLex",
    email: "nicola.canestrini@canestrinilex.it",
    website: "http://www.canestriniLex.com",
    telephone: "+39 0464 436688",
    address: "Piazza del Podestà, 10",
    postcode: "38068",
    city: "Rovereto",
    legalPracticeAreas: "Criminal; Personal injury",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
];
