export default [
  {
    contactName: "Alessandro Mazza",
    organisationName: "Studio Legale Giardini Mazza Sanvido e Associati",
    email: "alessandro.mazza@studiolegale.to.it",
    website: "http://www.studiolegale.to.it",
    telephone: "+39 0114335686",
    address: "Via Grassi, 9",
    postcode: "10138",
    city: "Torino",
    legalPracticeAreas:
      "Criminal; Employment; Family; Health; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Alessandro Rho",
    email: "avvalessandrarho@ordineavvocatinovara.it",
    telephone: "+39 0321 611737",
    address: "Via Magnani Ricotti, 5",
    postcode: "28100",
    city: "Novara",
    legalPracticeAreas: "Civil; Divorce; Land; Labour",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Andrea Sardo",
    organisationName: "Lexinto Avvocati",
    email: "a.sardo@lexinto.it",
    website: "http://www.lexinto.it",
    telephone: "+39 011 7654734",
    address: "Via Bernardino Drovetti, 15",
    postcode: "10138",
    city: "Torino",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Intellectual property; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Eugenio Remus",
    organisationName: "Studio Legale Remus",
    email: "eugenio.remus@gmail.com",
    telephone: "+39 161 212950",
    address: "Corso Fiume 5/B",
    postcode: "13100",
    city: "Vercelli",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Family; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Gabriele Pezzano",
    organisationName: "Avvocato Gabriele Pezzano",
    email: "gp@gabrielepezzano.it",
    website: "http://www.gabrielepezzano.it",
    telephone: "+39 011 7654734",
    address: "Via B. Drovetti, 15",
    postcode: "10138",
    city: "Torino",
    legalPracticeAreas: "Bankruptcy; Corporate; Criminal",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Marco; Umberto; Giulia Bona; Oliva; Oberto",
    organisationName: "Bona Oliva e Associati",
    email: "bona@mbolaw.it",
    website: "http://www.mbolaw.it",
    telephone: "+39 0115111005",
    address: "Via Pietro Giannone, 1",
    postcode: "10121",
    city: "Torino",
    legalPracticeAreas: "Employment; International; Personal injury",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Matteo Guidotti",
    organisationName: "Studio Legale Associato D&M Legal",
    email: "m.guidotti@dmlegal.eu",
    website: "http://www.dmlegal.eu",
    telephone: "+39 011 5184486",
    address: "Via Brofferio, 1",
    postcode: "10121",
    city: "Torino",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Intellectual property; International; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Paola Ciccarelli",
    organisationName: "Bonatti Sattanino Studio Legale Associato",
    email: "legale@bsavvocati.it",
    website: "http://www.studiobonatti.it",
    telephone: "+39 114334444",
    address: "Corso Vittorio Emanuele II, 94",
    postcode: "10121",
    city: "Torino",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Paolo Garrone",
    organisationName: "Avvocato Paolo Garrone",
    email: "avv.paologarrone@gmail.com",
    telephone: "+39 338 8353034",
    address: "Via Alberto Sordi, 36",
    postcode: "10095",
    city: "Grugliasco",
    legalPracticeAreas:
      "Corporate; Employment; Family; Health; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Raffaella Zucchetti",
    email: "raffaellazucchetti@libero.it",
    telephone: "+39 393 8881986",
    address: "Largo Luigi Cibrario, 11",
    postcode: "10143",
    city: "Torino",
    legalPracticeAreas: "Criminal; Family; Immigration",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Stefano Faraoni",
    organisationName: "Athena S.r.l. S.t.a.",
    email: "stefano.faraoni@athenalaw.it",
    website: "http://www.athenalaw.it",
    telephone: "+39 349 1659915",
    address: "Via Susa, 31",
    postcode: "10138",
    city: "Torino",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
];
