export default [
  {
    contactName: "Aleksandra Broom",
    organisationName: "Oliver & Partners",
    email: "a.broom@oliverpartners.it",
    website: "http://www.oliverpartners.it/our-team/aleksandra-broom/",
    telephone: "+39 06 45 777 174",
    address: "Rome",
    legalAid: "No",
    proBonoService: "No",
    description:
      "Solicitor of Supreme Court of England and Wales and registered at the Ordine degli Avvocati di Roma as an Avvocato Stabilito",
  },
  {
    contactName: "Roberto Gaglione",
    organisationName: "Slig Law",
    email: "info@sliglaw.com",
    website: "http://www.sliglaw.com/attorneys/",
    telephone: "+39 06 8419662",
    address: "Rome",
    legalAid: "No",
    proBonoService: "No",
    description:
      "Solicitor of the Supreme Court of England and Wales and qualified Italian lawyer",
  },
  {
    contactName: "Giulio Marini",
    email: "marini.giulio@pec.it",
    telephone: "+39 06 51 60 57 08",
    address: "Rome, Ascoli Piceno",
    legalAid: "No",
    proBonoService: "No",
    description: "Scottish solicitor and notary public",
  },
  {
    contactName: "Charlotte Oliver",
    organisationName: "Oliver & Partners",
    email: "c.oliver@oliverpartners.it",
    website: "http://www.oliverpartners.it/our-team/charlotte-oliver/",
    telephone: "+ 39 06 45 777 174; + 39 06 45 777 350",
    address: "Rome",
    legalAid: "No",
    proBonoService: "No",
    description:
      "Solicitor of the Supreme Court of England and Wales and registered at the Ordine degli Avvocati di Roma as an Avvocato Integrato",
  },
  {
    contactName: "Fernanda Stefani Araujo",
    organisationName: "Giambrone Law Firm",
    email: "Fernanda.stefani@giambronelaw.com",
    website: "https://www.giambronelaw.com",
    telephone: "+39 02 9475 4184; +39 338 247 6424; +44 (0)7383 828368",
    address: "Rome, Milan",
    legalAid: "No",
    proBonoService: "No",
    description:
      "Solicitor of the Supreme Court of England and Wales and Avvocato Stabilito in the Ordine degli Avvocati di Trapani",
  },
  {
    contactName: "Piers William Jennings",
    organisationName: "Jennings Law",
    email: "piers@zennings.com",
    telephone: "+39 334 74265760",
    address: "Rome",
    legalAid: "No",
    proBonoService: "No",
    description: "Solicitor of the Supreme Court of England and Wales",
  },
];
