export default [
  {
    contactName: "Alessandro Bonta",
    lawFirmName: "Avvocati.Us PLLC",
    email: "info@avvocati.us",
    telephone: "+39 375 5725237",
    address: "Piazza del Popolo, 18",
    postcode: "00187",
    city: "Roma",
    legalPracticeAreas:
      "Criminal; Employment; Family; Health; Immigration; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Carlo Dalla Vedova",
    lawFirmName: "Dalla Vedova Studio Legale",
    email: "dvsl@dallavedova.com",
    telephone: "+39 06 4440821",
    address: "Via Vittorio, 12 Bachelet",
    postcode: "00185",
    city: "Roma",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Charlotte Oliver",
    lawFirmName: "Oliver & Partners",
    email: "legal@oliverpartners.it",
    telephone: "+39 333 2937921",
    address: "Piazza Capranica, 78",
    postcode: "00186",
    city: "Rome",
    legalPracticeAreas: "Family; Immigration; International; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Claudia Bortolani",
    lawFirmName: "Legal Grounds Avvocati",
    email: "c.bortolani@legalgrounds.eu",
    telephone: "+39 349 6221364",
    address: "Via A. Bertoloni, 55",
    postcode: "00197",
    city: "Roma",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Health; Immigration; Intellectual property; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Daniela Piccioni",
    lawFirmName: "Lex Consilium",
    email: "avvdanielapiccioni@gmail.com",
    telephone: "+39 06 39736280",
    address: "Via Andrea Doria, 64",
    postcode: "00192",
    city: "Roma",
    legalPracticeAreas:
      "Honorary Legal Advisor to the British Embassy Rome; Criminal; Civil; Family; Insurance",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Domenico Plateroti",
    lawFirmName: "International Law Firm Iorio & Parteners",
    email: "avv.dplateroti@gmail.com",
    telephone: "+39 347 8792285",
    address: "Via Tacito, 50",
    postcode: "00193",
    city: "Roma",
    legalPracticeAreas:
      "Bankruptcy; Criminal; Health; Immigration; International; Maritime",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Elena Capriati",
    lawFirmName: "Capriati Carbone & Partners Law Firm",
    email: "ecapriati@cc-partners.it",
    telephone: "+39 0635072132",
    address: "Via Giuseppe Taverna, 76",
    postcode: "00135",
    city: "Roma",
    legalPracticeAreas: "Family; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Elvira Marzano",
    lawFirmName: "Marzano Avvocati Associati",
    email: "ira@marzanolaw.it",
    telephone: "+39 089 224842",
    address: "Via Nazionale, 69",
    postcode: "00184",
    city: "Rome",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Francesca Catherine Dimunno",
    lawFirmName: "Consulia Studio Legale e Commerciale",
    email: "dimunno@consulia.it",
    telephone: "+39 06 688 02363",
    address: "Piazza S. Andrea della Valle, 3",
    postcode: "00186",
    city: "Roma",
    legalPracticeAreas:
      "Corporate; Criminal; Family; Health; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Francesco Maresca",
    lawFirmName: "Studio Legale Maresca",
    email: "avv.fmaresca@gmail.com",
    telephone: "+39 335 7059597; +39 06 3221351",
    address: "Via Ennio Quirino Visconti, 20",
    postcode: "00193",
    city: "Roma",
    legalPracticeAreas: "Bankruptcy; Corporate; Criminal; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Giandomenico De Tullio",
    lawFirmName: "De Tullio Law Firm",
    email: "info@detulliolawfirm.com",
    telephone: "+39  06 4227 2230",
    address: "Via Antonio Salandra, 18",
    postcode: "00187",
    city: "Roma",
    legalPracticeAreas: "International; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Marco Calabrese",
    lawFirmName: "Family Law Italy",
    email: "m.calabrese@familylawitaly.com",
    telephone: "+39 06 8075014",
    address: "Via Domenico Chelini, 20",
    postcode: "00197",
    city: "Roma",
    legalPracticeAreas: "Family; International",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Mariafelicita Dolci",
    email: "mariadolci.legale@gmail.com",
    telephone: "+39 3487782404",
    address: "Via Tiburtina 352",
    postcode: "00159",
    city: "Roma",
    legalPracticeAreas:
      "Criminal; Immigration; Penitentiary; Juvenile; Intellectual property; Extradition and European Arrest Warrant; Human Rights",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Nicholas Scott",
    lawFirmName: "Scott & Partners International Law Firm",
    email: "info@scottandpartners.com",
    telephone: "+39 06 89016876",
    address: "Viale angelico 78",
    postcode: "00195",
    city: "Roma",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Immigration; International; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Nicoletta Caruso",
    lawFirmName: "Studio Caruso",
    email: "legalenquiry@studio-caruso.com",
    telephone: "+39 06 7720 4581",
    address: "Piazza Re di Roma, 3",
    postcode: "00183",
    city: "Roma",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Ombretta Paoletti",
    lawFirmName: "Studio legale Ombretta Paoletti",
    email: "ombrettapaoletti1@gmail.com",
    telephone: "+39 3471581428",
    address: "Largo XII Settembre, 4",
    postcode: "01017",
    city: "Tuscania",
    legalPracticeAreas:
      "Criminal; Employment; Family; Health; Immigration; Intellectual property; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Riccardo, Ernesto Di Vizio",
    lawFirmName: "Dviuris Law Firm",
    email: "info@dviuris.com",
    telephone: "+39 0776 310673",
    address: "Piazza Marconi 20",
    postcode: "03043",
    city: "Cassino",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Health; Intellectual property; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Roberta Ceschini",
    lawFirmName: "Ceschini & Restignoli",
    email: "rceschini@crlegal.it",
    telephone: "+39 06 3216 571",
    address: "Viale Giuseppe Mazzini, 4",
    postcode: "00195",
    city: "Roma",
    legalPracticeAreas: "Criminal; Family; International; Personal injury",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Rodrigo Carè",
    lawFirmName: "CARE - International Counsel",
    email: "rodrigo.care@careinternationalcounsel.com",
    telephone: "+39 068 415 687",
    address: "c/o Studio Legale Abenavoli - Viale Liegi, 14",
    postcode: "00198",
    city: "Roma",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Family; International; Personal injury",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Susanna Beltramo",
    lawFirmName: "Studio Legale Beltramo",
    email: "slb@beltramo.biz",
    telephone: "+39 06 4817747",
    address: "Via Vittorio Veneto 84",
    postcode: "00187",
    city: "Roma",
    legalPracticeAreas:
      "Bankruptcy; Corporate; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Walter De Agostino",
    lawFirmName: "Studio Legale De Agostino",
    email: "walterdeagostino@studiolegaledeagostino.eu",
    telephone: "+39 335 8159832",
    address: "Piazza Adriana, 15",
    postcode: "00193",
    city: "Roma",
    legalPracticeAreas:
      "Criminal; Extradition and European Arrest Warrant; Human Rights",
    legalAid: "Yes",
    proBonoService: "No",
  },
];
