version: "3.9"
services:
  postgres:
    platform: linux/amd64
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    # if you are on Mac M1 please use the image below
    # see https://github.com/docker/for-mac/issues/5122
    # image: "gangstead/postgis:13-3.1-arm"
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass redispassword
    ports:
      - 6379:6379
  lists:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm run start:ci
    environment:
      DATABASE_URL: "postgresql://master:postgrespass@postgres:5432/lists"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_PASSWORD: redispassword
      REDIS_CLUSTER_MODE: false
      FORM_RUNNER_URL: "apply:3001"
    depends_on:
      - postgres
      - redis 
      - apply
  apply:
    build:
      context: "docker/apply"
      dockerfile: Dockerfile
    ports: 
      - 3001:3001
    depends_on:
      - redis

  