process.env.DATABASE_URL = "postgresql://dumb";
process.env.LOCATION_SERVICE_ACCESS_KEY = "LOCATION_SERVICE_ACCESS_KEY";
process.env.LOCATION_SERVICE_SECRET_KEY = "LOCATION_SERVICE_SECRET_KEY";
process.env.LOCATION_SERVICE_INDEX_NAME = "LOCATION_SERVICE_INDEX_NAME";
process.env.REDIS_HOST = "localhost";
process.env.REDIS_PORT = "6379";
process.env.REDIS_PASSWORD = "redispassword";
process.env.SERVICE_DOMAIN = "test-domain";
process.env.SERVICE_NAME = "Service Name";
process.env.LOCAL_HOST = "false";

process.env.GA_TRACKING_ID = "123ABC";
process.env.GA_API_SECRET = "123ABC";

process.env.GOVUK_NOTIFY_API_KEY = "123_Notify_API_Key";
process.env.GOVUK_NOTIFY_PROFESSIONAL_APPLICATION_EMAIL_CONFIRMATION_TEMPLATE_ID =
  "123ABC";
process.env.GOVUK_NOTIFY_POST_NEW_PROFESSIONAL_APPLICATION_RECEIVED_TEMPLATE_ID =
  "123ABC";
process.env.GOVUK_NOTIFY_AUTHENTICATION_EMAIL_TEMPLATE_ID = "123ABC";
process.env.GOVUK_NOTIFY_DATA_PUBLISHED_TEMPLATE_ID = "123ABC";
