process.env.LOCATION_SERVICE_ACCESS_KEY = "LOCATION_SERVICE_ACCESS_KEY"
process.env.LOCATION_SERVICE_SECRET_KEY = "LOCATION_SERVICE_SECRET_KEY"
process.env.LOCATION_SERVICE_INDEX_NAME = "LOCATION_SERVICE_INDEX_NAME";
