export default [
  {
    contactName: "Ralph Smith",
    lawFirmName: "Gómez-Acebo & Pombo Abogados S.L.P.",
    website: "https://www.ga-p.com/",
    telephone: "+34 91 582 91 00",
    address: "Castellana 216, 28046 Madrid",
    regionsServed: "All regions in Spain",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Health; Intellectual Property; International; Maritime; Personal Injury; Real Estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Rosana Hallett",
    lawFirmName: "Gómez-Acebo & Pombo",
    website: "https://www.ga-p.com/oficina/bilbao/",
    telephone: "+34 94 415 70 15",
    address: "Plaza Euskadi 5, planta 19, Bilbao 48009",
    regionsServed: "Bilbao",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Intellectual Property; International; Real Estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "María García de la Concha",
    lawFirmName: "Gómez-Acebo & Pombo",
    website: "https://www.ga-p.com/en/office/vigo-en/",
    telephone: "+34 91 582 91 00",
    address: "Colón 36, 4º, 36201 Pontevedra, Vigo",
    regionsServed: "Vigo",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Intellectual Property; Maritime; Personal Injury; Real Estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "César Gerardo Ayala Canales",
    lawFirmName: "All Law",
    website: "http://www.all-law.es/",
    telephone: "+34 91 578 05 60",
    address: "Paseo de la Castellana 140, 10ºD, 28046 Madrid",
    regionsServed: "Madrid, Lanzarote",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Family; Personal Injury; Real Estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Oscar Baeza Chibel",
    lawFirmName: "Baeza Abogados",
    telephone: "+34 649 05 47 99",
    address: "Calle Pensamiento, 27 - Izq. 3º 3 - 28020 Madrid",
    regionsServed: "All regions in Spain",
    legalPracticeAreas:
      "Criminal; Employment; Family; Immigration; Personal Injury",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Margaret J. Hauschild Rey",
    lawFirmName: "Bennet&Rey",
    website: "http://www.bennetrey.com/en/",
    telephone: "+34 91 186 32 68",
    address: "Paseo de la Castellana, 119, 2º D, 28046 Madrid",
    regionsServed: "All regions in Spain",
    legalPracticeAreas:
      "Criminal; Employment; Family; Immigration; International; Real Estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Juan-Antonio Berdejo",
    lawFirmName: "Berdejo-Abogados",
    website: "https://berdejoabogados.eu/",
    telephone: "+34 94 222 05 87",
    address: "Calle Lealtad, 19, 1-C, 39002 Santander",
    regionsServed: "Cantabria, Castilla-León",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Tax; Real Estate; Family; Health; International; Criminal",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Gustavo Carlos Duguech Torriente",
    lawFirmName: "Duguech & Dip",
    website: "https://duguechdip.com/",
    telephone: "+34 91 825 92 53",
    address:
      "Calle Fernandez de la Hoz, nº 27, Ground Floor - Left, 28010 Madrid",
    regionsServed: "All regions in Spain",
    legalPracticeAreas:
      "Corporate; Immigration; Family; Real Estate; Employment; International",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Viviana Echeverria Pascual",
    lawFirmName: "Echeverria Abogados",
    website: "https://www.echeverriaabogados.com/en/",
    telephone: "+34 94 342 57 26",
    address: "Antonio Maria Labaien 14 - 4º B, 20009 San Sebastián",
    regionsServed: "Guipuzcoa - País Vasco",
    legalPracticeAreas: "Immigration",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Elena Garrido Martín",
    lawFirmName: "Sánchez-Cervera Abogados",
    website: "https://www.sanchez-cervera.com",
    telephone: "+34 91 411 48 78",
    address: "Calle General Oráa, 26, 28006, Madrid",
    regionsServed: "All regions in Spain",
    legalPracticeAreas:
      "Corporate; Criminal; Family; Inheritance; International; Personal Injury; Real Estate;",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Florina García González",
    lawFirmName: "Florina García y Asociados",
    website: "http://www.florinag.com/en/home/",
    telephone: "+34 98 523 45 55",
    address: "Calle Uría 19, entresuelo izquierda, 33003 Oviedo (Asturias)",
    regionsServed: "Asturias",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Intellectual Property; International; Personal Injury; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Elena Lino Garcia",
    lawFirmName: "Galicia Property Lawyers",
    website: "https://galiciapropertylawyers.net/",
    telephone: "+34 647 42 25 01",
    address: "García Camba nº 6  4º A  Pontevedra 36001",
    regionsServed: "Asturias, Cantabria, Galicia, Madrid",
    legalPracticeAreas: "Family; International; Personal Injury; Real Estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Lucía Goy Mastromiechele",
    lawFirmName: "Goy Gentile Abogados",
    website: "https://www.goygentile.com/en/",
    telephone: "+34 91 435 45 19",
    address: "Calle Ayala 17, 1C, 28001 Madrid",
    regionsServed: "All regions in Spain",
    legalPracticeAreas:
      "Corporate; Family; Immigration; International; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Ramón Bustillo",
    lawFirmName: "InheritanceSpain",
    website: "http://www.inheritancespain.com/",
    telephone: "+34 636 54 24 65",
    address: "Calle Asturias 21 1 D, Oviedo, 33004",
    regionsServed: "All regions in Spain",
    legalPracticeAreas:
      "Family; Tax; Personal Injury; Real Estate; Inheritance",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Javier Bicarregui",
    lawFirmName: "Iusfinder Abogados",
    website: "http://www.iusfinder.com/",
    telephone: "+34 94 465 70 00",
    address: "Gran Via 17, Dpto 402, Bilbao, 48001",
    regionsServed: "All regions in Spain",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Family; International; Real Estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Javier Frías",
    lawFirmName: "Javier Frías",
    telephone: "+34 635 53 68 98",
    address: "Calle Capitán Haya 33, 10D, 28020, Madrid",
    regionsServed: "All regions in Spain",
    legalPracticeAreas: "International; Family; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Juan Manuel Batuecas Florindo",
    lawFirmName: "Juan Manuel Batuecas & Associates",
    website: "http://www.asesoriayabogados.com/",
    telephone: "+34 646 37 38 87",
    address: "Santiago Alió, 9, 28018 Madrid",
    regionsServed: "All regions in Spain",
    legalPracticeAreas:
      "Criminal; Family; Immigration; Personal Injury; Real Estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Fernando Martínez",
    lawFirmName: "Martínez Sanz Abogados",
    website: "http://martinezsanzabogados.com/?lang=en",
    telephone: "+34 91 192 20 12",
    address: "Paseo General Martínez Campos, 42, bajo 28010 Madrid",
    regionsServed: "Madrid, Comunidad Valenciana",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; International; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Joseba Renobales",
    lawFirmName: "Renobales, Mariscal, Castresana, Abogados & Asociados",
    website: "https://www.abogadoempresayfamilia.com/",
    telephone: "+34 94 423 40 00",
    address: "Alameda Recalde 27, 1, 48009 Bilbao",
    regionsServed: "All regions in Spain",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Family; Health; Intellectual Property; International; Personal Injury; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Rocco Caira",
    lawFirmName: "Rocco Caira",
    website: "http://www.caira.es/",
    telephone: "+34 94 475 06 96",
    address: "Avda. Madariaga 1, 48014 Bilbao",
    regionsServed: "Basque Country, Navarra, Cantabria",
    legalPracticeAreas: "Corporate; International",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Jeremy Scudamore",
    lawFirmName: "Scudamore Law",
    website: "http://www.scudamore.es/en/",
    telephone: "+34 91 593 91 26",
    address: "Plaza de Castilla 3, 15ª E2, 28046 Madrid",
    regionsServed: "All regions in Spain",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Family; Immigration; Intellectual Property; International; Personal Injury; Real Estate; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Bianca Sharma Sharma",
    lawFirmName: "Sharma Abogados",
    website: "http://www.emergenciaspenales.com",
    telephone: "+34 91 326 95 23",
    address:
      "Via de las Dos Castillas, 33, Atica 4 B-A, Pozuelo de Alarcón, 28224 Madrid",
    regionsServed: "All regions in Spain",
    legalPracticeAreas:
      "Corporate; Criminal (emergencies); Family; Health; Immigration; Intellectual Property; Real Estate; Personal Injury;",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Carolina Trujillo Garzon",
    lawFirmName: "Trujillo Garzon Legal Consulting S.L.",
    website: "http://www.tglegalconsulting.com",
    telephone: "+34 619 56 92 62",
    address: "Plaza de Castilla 3, 28046, Madrid",
    regionsServed: "Madrid",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Health; Immigration; Personal Injury; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Andrea San Román",
    lawFirmName: "Valero San Román SLP",
    website: "https://valerosanroman.com/",
    telephone: "+34 647 78 52 30",
    address: "Calle Suero de Quiñones 38, 2º izq., 28002 Madrid",
    regionsServed: "All regions in Spain",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Family; Immigration; Intellectual Property; International; Personal Injury; Real Estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
];
