export default [
  {
    contactName: "Valle García de novales",
    lawFirmName: "A\\V Asesores, A.I.E.",
    website: "http://www.av-asesores.com",
    telephone: "(+34) 976234029",
    address: "Paseo Constitución 21, 4ºdcha. 50001 Zaragoza",
    regionsServed: "Aragón, Basque Country, Andalusia",
    legalPracticeAreas: "Corporate; International",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Anna Abad",
    lawFirmName: "Abad Associats",
    website: "https://www.abadassociats.com",
    telephone: "(+34) 972818901",
    address: "Ginesta, 40 Platja d’Aro (Girona)",
    regionsServed: "Girona, Barcelona.",
    legalPracticeAreas: "Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Albert Forment",
    lawFirmName: "Aft Iure Legal",
    website: "http://www.aftiure.com",
    telephone: "(+34) 616614764",
    address: "Calle Comte d’Urgell-272 Entresuelo 3ª 08036 Barcelona",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Criminal; Employment; Family; Health; Immigration; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Jonathan Hinkson",
    lawFirmName: "Augé Legal & Fiscal",
    website: "http://www.augelegalfiscal.com",
    telephone: "(+376) 803 636",
    address:
      "Carrer Pere d’Urg, 10 (5e planta) - Andorra la vella (PRINCIPALITY OF ANDORRA)",
    regionsServed: "Principality of Andorra",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Immigration; Intellectual property; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Lourdes Santisteban",
    lawFirmName: "Avalaw Legal Services SLP",
    website: "http://www.avasla.com",
    telephone: "(+34) 934814349",
    address: "Rambla Catalunya 25, 1-1",
    regionsServed: "Catalonia, Madrid",
    legalPracticeAreas:
      "Corporate; Immigration; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Montserrat Balart Torrequebrada",
    lawFirmName: "Balart Advocats",
    email: "m.balart@balartadvocats.com",
    telephone: "(+376) 829 829",
    address:
      "Despatx 4, planta 2, Escala C, 59 - 65 Carrer Prat de la Creu, Andorra La Vella, AD500, ANDORRA",
    regionsServed: "Andorra",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Immigration; Intellectual property; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Melanie Cachafeiro Martínez",
    lawFirmName: "Boni Iuris Advocats",
    email: "administracio@boniiurisandorra.com",
    telephone: "(+376) 821 518",
    address: "Ed. 92, Carrer Prat de la Creu, Andorra a Vella, AD500",
    regionsServed: "Andorra",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Luis Berenguer",
    lawFirmName: "Bufete Berenguer Comas Abogados",
    website: "http://www.bbcalegal.com/",
    telephone: "(+34) 933021143",
    address: "Paseo Colon 24, Pral 2, 08002 Barcelona",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Laura Nieto",
    lawFirmName: "Cases&Lacambra",
    website: "http://www.caseslacambra.com",
    telephone: "(+376) 728 001",
    address: "Manuel Cerqueda i Escaler, 3-5 - AD 700 Escaldes- Engordany",
    regionsServed: "Andorra",
    legalPracticeAreas: "Bankruptcy; Corporate; International",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Cristian Carci",
    lawFirmName: "CC Defensa Legal",
    telephone: "(+34) 610525064",
    address: "Gran de Garcia, 1 Principal, Barcelona 08012",
    regionsServed: "Catalonia",
    legalPracticeAreas: "Criminal; Family; Personal injury",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Sebastián Martín-Osorio",
    lawFirmName: "Despatx Osorio",
    email: "sebastianmartin@cada.ad",
    telephone: "(+376) 650 650",
    address:
      "Carrer Prat de la Creu nº. 96, Edifici Sucarà, 3º-1ª, AD500 Andorra La Vella, Principat d’Andorra (also Spanish office in Tarragona province)",
    regionsServed: "Principat d’Andorra and Catalonia",
    legalPracticeAreas:
      "Criminal; Family; Immigration; International; Personal injury",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Christopher Lee",
    lawFirmName: "Doménech Abogados",
    website: "http://www.domenechabogados.com/en/",
    telephone: "(+34) 934150677",
    address: "Madrazo 33, 08006 Barcelona",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Criminal; Employment; Family; Immigration; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Yolanda Lobao Andres",
    lawFirmName: "Ecija",
    website: "https://www.ecija.com",
    telephone: "(+34) 669475612",
    address: "Avda. Diagonal 458, 8, 08006 Barcelona",
    regionsServed: "All Regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Benjamin Rascagneres",
    lawFirmName: "Eurolex Andorra",
    website: "http://www.eurolexinternational.com",
    telephone: "(+376) 801 420",
    address: "7, Les Canals Street, Andorra la Vella, AD500",
    regionsServed: "Principality of Andorra",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Víctor Fabregat Rubiol",
    lawFirmName: "Fabregat Perulles Sales Abogados",
    website: "http://www.fabregat-perulles-sales.com/lawyers-en/index",
    telephone: "(+34) 932054231",
    address: "Plaza Bonanova 4, 1º, 1ª, Barcelona",
    regionsServed: "Barcelona, Madrid, Mallorca",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Family; Intellectual property; International; Maritime; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Graciano Cecchetti",
    lawFirmName: "Giambrone & Partners SLP",
    website: "https://www.giambronelaw.com/",
    telephone: "(+34) 932201627",
    address: "Calle Balmes 28, pral. 2, Barcelona, 08007 Spain",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Antonio Guillen Hederich",
    lawFirmName: "Gunnercooke LLP",
    website: "http://www.gunnercooke.com",
    telephone: "(+34) 649945633",
    address: "Av. Del Mar 10, 1º 1ª Gava mar, Barcelona, 08850",
    regionsServed: "Catalunya and Aragón",
    legalPracticeAreas: "Corporate; Family; International; Real estate; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Christian Herrera Petrus",
    lawFirmName: "Herrera Advocats",
    website: "http://www.herrera-advocats.com",
    telephone: "(+34) 932176362",
    address: "Vía Augusta n. 4, 6th floor, Barcelona 08006",
    regionsServed: "Catalonia, Madrid, Balearics",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Intellectual Property; International; Personal Injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Hugh McCairley",
    lawFirmName: "Hugh McCairley Abogado",
    website: "http://mccairley-abogado.com",
    telephone: "(+34) 934539029",
    address: "Calle Benet Mercadé 9-11 bajos 2ª, 08012 Barcelona",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Criminal; Family; Immigration; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Hugo Navarrete Gragera",
    lawFirmName: "Hugo Lawyer",
    website: "http://www.hugolawyer.com/",
    telephone: "(+34) 661886587",
    address: "Calle Princesa 34, 2º1, Barcelona 08003",
    regionsServed: "Catalonia, Valencia, Andalucia",
    legalPracticeAreas: "Real Estate Law, and Employment Law",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Luis Izquierdo",
    lawFirmName: "ILV Silver",
    website: "https://www.ilvsilver.com/",
    telephone: "(+34) 932411670",
    address: "Calle Santaló 10, 1º, 08021 Barcelona",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Corporate; Employment; International; Real Estate, Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Alexandru George Lazar",
    lawFirmName: "INTLAW Abogados y Consultores",
    website: "http://www.intlaw.eu",
    telephone: "(+34) 655837261",
    address: "Calle Aribau 175, Principal 1 B, 08036 Barcelona",
    regionsServed:
      "Barcelona, Catalunya, Andorra and Aragon, Madrid, Valencia and other Spanish territorries",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Anna Klevtsova",
    lawFirmName: "Klev&Vera International Law Firm",
    website: "http://www.klevvera.com/",
    telephone: "(+34) 931760190",
    address: "281 Valencia Street, 2-2, Barcelona 08009",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Corporate; Immigration; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Manuel Laguillo",
    lawFirmName: "LBL Partners",
    website: "https://www.lblpartners.es/",
    telephone: "(+34) 932182300",
    address: "123, 5B Josep Tarradellas Avenue, Barcelona, 08029",
    regionsServed: "Catalonia, Madrid",
    legalPracticeAreas: "Bankruptcy; Corporate; Employment; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Lidia Navas Esteller",
    lawFirmName: "LN Solicitors",
    website: "http://www.lnsolicitors.es",
    telephone: "(+34) 636046663",
    address: "Calle Sanchis Albella, 2, 2º , 12001 Castellon",
    regionsServed: "All Regions",
    legalPracticeAreas: "Criminal; Family; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Màrius Roch Izard",
    lawFirmName: "Màrius Roch Izard, Advocat",
    website: "http://rochadvocat.com",
    telephone: "(+34) 934397332",
    address: "Carrer Muntaner 161 2n 4ª 08036 Barcelona",
    regionsServed: "All regions",
    legalPracticeAreas: "Criminal; Personal injury",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Miquel Martí Torrents",
    lawFirmName: "Martí & Associats Lawyers and Consultants",
    website: "http://www.martilawyers.com",
    telephone: "(+34) 932016266",
    address: "Av. Diagonal 584 - Principal  -  E 08021  Barcelona",
    regionsServed: "All of Spain",
    legalPracticeAreas: "Corporate; Family; International; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Noelia Hernando Mercadé",
    lawFirmName: "Noelia Hernando Mercadé",
    website: "https://www.noeliahernandoabogada.com/",
    telephone: "(+34) 606582525",
    address: "Travessia del carrer nou, 1, entr., Falset (Tarragona) 43730",
    regionsServed: "Tarragona",
    legalPracticeAreas:
      "Employment; Family; Immigration; International; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Yolanda Porcel Martínez",
    lawFirmName: "Porcel Advocats",
    website: "http://www.porcel.legal/",
    telephone: "(+34) 972963413",
    address: "Calle Hortal de’n Pou 56 Baixos",
    regionsServed: "Girona",
    legalPracticeAreas:
      "Family; Health; Maritime; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Thais Delgado",
    lawFirmName: "Pragma Advocats",
    website: "http://www.pragma-advocats.com/",
    telephone: "(+34) 937588522",
    address: "Calle Altafulla 8 3-3, 08302 Mataró",
    regionsServed: "Barcelona",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; International; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Raffaele Tancredi",
    lawFirmName: "Raffaele Tancredi Abogados",
    telephone: "(+34) 622856625",
    address:
      "Carrer de la Granada del Penedés 10, entresuelo, 08006, Barcelona",
    regionsServed: "All regions except Andorra",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Victoriano Travieso",
    lawFirmName: "Stepinlaw SLP",
    website: "https://www.stepinlaw.com",
    telephone: "(+44)(0)934584353",
    address: "Roger de Flor 275, 2º 1ª, Barcelona, 08025",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Family; Intellectual property; International; Maritime; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Carlos Prieto Cid",
    lawFirmName: "Tarracoiuris S.L.",
    website: "https://www.tarracoiuris.com",
    telephone: "(+34) 977243021",
    address: "Carrer Macià Mallol i Bosch 5 B, Tarragona, E43005",
    regionsServed: "Catalonia",
    legalPracticeAreas: "Immigration; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Eduardo Vilá",
    lawFirmName: "Vilá Abogados",
    website: "https://www.vila.es",
    telephone: "(+34) 932156865",
    address: "Paseo de Gracia, 76, 1 - 2, 08008 Barcelona",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Intellectual property; International; Real estate",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Xavier Jordana",
    lawFirmName: "Xavier Jordana Advocats",
    email: "xjordana@andorra.ad",
    telephone: "(+376) 807 030",
    address:
      "Plaça Rebés 8, 2n, Andorra la Vella, AD500, Principality of Andorra",
    regionsServed: "Principality of Andorra",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; International; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
];
