export default [
  {
    contactName: "Alberto Batini",
    lawFirmName: "Batini Traverso Grasso & Associati",
    email: "a.batini@btglegal.it",
    website: "http://www.btglegal.it",
    telephone: "+39 348 7902191",
    address: "Via Camperio, 9 - 20123 Milano",
    legalPracticeAreas:
      "Bankruptcy; Corporate; International; Maritime; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Aldo Lorenzo Feliciani",
    lawFirmName: "Studio Legale Bonora e Associati",
    email: "a.feliciani@studiobonora.it",
    website: "http://www.studiobonora.it",
    telephone: "+39 02 76013210",
    address: "Piazzetta U. Giordano, 4 - 20122 Milano",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; International; Personal injury",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Alessandro Bossi",
    lawFirmName: "Studio Legale Bossi",
    email: "<info@slblaw.eu >",
    website: "http://www.slblaw.eu",
    telephone: "+39 02 58315151",
    address: "Via Alfredo Oriani 2 - 20122 Milano",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Family; International; Personal injury",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Alessandro Maria Tirelli",
    lawFirmName: "International Lawyers Associates",
    email: "alessandrotirelli@yahoo.it",
    website: "http://www.lawyeritalian.com",
    telephone: "+39 338 6222365",
    address: "Via Monte Napoleone, 8 - 20121 Milano",
    legalPracticeAreas: "Criminal",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Andrea Arcidiacono",
    lawFirmName: "Studio Legale Arcidiacono",
    email: "studio.arcidiacono@gmail.com",
    website: "https://studiolegalearcidiacono.com/",
    telephone: "+39 333 6892201",
    address: "Via Melchiorre Gioia , 4/A - 20124 Milano",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Immigration; Intellectual property; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Anna Scalzi",
    lawFirmName: "Scalzi Legal",
    email: "info@scalzi.it",
    website: "http://www.scalzi.it",
    telephone: "+39 347 2560738",
    address: "Piazza S. Agostino, 4/1 - 20123 Milano",
    legalPracticeAreas:
      "Corporate; Employment; Family; Immigration; Intellectual property; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Antonio Golino",
    lawFirmName: "Clifford Chance",
    email: "antonio.golino@cliffordchance.com",
    website: "http://www.cliffordchance.com",
    telephone: "+39 02 8063411",
    address: "Via Broletto 16 - 20121 Milano",
    legalPracticeAreas: "Criminal",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Benedetta Guzzoni",
    lawFirmName: "Studio Legale Guzzoni",
    email: "bg@guzzoni.net",
    website: "http://www.guzzoni.net",
    telephone: "+39 02 76008869",
    address: "Corso Magenta, 85 - 20123 Milano",
    legalPracticeAreas: "Criminal",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Carlo Bottino",
    lawFirmName: "Studio Legale Bottino",
    email: "info@studiolegalebottino.it",
    website: "http://www.italianlawfirm.co.uk",
    telephone: "+39 02 8356327",
    address: "Via Giambologna, 1 - 20136 Milano",
    legalPracticeAreas:
      "Bankruptcy; Employment; Family; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Claudio Piombo",
    lawFirmName: "NCL Legal",
    email: "avvclaudiopiombo@gmail.com",
    website: "http://www.nclegal.it",
    telephone: "+39 340 4836822",
    address: "Corso Vercelli, 11 - 20144 Milano",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Immigration; Intellectual property; International; Personal Injury; Real Estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Colin Jamieson",
    lawFirmName: "Studio Legale Avv. Jamieson",
    email: "colin@taxing.it",
    website: "http://www.jamieson.it",
    telephone: "+39 02 488 3945",
    address: "Via delle Betulle, 6, 20090 - Assago (MI)",
    legalPracticeAreas:
      "Corporate; Employment; Family; Intellectual property; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Cristiano Cominotto",
    lawFirmName: "AL Assistenza Legale",
    email: "c.cominotto@alassistenzalegale.it",
    website: "http://www.alassistenzalegale.it",
    telephone: "+39 335 59 28 732",
    address: "Piazza Cinque Giornate, 3 - 20129 Milano",
    legalPracticeAreas:
      "Corporate; Employment; Family; Health; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Daria Pesce",
    lawFirmName: "Studio Avv. Daria Pesce",
    email: "info@avvocatodariapesce.it",
    website: "http://www.avvocatodariapesce.it",
    telephone: "+39 02 5455553",
    address: "Via Colonnetta 5 - 20122 Milano",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Davide Palazzo",
    lawFirmName: "Palazzo Law Boutique",
    email: "avv.palazzo@palazzolawboutique.com",
    website: "http://palazzolawboutique.com",
    telephone: "+39 0287199463",
    address: "Via Ludovico il Moro, 135 - 20141 Milano",
    legalPracticeAreas:
      "Family; International; Italian Citizenship; Litigation; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Davide Cinelli",
    lawFirmName: "Studio Legale De Falco e Grompe",
    email: "davide.cinelli@defalcogrompe.com",
    website: "http://www.defalcogrompe.com",
    telephone: "+39 02 801031-2",
    address: "Corso Italia, 8 - 20122 Milano",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Emanuele Cammareri",
    lawFirmName: "Studio Legale Bresner Cammareri",
    email: "emanuele.cammareri@bcip.it",
    website: "http://www.bcip.it",
    telephone: "+39 349 7218642",
    address: "Via Aurelio Saffi, 23 - 20123 Milano",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Immigration; Intellectual property; International; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Fabrizio Bianchi Schierholz",
    lawFirmName: "Bianchi Schierholz & Partners",
    email: "studio@bianchischierholz.it",
    website: "http://www.bianchischierholz.it",
    telephone: "+39 02 866644",
    address: "Largo Richini, 2/A - 20122 Milano",
    legalPracticeAreas:
      "Corporate; Employment; Family; Intellectual property; International; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Francesco Senaldi",
    lawFirmName: "BSVA Studio Legale",
    email: "f.senaldi@bsva.it",
    website: "http://www.bsva.it",
    telephone: "+39 02 783811",
    address: "Via Borgonuovo, 9 - 20121 Milano",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Family; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Francesco Mangiameli",
    lawFirmName: "CTES Advisors",
    email: "francesco.mangiameli@ctes.it",
    website: "http://www.ctes.it",
    telephone: "+39 02 36574450",
    address: "Foro Buonaparte, 12 - 20121 Milano",
    legalPracticeAreas: "Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Giovanni Babino",
    lawFirmName: "Giovanni Babino",
    email: "foreignclients@bf-lawyers.com",
    website: "http://www.bf-lawyers.com",
    telephone: "+39 02 66981438",
    address: "Piazza Duca D’Aosta, 10 - 20124  Milan",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Inheritance; Maritime; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Lorenzo Da Pra Galanti",
    lawFirmName: "Iuraplus",
    email: "dapra@iuraplus.com",
    website: "http://www.iuraplus.com",
    telephone: "+39 02 80501156",
    address: "Via Vincenzo Bellini, 13 - 20122 Milano",
    legalPracticeAreas: "Bankruptcy; Corporate; International; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Luca Corabi De Marchi",
    lawFirmName: "Ughi e Nunziante",
    email: "l.corabi@unlaw.it",
    website: "http://www.unlaw.it",
    telephone: "+39 02 762171",
    address: "Via Zenale, 19 - 20123 Milano",
    legalPracticeAreas:
      "Corporate; Employment; Family; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Luca Salerno",
    lawFirmName: "Hanover Bond Law",
    email: "ls@hanoverbondlaw.com",
    website: "http://www.hanoverbondlaw.com",
    telephone: "+39 02 40707817",
    address: "Via Gustavo Modena, 3 - 20129 Milano",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Health; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Luciano Pizzi",
    lawFirmName: "A&P Legal",
    email: "lpizzi@aeplegal.com",
    website: "http://www.aeplegal.com",
    telephone: "+39 02 83466400",
    address: "Viale Majno, 11 - 20122 Milano",
    legalPracticeAreas: "Criminal",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Mark Anthony Simon Paolini",
    lawFirmName: "CDT Legal",
    email: "mpaolini@cdt.legal",
    website: "https://cdt.legal/",
    telephone: "+39 349 1401967",
    address: "CDT Legal, Via Fatebenefratelli , 19 Milano - 20121",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Intellectual property; International; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Massimo Dimarco",
    lawFirmName: "Dimarco & Partners International Law Firm",
    email: "m.dimarco@dimarcoandpartners.eu",
    website: "http://www.lawyer-italy.org",
    telephone: "+39 0289053510",
    address: "Via Francesco Sforza, 15 - 20154 Milano",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Family; Intellectual property; International; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Massimo Mascali",
    lawFirmName: "Studio Legale Mascali",
    email: "info@studio-mascali.it",
    website: "http://www.studio-mascali.it",
    telephone: "+39 035 238314",
    address: "Via Matris Domini, 21/A -24121 Bergamo",
    legalPracticeAreas: "Corporate; Family; Personal injury; Real Estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Michele Stratta",
    lawFirmName: "studio Legale Avv. Michele Stratta",
    email: "michele.stratta@hotmail.it",
    website: "http://www.studiolegalestratta.it",
    telephone: "+39 0444 326698",
    address: "Piazza Duomo, 5 -  36100 Vicenza",
    legalPracticeAreas: "Civil; Commercial; International Trade; Maritime",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Monica C. James",
    lawFirmName: "James & Co. - Legal Services in Italy",
    email: "info@james-legal.com",
    website: "http://www.james-legal.com",
    telephone: "+39 030 9911001",
    address:
      "Via Garibaldi, 29 - 25015 Desenzano del Garda (BS) / Via IV Novembre, 2 - 25121 Brescia",
    legalPracticeAreas:
      "Corporate; Employment; Family; International; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Paolo De’ Capitani di Vimercate",
    lawFirmName: "Studio Uckmar Associazione Professionale",
    email: "p.decapitani@uckmar.com",
    website: "http://www.studiouckmar.com/home.html",
    telephone: "+39 02 801085",
    address: "Via Agnello, 5 - 20121 Milano",
    legalPracticeAreas: "Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Perla Sciretti",
    lawFirmName: "Sciretti Avvocati",
    email: "perlex@perlex.it",
    website: "http://www.perlex.it",
    telephone: "+39 02 55185533",
    address: "Via della Signora, 2 - 20122 Milano",
    legalPracticeAreas: "Criminal",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Stefania Skonieczny",
    lawFirmName: "Giambrone&Partners",
    email: "stefania.skonieczny@giambronelaw.com",
    website: "http://www.giambronelaw.com",
    telephone: "+39 02 49481276",
    address: "Foro Buonaparte, 12 - 20121 Milano",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; International; Personal Injury; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Stefano Linares",
    lawFirmName: "Linares Associates PLLC",
    email: "info@linareslaw.com",
    website: "http://www.linareslaw.com",
    telephone: "+39 349 1723704",
    address: "Via P. Rondoni, 11 - 20146 Milano",
    legalPracticeAreas:
      "Corporate; Employment; Family; Immigration; Intellectual property; International; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Marzia Ghigliazza",
    lawFirmName: "Studio Legale Internazionale Ghigliazza-Rugani",
    email: "marzia.ghigliazza@gr-studio.eu",
    website: "https://www.iafl.com/fellows/marzia-ghigliazza/22695",
    telephone: "+39 02 72093417",
    address: "Via Valpetrosa, 1 - 20123 Milano",
    legalPracticeAreas:
      "International Family Law; Hague Conventions and Child Abduction; International Succession Law; Cross-border Mediator",
    legalAid: "No",
    proBonoService: "Yes",
  },
];
