/*
  Warnings:

  - The values [ANNUAL_REVIEW_START_ONE_MONTH_REMINDER_EMAIL,ANNUAL_REVIEW_START_ONE_WEEK_REMINDER_EMAIL,ANNUAL_REVIEW_START_ONE_DAY_REMINDER_EMAIL,WEEKLY_UNPUBLISH_POST_REMINDER_EMAIL,ONE_DAY_UNPUBLISH_POST_REMINDER_EMAIL,WEEKLY_UNPUBLISH_PROVIDER_REMINDER_EMAIL,ONE_DAY_UNPUBLISH_PROVIDER_REMINDER_EMAIL] on the enum `ListItemEvent` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ListItemEvent_new" AS ENUM ('NEW', 'OUT_WITH_PROVIDER', 'EDITED', 'ANNUAL_REVIEW', 'REVIEWED', 'UNPUBLISHED', 'PUBLISHED', 'PINNED', 'UNPINNED', 'DELETED', 'UNDEFINED', 'ANNUAL_REVIEW_START_ONE_DAY_REMINDER_EMAIL_SENT', 'ANNUAL_REVIEW_START_ONE_WEEK_REMINDER_EMAIL_SENT', 'ANNUAL_REVIEW_START_ONE_MONTH_REMINDER_EMAIL_SENT', 'ANNUAL_REVIEW_STARTED', 'UNPUBLISH_ONE_DAY_POST_REMINDER_EMAIL_SENT', 'UNPUBLISH_WEEKLY_POST_REMINDER_EMAIL_SENT', 'UNPUBLISH_ONE_DAY_PROVIDER_REMINDER_EMAIL_SENT', 'UNPUBLISH_WEEKLY_PROVIDER_REMINDER_EMAIL_SENT');
ALTER TABLE "Event" ALTER COLUMN "type" TYPE "ListItemEvent_new" USING ("type"::text::"ListItemEvent_new");
ALTER TYPE "ListItemEvent" RENAME TO "ListItemEvent_old";
ALTER TYPE "ListItemEvent_new" RENAME TO "ListItemEvent";
DROP TYPE "ListItemEvent_old";
COMMIT;

-- AlterTable
ALTER TABLE "List" ALTER COLUMN "nextAnnualReviewStartDate" SET DEFAULT NOW() + interval '1 year';
