-- This is an empty migration.

INSERT INTO
    "Country" ("updatedAt", name)
VALUES
  (NOW(), 'Afghanistan'),
  (NOW(), 'Albania'),
  (NOW(), 'Algeria'),
  (NOW(), 'American Samoa'),
  (NOW(), 'Andorra'),
  (NOW(), 'Angola'),
  (NOW(), 'Anguilla'),
  (NOW(), 'Antigua and Barbuda'),
  (NOW(), 'Argentina'),
  (NOW(), 'Armenia'),
  (NOW(), 'Aruba'),
  (NOW(), 'Australia'),
  (NOW(), 'Austria'),
  (NOW(), 'Azerbaijan'),
  (NOW(), 'Bahamas'),
  (NOW(), 'Bahrain'),
  (NOW(), 'Bangladesh'),
  (NOW(), 'Barbados'),
  (NOW(), 'Belarus'),
  (NOW(), 'Belgium'),
  (NOW(), 'Belize'),
  (NOW(), 'Benin'),
  (NOW(), 'Bermuda'),
  (NOW(), 'Bhutan'),
  (NOW(), 'Bolivia'),
  (NOW(), 'Bonaire, Sint Eustatius and Saba'),
  (NOW(), 'Bosnia and Herzegovina'),
  (NOW(), 'Botswana'),
  (NOW(), 'Brazil'),
  (NOW(), 'British Indian Ocean Territory'),
  (NOW(), 'British Virgin Islands'),
  (NOW(), 'Brunei'),
  (NOW(), 'Bulgaria'),
  (NOW(), 'Burkina Faso'),
  (NOW(), 'Myanmar'),
  (NOW(), 'Burundi'),
  (NOW(), 'Cambodia'),
  (NOW(), 'Cameroon'),
  (NOW(), 'Canada'),
  (NOW(), 'Cape Verde'),
  (NOW(), 'Cayman Islands'),
  (NOW(), 'Central African Republic'),
  (NOW(), 'Chad'),
  (NOW(), 'Chile'),
  (NOW(), 'China'),
  (NOW(), 'Comoros'),
  (NOW(), 'Congo'),
  (NOW(), 'Congo, Democratic Republic'),
  (NOW(), 'Cook Islands'),
  (NOW(), 'Costa Rica'),
  (NOW(), 'Côte d''Ivoire'),
  (NOW(), 'Cuba'),
  (NOW(), 'Curaçao'),
  (NOW(), 'Cyprus'),
  (NOW(), 'Northern Cyprus'),
  (NOW(), 'Czech Republic'),
  (NOW(), 'Denmark'),
  (NOW(), 'Djibouti'),
  (NOW(), 'Dominica'),
  (NOW(), 'Dominican Republic'),
  (NOW(), 'Ecuador'),
  (NOW(), 'Egypt'),
  (NOW(), 'El Salvador'),
  (NOW(), 'Equatorial Guinea'),
  (NOW(), 'Eritrea'),
  (NOW(), 'Estonia'),
  (NOW(), 'Ethiopia'),
  (NOW(), 'Falkland Islands'),
  (NOW(), 'Fiji'),
  (NOW(), 'Finland'),
  (NOW(), 'French Guiana'),
  (NOW(), 'French Polynesia'),
  (NOW(), 'Gabon'),
  (NOW(), 'Gambia'),
  (NOW(), 'Georgia'),
  (NOW(), 'Ghana'),
  (NOW(), 'Gibraltar'),
  (NOW(), 'Greece'),
  (NOW(), 'Grenada'),
  (NOW(), 'Guadeloupe'),
  (NOW(), 'Guatemala'),
  (NOW(), 'Guinea'),
  (NOW(), 'Guinea-Bissau'),
  (NOW(), 'Guyana'),
  (NOW(), 'Haiti'),
  (NOW(), 'Honduras'),
  (NOW(), 'Hong Kong'),
  (NOW(), 'Hungary'),
  (NOW(), 'Iceland'),
  (NOW(), 'Iran'),
  (NOW(), 'Iraq'),
  (NOW(), 'Ireland'),
  (NOW(), 'Israel'),
  (NOW(), 'Jamaica'),
  (NOW(), 'Japan'),
  (NOW(), 'Jordan'),
  (NOW(), 'Kazakhstan'),
  (NOW(), 'Kenya'),
  (NOW(), 'Kiribati'),
  (NOW(), 'Kosovo'),
  (NOW(), 'Kuwait'),
  (NOW(), 'Kyrgyzstan'),
  (NOW(), 'Laos'),
  (NOW(), 'Latvia'),
  (NOW(), 'Lebanon'),
  (NOW(), 'Lesotho'),
  (NOW(), 'Liberia'),
  (NOW(), 'Libya'),
  (NOW(), 'Liechtenstein'),
  (NOW(), 'Lithuania'),
  (NOW(), 'Luxembourg'),
  (NOW(), 'Macao'),
  (NOW(), 'Madagascar'),
  (NOW(), 'Malawi'),
  (NOW(), 'Malaysia'),
  (NOW(), 'Maldives'),
  (NOW(), 'Mali'),
  (NOW(), 'Malta'),
  (NOW(), 'Marshall Islands'),
  (NOW(), 'Martinique'),
  (NOW(), 'Mauritania'),
  (NOW(), 'Mauritius'),
  (NOW(), 'Mayotte'),
  (NOW(), 'Mexico'),
  (NOW(), 'Micronesia'),
  (NOW(), 'Moldova'),
  (NOW(), 'Monaco'),
  (NOW(), 'Mongolia'),
  (NOW(), 'Montenegro'),
  (NOW(), 'Montserrat'),
  (NOW(), 'Morocco'),
  (NOW(), 'Mozambique'),
  (NOW(), 'Namibia'),
  (NOW(), 'Nauru'),
  (NOW(), 'Nepal'),
  (NOW(), 'Netherlands'),
  (NOW(), 'New Caledonia'),
  (NOW(), 'New Zealand'),
  (NOW(), 'Nicaragua'),
  (NOW(), 'Niger'),
  (NOW(), 'Niue'),
  (NOW(), 'North Korea'),
  (NOW(), 'North Macedonia'),
  (NOW(), 'Norway'),
  (NOW(), 'Oman'),
  (NOW(), 'Pakistan'),
  (NOW(), 'Palau'),
  (NOW(), 'Panama'),
  (NOW(), 'Papua New Guinea'),
  (NOW(), 'Paraguay'),
  (NOW(), 'Peru'),
  (NOW(), 'Philippines'),
  (NOW(), 'Pitcairn Island'),
  (NOW(), 'Qatar'),
  (NOW(), 'Réunion'),
  (NOW(), 'Romania'),
  (NOW(), 'Russia'),
  (NOW(), 'Rwanda'),
  (NOW(), 'Saint Barthélemy'),
  (NOW(), 'Saint Helena, Ascension and Tristan da Cunha'),
  (NOW(), 'Saint Kitts and Nevis'),
  (NOW(), 'Saint Lucia'),
  (NOW(), 'Saint Vincent and the Grenadines'),
  (NOW(), 'Samoa'),
  (NOW(), 'San Marino'),
  (NOW(), 'São Tomé and Príncipe'),
  (NOW(), 'Saudi Arabia'),
  (NOW(), 'Senegal'),
  (NOW(), 'Serbia'),
  (NOW(), 'Seychelles'),
  (NOW(), 'Sierra Leone'),
  (NOW(), 'Singapore'),
  (NOW(), 'Slovakia'),
  (NOW(), 'Slovenia'),
  (NOW(), 'Solomon Islands'),
  (NOW(), 'Somalia'),
  (NOW(), 'South Africa'),
  (NOW(), 'South Georgia and South Sandwich Islands'),
  (NOW(), 'South Korea'),
  (NOW(), 'South Sudan'),
  (NOW(), 'Spain'),
  (NOW(), 'Sri Lanka'),
  (NOW(), 'St Maarten'),
  (NOW(), 'St Martin'),
  (NOW(), 'St. Pierre and Miquelon'),
  (NOW(), 'Sudan'),
  (NOW(), 'Suriname'),
  (NOW(), 'Eswatini'),
  (NOW(), 'Sweden'),
  (NOW(), 'Switzerland'),
  (NOW(), 'Syria'),
  (NOW(), 'Taiwan'),
  (NOW(), 'Tajikistan'),
  (NOW(), 'Tanzania'),
  (NOW(), 'Thailand'),
  (NOW(), 'The Occupied Palestinian Territories'),
  (NOW(), 'Timor-Leste'),
  (NOW(), 'Togo'),
  (NOW(), 'Tokelau'),
  (NOW(), 'Tonga'),
  (NOW(), 'Trinidad and Tobago'),
  (NOW(), 'Tunisia'),
  (NOW(), 'Turkey'),
  (NOW(), 'Turkmenistan'),
  (NOW(), 'Turks and Caicos Islands'),
  (NOW(), 'Tuvalu'),
  (NOW(), 'Uganda'),
  (NOW(), 'Ukraine'),
  (NOW(), 'United Arab Emirates'),
  (NOW(), 'United States'),
  (NOW(), 'Uruguay'),
  (NOW(), 'Uzbekistan'),
  (NOW(), 'Vanuatu'),
  (NOW(), 'Vatican City'),
  (NOW(), 'Venezuela'),
  (NOW(), 'Vietnam'),
  (NOW(), 'Wallis and Futuna Islands'),
  (NOW(), 'Western Sahara'),
  (NOW(), 'Yemen'),
  (NOW(), 'Zambia'),
  (NOW(), 'Zimbabwe');