version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.0.0
  node: circleci/node@5.0.0
  browser-tools: circleci/browser-tools@1.3.0

defaults: &defaults
  working_directory: ~/repo


jobs:
  test:
    <<: *defaults

    docker:
      - image: cimg/node:18.15.0-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-

      - run: npm i

      - run:
          name: Prisma generate
          command: npm run prisma:generate

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Run tests
          command: npm run test

      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules


  smoke:
    <<: *defaults
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true

    steps:
      - checkout


      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-deps-

      - run:
          name: build postgres
          command: |
            docker-compose build --build-arg PGP_PUB=$PGP_PUB --build-arg PGP_SECRET=$PGP_SECRET --build-arg PGP_OTRUST=$PGP_OTRUST postgres

      - run:
          name: build lists
          command: |
            docker login ghcr.io -u jenbutongit -p $GHCR_PULL_PAT
            COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build --no-cache lists apply
            docker ps


      - run:
          name: build scheduler images
          command: |
            docker-compose build scheduler-batch && docker-compose build scheduler-annual-review-worker

      - persist_to_workspace:
          root: ~/
          paths:
            - .

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache



      # - store_artifacts: # store videos so they are accessible via circleci. Only use when necessary since it will add additional time to the run.
      #     path: ~/repo/cypress/videos
      #     destination: videos


  smoke-run:
    <<: *defaults
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    parallelism: 2
    steps:
      - attach_workspace:
          at: ~/
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name:  run lists
          command: |
            docker-compose up -d lists apply
            docker ps

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-


      - run: # this will let you view logs from the apply and lists docker containers
          name: logs
          background: true
          command: docker-compose logs -f lists apply

      - run:
          environment:
            DATABASE_URL: "postgresql://master:postgrespass@localhost:5432/lists"
            CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
            CI_SMOKE_TEST: true
            CYPRESS_BASE_URL: http://localhost:3000
          name: Run smoke tests
          command: npx -y cypress run



  publish:
    <<: *defaults

    parameters:
      app:
        description: The app to build and publish. Pick from lists, lists-apply, lists-postgres.
        default: "lists"
        type: string

    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true

    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: "set $DOCKER_TAG"
          command:
            | # set $DOCKER_TAG as either the git tag that triggered the build, or the git sha (for deploy-test branch)
            if [ "<<pipeline.git.tag>>" == "" ]; then echo 'export DOCKER_TAG="<<pipeline.git.revision>>"' >> $BASH_ENV; else echo 'export DOCKER_TAG="<<pipeline.git.tag>>"' >> $BASH_ENV; fi

      - when:
          condition:
            equal: [lists, <<parameters.app>>]
          steps:
            - run:
                name: Publish docker image - lists
                command: |
                  eval $(aws ecr get-login --no-include-email --region eu-west-2)
                  docker build --build-arg NODE_ENV=production --build-arg=BUILD_MODE=prod --build-arg DOCKER_TAG=$DOCKER_TAG --target main -t 523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists:$DOCKER_TAG .
                  docker push 523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists:$DOCKER_TAG

      - when:
          condition:
            equal: [lists-apply, <<parameters.app>>]
          steps:
            - run:
                name: Publish docker image - apply
                command: |
                  eval $(aws ecr get-login --no-include-email --region eu-west-2)
                  docker build --build-arg DOCKER_TAG=$DOCKER_TAG -t 523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists-apply:$DOCKER_TAG docker/apply
                  docker push 523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists-apply:$DOCKER_TAG

      - when:
          condition:
            equal: [lists-postgres, <<parameters.app>>]
          steps:
            - run:
                name: build postgres
                command: |
                  docker-compose build \
                  --build-arg PGP_PUB=$PGP_PUB \
                  --build-arg PGP_SECRET=$PGP_SECRET \
                  --build-arg PGP_OTRUST=$PGP_OTRUST postgres
            - run:
                name: Publish docker image - lists-postgres
                command: |
                  eval $(aws ecr get-login --no-include-email --region eu-west-2)
                  docker tag repo_postgres 523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists-postgres:$DOCKER_TAG
                  docker push 523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists-postgres:$DOCKER_TAG

      - when:
          condition:
            equal: [lists-scheduler-batch, <<parameters.app>>]
          steps:
            - run:
                name: Publish docker image - annual review scheduled batch process
                command: |
                  eval $(aws ecr get-login --no-include-email --region eu-west-2)
                  docker build --build-arg DOCKER_TAG=$DOCKER_TAG --build-arg BUILD_MODE=ci --target scheduled -t 523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists-scheduler-batch:$DOCKER_TAG .
                  docker push 523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists-scheduler-batch:$DOCKER_TAG

      - when:
          condition:
            equal: [lists-scheduler-worker, <<parameters.app>>]
          steps:
            - run:
                name: Publish docker image - annual review scheduled worker process
                command: |
                  eval $(aws ecr get-login --no-include-email --region eu-west-2)
                  docker build --build-arg DOCKER_TAG=$DOCKER_TAG --build-arg BUILD_MODE=ci --target scheduled -t 523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists-scheduler-worker:$DOCKER_TAG .
                  docker push 523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists-scheduler-worker:$DOCKER_TAG

  deploy:
    <<: *defaults

    parameters:
      namespace:
        type: string

    machine:
      image: ubuntu-2004:202201-02

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Install the eksctl tool
          command: |
            if which eksctl > /dev/null; then
              echo "eksctl is already installed"
              exit 0
            fi

            mkdir -p eksctl_download
            curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
              | tar xz -C eksctl_download
            chmod +x eksctl_download/eksctl
            SUDO=""
            if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
              SUDO="sudo"
            fi
            $SUDO mv eksctl_download/eksctl /usr/local/bin/
            rmdir eksctl_download

      - run:
          name: Install OpenVPN
          command: |
            sudo apt-get update
            sudo apt-get install net-tools -y
            sudo apt-get install openvpn openvpn-systemd-resolved -y

      - run:
          name: Check IP before VPN connection
          command: |
            ip a
            echo "Public IP before VPN connection is $(curl checkip.amazonaws.com)"

      - run:
          name: VPN Setup
          background: true
          command: |
            echo $VPN_CLIENT_CONFIG | base64 --decode > /tmp/config.ovpn

            if grep -q auth-user-pass /tmp/config.ovpn; then
              if [ -z "${VPN_USER:-}" ] || [ -z "${VPN_PASSWORD:-}" ]; then
                echo "Your VPN client is configured with a user-locked profile. Make sure to set the VPN_USER and VPN_PASSWORD environment variables"
                exit 1
              else
                printf "$VPN_USER\\n$VPN_PASSWORD" > /tmp/vpn.login
              fi
            fi

            SYS_RES_DNS=$(systemd-resolve --status | grep 'DNS Servers'|awk '{print $3}')
            echo $SYS_RES_DNS

            phone_home=$(ss -Hnto state established '( sport = :ssh )' | head -n1 | awk '{ split($4, a, ":"); print a[1] }') || $(sudo netstat -an | grep ':22 .*ESTABLISHED' | head -n1 | awk '{ split($5, a, ":"); print a[1] }')
            echo $phone_home

            vpn_command=(sudo openvpn
              --config /tmp/config.ovpn
              --route $SYS_RES_DNS 255.255.255.255 net_gateway
              --route 169.254.0.0 255.255.0.0 net_gateway
              --script-security 2
              --up /etc/openvpn/update-systemd-resolved --up-restart
              --down /etc/openvpn/update-systemd-resolved --down-pre
              --dhcp-option DOMAIN-ROUTE .)

            if grep -q auth-user-pass /tmp/config.ovpn; then
              vpn_command+=(--auth-user-pass /tmp/vpn.login)
            fi

            if [ -n "$phone_home" ]; then
              vpn_command+=(--route $phone_home 255.255.255.255 net_gateway)
            fi

            for IP in $(host runner.circleci.com | awk '{ print $4; }')
              do
                vpn_command+=(--route $IP 255.255.255.255 net_gateway)
                echo $IP
            done

            "${vpn_command[@]}" > /tmp/openvpn.log

      - run:
          name: Wait for the connection to be established and check IP
          command: |
            until [ -f /tmp/openvpn.log ] && [ "$(grep -c "Initialization Sequence Completed" /tmp/openvpn.log)" != 0 ]; do
              echo "Attempting to connect to VPN server..."
              sleep 3;
            done

            printf "\nVPN connected\n"
            printf "\nPublic IP is now $(curl checkip.amazonaws.com)\n"

      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: fco-forms-test
          aws-region: eu-west-2
          install-kubectl: true

      - kubernetes/update-container-image:
          namespace: << parameters.namespace >>
          container-image-updates: lists=523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists:$CIRCLE_SHA1
          resource-name: deployment/lists

      - kubernetes/update-container-image:
          namespace: << parameters.namespace >>
          container-image-updates: lists-apply=523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists-apply:$CIRCLE_SHA1
          resource-name: deployment/lists-apply

      - kubernetes/update-container-image:
          namespace: << parameters.namespace >>
          container-image-updates: lists-postgres=523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists-postgres:$CIRCLE_SHA1
          resource-name: deployment/lists-postgres

      - kubernetes/update-container-image:
          namespace: << parameters.namespace >>
          container-image-updates: lists-scheduler-batch=523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists-scheduler-batch:$CIRCLE_SHA1
          resource-name: cronjob/lists-scheduler-batch

      - kubernetes/update-container-image:
          namespace: << parameters.namespace >>
          container-image-updates: lists-scheduler-worker=523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/lists-scheduler-worker:$CIRCLE_SHA1
          resource-name: cronjob/lists-scheduler-worker

      - run:
          name: Disconnect from OpenVPN
          command: |
            sudo killall openvpn || true
          when: always

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/

      - smoke
      - smoke-run:
          requires:
            - smoke

      - publish:
          name: publish-lists
          app: lists
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              only:
                - deploy-test
          context:
            - VPN
            - AWS


      - publish:
          name: publish-lists-apply
          app: lists-apply
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              only:
                - deploy-test
          context:
            - VPN
            - AWS


      - publish:
          name: publish-lists-postgres
          app: lists-postgres
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              only:
#                - deploy-test
                - deploy-db
          context:
            - VPN
            - AWS


      - publish:
          name: publish-lists-scheduler-batch
          app: lists-scheduler-batch
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              only:
                - deploy-test
          context:
            - VPN
            - AWS


      - publish:
          name: publish-lists-scheduler-worker
          app: lists-scheduler-worker
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              only:
                - deploy-test
          context:
            - VPN
            - AWS


      - deploy:
          name: deploy-test
          namespace: test-lists
          context:
            - VPN
            - AWS
          requires:
            - publish-lists
            - publish-lists-apply
            - publish-lists-scheduler-batch
            - publish-lists-scheduler-worker
#            - publish-lists-postgres
          filters:
            branches:
              only:
                - deploy-test

      - deploy:
          name: deploy-db
          namespace: test-lists
          context:
            - VPN
            - AWS
          requires:
            - publish-lists-postgres
          filters:
            branches:
              only:
                - deploy-db
