-- Add missing countries

INSERT INTO
    "Country" ("updatedAt", "name")
VALUES
  (NOW(), 'Afghanistan'),
  (NOW(), 'Albania'),
  (NOW(), 'Algeria'),
  (NOW(), 'American Samoa'),
  (NOW(), 'Andorra'),
  (NOW(), 'Anguilla'),
  (NOW(), 'Armenia'),
  (NOW(), 'Aruba'),
  (NOW(), 'Belarus'),
  (NOW(), 'Bermuda'),
  (NOW(), 'Bhutan'),
  (NOW(), 'Bonaire, Sint Eustatius and Saba'),
  (NOW(), 'Bosnia and Herzegovina'),
  (NOW(), 'British Indian Ocean Territory'),
  (NOW(), 'British Virgin Islands'),
  (NOW(), 'Burundi'),
  (NOW(), 'Cameroon'),
  (NOW(), 'Canada'),
  (NOW(), 'Cape Verde'),
  (NOW(), 'Cayman Islands'),
  (NOW(), 'Central African Republic'),
  (NOW(), 'Chad'),
  (NOW(), 'China'),
  (NOW(), 'Comoros'),
  (NOW(), 'Congo'),
  (NOW(), 'Cook Islands'),
  (NOW(), 'Curaçao'),
  (NOW(), 'Ecuador'),
  (NOW(), 'Equatorial Guinea'),
  (NOW(), 'Falkland Islands'),
  (NOW(), 'French Guiana'),
  (NOW(), 'French Polynesia'),
  (NOW(), 'Gabon'),
  (NOW(), 'Gibraltar'),
  (NOW(), 'Guadeloupe'),
  (NOW(), 'Iceland'),
  (NOW(), 'Ireland'),
  (NOW(), 'Jordan'),
  (NOW(), 'Kenya'),
  (NOW(), 'Kiribati'),
  (NOW(), 'Kosovo'),
  (NOW(), 'Kyrgyzstan'),
  (NOW(), 'Libya'),
  (NOW(), 'Macao'),
  (NOW(), 'Maldives'),
  (NOW(), 'Marshall Islands'),
  (NOW(), 'Martinique'),
  (NOW(), 'Mayotte'),
  (NOW(), 'Micronesia'),
  (NOW(), 'Monaco'),
  (NOW(), 'Mongolia'),
  (NOW(), 'Montenegro'),
  (NOW(), 'Montserrat'),
  (NOW(), 'Nauru'),
  (NOW(), 'New Caledonia'),
  (NOW(), 'New Zealand'),
  (NOW(), 'Niger'),
  (NOW(), 'Niue'),
  (NOW(), 'North Korea'),
  (NOW(), 'Palau'),
  (NOW(), 'Papua New Guinea'),
  (NOW(), 'Paraguay'),
  (NOW(), 'Philippines'),
  (NOW(), 'Pitcairn Island'),
  (NOW(), 'Réunion'),
  (NOW(), 'Romania'),
  (NOW(), 'Saint Barthélemy'),
  (NOW(), 'Saint Helena, Ascension and Tristan da Cunha'),
  (NOW(), 'Samoa'),
  (NOW(), 'São Tomé and Príncipe'),
  (NOW(), 'Saudi Arabia'),
  (NOW(), 'Serbia'),
  (NOW(), 'Slovenia'),
  (NOW(), 'Solomon Islands'),
  (NOW(), 'Somalia'),
  (NOW(), 'South Georgia and South Sandwich Islands'),
  (NOW(), 'St Maarten'),
  (NOW(), 'St Martin'),
  (NOW(), 'St. Pierre and Miquelon'),
  (NOW(), 'Syria'),
  (NOW(), 'Tanzania'),
  (NOW(), 'Timor-Leste'),
  (NOW(), 'Tokelau'),
  (NOW(), 'Tonga'),
  (NOW(), 'Tunisia'),
  (NOW(), 'Turkmenistan'),
  (NOW(), 'Turks and Caicos Islands'),
  (NOW(), 'Tuvalu'),
  (NOW(), 'United States'),
  (NOW(), 'Uzbekistan'),
  (NOW(), 'Vanuatu'),
  (NOW(), 'Vatican City'),
  (NOW(), 'Wallis and Futuna Islands'),
  (NOW(), 'Western Sahara'),
  (NOW(), 'Yemen');
