export default [
  {
    contactName: "Cristina Carrillo Cabrera",
    lawFirmName: "Carillo y Asociados",
    email: "carrilloyasociados@yahoo.es",
    telephone: "+34607909484",
    address: "Calle Ramos Puente Nº 9, Bajo-A, Torremolinos, Malaga",
    regionsServed: "All regions",
    legalPracticeAreas: "Criminal",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Francisco Jose Ortega Moreno",
    lawFirmName: "AF Consulting Lawyers",
    website: "https://afconsulting.es/en/contact-us/",
    telephone: "+34722277677",
    address: "Calle Vilchez 6, 1B, Motril 18600 Granada",
    regionsServed: "Andalucia",
    legalPracticeAreas:
      "Corporate; Criminal; Immigration; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Jose Maria Alonso Martin",
    lawFirmName: "Alonso & Weber abogados",
    website: "http://www.alonsoweber.com",
    telephone: "+34951132760",
    address: "Calle Granados 3, 4ºB, 29008, Málaga",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Health; Intellectual property; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Guerrero Rafael",
    lawFirmName: "Andalucia-Lawyers",
    website: "https://www.andalucia-lawyers.com/",
    telephone: "+34958290580",
    address: "Camino de Ronda, 74, 3º, P4, 18004. Granada",
    regionsServed: "Andalucia",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Family; Immigration; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Jose Miguel López",
    lawFirmName: "Axarquía Solicitors",
    website: "https://marbellasolicitors.com/",
    telephone: "+34952901225",
    address:
      "Calle Camino de Remanente, nº 2, 1º A, Vélez-Málaga, Málaga, 29700",
    regionsServed: "Málaga, Manilva, Marbella, Mijas, Nerja",
    legalPracticeAreas: "Corporate; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Katherine Biel Gleeson",
    lawFirmName: "Biel Gleeson Abogado & Solicitor",
    website: "https://bielgleeson.com/",
    telephone: "+34639099395",
    address: "Calle Boleros 11, 18198 Granada",
    regionsServed: "Andalucia",
    legalPracticeAreas:
      "Corporate; Employment; Family; Immigration; International; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Oscar Ernesto Bornico",
    lawFirmName: "Bornico Farquharson Solicitors",
    website: "http://www.bfsolicitors.com",
    telephone: "+34660622374",
    address:
      "Urb. Monte Duquesa, The courtyard, Local 31 B. 29692- Puerto de la Duquesa, Manilva Spain",
    regionsServed: "Costa del Sol",
    legalPracticeAreas:
      "Corporate; Family; Immigration; Intellectual property; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Miguel Angel Bravo",
    lawFirmName: "Bravo Legal, S.L.",
    website: "http://www.bravolegal.es",
    telephone: "+34952463499",
    address: "Calle Córdoba 9, Office 5, 29640 Fuengirola",
    regionsServed: "Malaga Province",
    legalPracticeAreas: "Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Victoria Westhead",
    lawFirmName: "British Lawyer In Spain",
    website: "https://www.britishlawyerspain.com/",
    telephone: "+34678826771",
    address:
      "Edificio Santa Maria 1 °N, Avenida Tivoli 15, 29631 Benalmadena, Malaga",
    regionsServed: "Malaga Province",
    legalPracticeAreas: "Criminal; Immigration; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Sixto Garcia",
    lawFirmName: "Costadelaluz-Lawyers",
    website: "https://costaluzlawyers.es/",
    telephone: "+34956531214",
    address: "Calle Hormaza 28, 2ºB, 11130 Chiclana, Cadiz",
    regionsServed: "Costa de la Luz and Andalucia",
    legalPracticeAreas: "Criminal; Family; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "María L De Castro",
    lawFirmName: "Costaluz Lawyers",
    website: "https://costaluzlawyers.es/",
    telephone: "+34956092687",
    address:
      "Calle Fuerte Santiago 3, Centro Blas Infante, Entreplanta 2, oficina 1c 11201 Algeciras, Cádiz",
    regionsServed: "All regions",
    legalPracticeAreas: "Corporate; Family; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Michael Davies",
    lawFirmName: "Davies Abogados/Solicitors & Barristers",
    website: "http://www.daviessolicitors.com",
    telephone: "+34950472775",
    address: "Parque Comercial 50, 04638, Mojacar",
    regionsServed: "Andalucia",
    legalPracticeAreas: "Family; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Manuel Davó",
    lawFirmName: "Davo & Asociados Abogados SLP",
    website: "http://www.davolawoffices.com",
    telephone: "+34952064781",
    address:
      "Calle Pirandello Street 16, 6th Floor, Apartament nº 1, 29010, Malaga",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Sandra Wrightson",
    lawFirmName: "De Cotta Law",
    website: "http://www.decottalaw.com",
    telephone: "+34952527014",
    address:
      "Centro Comercial Valdepinos 1 y 3 Urb.Calypso, Mijas Costa, Málaga",
    regionsServed: "All Regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Immigration; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Eugene Delgado de la Cuesta",
    lawFirmName: "DJ Ortiz Y Asociados, SL",
    website: "http://www.ortizyasociados.es",
    telephone: "+34954561056",
    address: "Calle Almirante Lobo 2, 2 Iza, 41001, Seville",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Edward Grant",
    lawFirmName: "Edward Grant Associates",
    website: "http://www.spanishbarrister.com",
    telephone: "+34952822876",
    address: "Plaza de la Solidaridad, 12, 5ª planta, 29006 Málaga",
    regionsServed: "Southern Spain",
    legalPracticeAreas: "Family; Maritime; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Francisco de Asis Gamboa",
    lawFirmName: "Fitzwilliam Solicitors",
    website: "https://www.fitzwilliamsolicitors.com/",
    telephone: "+34951519851",
    address:
      "Calle Llanos de San Ramón 3, Edf. Mayoral, 2º 6, Marbella, Málaga",
    regionsServed: "All regions",
    legalPracticeAreas: "Corporate; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Fernando Franco",
    lawFirmName: "Franco Abogados",
    website: "https://www.francoabogados.com/",
    telephone: "+34952863819",
    address: "Calle Ramon Gomez de la Serna 14, 29602 Marbella, Málaga",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Immigration; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Francisco Gómez Moreno",
    lawFirmName: "Gómez Abogados",
    website: "http://www.gomez-abogados.com/",
    telephone: "+34689740442",
    address:
      "Avenida Gerald Brenan 103, Edificio Perla 1, Local 2, Oficina 3, 29120 Alhaurín el Grande, Málaga",
    regionsServed: "All regions",
    legalPracticeAreas: "Family; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Marianela Nuñez",
    lawFirmName: "Hispalaw Abogados",
    website: "https://www.hispalawabogados.com/",
    telephone: "+34605815338",
    address: "Calle Bolivia, 12, ground floor, 23680 Manilva, Málaga",
    regionsServed: "Spain, Jaen, Alcala la Real",
    legalPracticeAreas:
      "Criminal; Family; Immigration; Intellectual property; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Jaime Casado Ruiz",
    lawFirmName: "Jaime Casado Ruiz - Despacho Jurídico",
    website: "https://jaimecasado.com/",
    telephone: "+34954281614",
    address:
      "Edificio Metropol I, 1 Calle Industria, 41927, Mairena del Aljarafe, Seville",
    regionsServed: "Sevilla, Cádiz, Huelva",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; International; Maritime; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Jesus M Hernandez Carmona",
    lawFirmName: "Jesus Hernandez C JMHC",
    email: "jmhc@icadiz.net",
    telephone: "+34679474647",
    address: "San Pablo 18, 2nd floor La Linea de la Concepción, Cádiz",
    regionsServed: "Andalucia",
    legalPracticeAreas:
      "Corporate; Criminal; Family; Immigration; Real estate; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Juan Domingo Corpas",
    lawFirmName: "Juan Domingo & abogados",
    website: "http://www.juandomingo-abogados.com",
    telephone: "+34952857292",
    address: "Calle Jacinto Benavente nº 30 1º F, 29601 Marbella, Málaga",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Intellectual property; International; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Marisa Moreno Castillo",
    lawFirmName: "Just Law Spanish Solicitors",
    website: "https://justlawsolicitors.com/",
    telephone: "+34663373535",
    address: "2, Calle Chile, Fuengirola (Malaga) 29640",
    regionsServed: "All regions in Spain",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Immigration; International; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "José Manuel Díaz Montes",
    lawFirmName: "Konsell Abogados y Asesores, S.L.",
    website: "http://www.konsell.es",
    telephone: "+34956330083",
    address: "Calle Porvera nº 6, 1º A, 11403 Jerez de la Frontera, Cádiz",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Raymond L. Nesbitt",
    lawFirmName: "Larrain Nesbitt Abogados",
    website: "https://www.larrainnesbittabogados.com/",
    telephone: "+34952192288",
    address: "Calle San Juan Bosco 2, 6B, 29602, Marbella, Malaga",
    regionsServed: "Malaga",
    legalPracticeAreas: "Immigration; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Encarnacion Mercedes Teva Villen",
    lawFirmName: "Lexpertis",
    website: "http://www.lexpertis.es",
    telephone: "+34953583198",
    address: "Calle Archidona 36, 29532, Mollina-Málaga",
    regionsServed: "Malaga-Granada-Jaen",
    legalPracticeAreas:
      "Family; Health; Immigration; Intellectual property; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "David Llucia",
    lawFirmName: "llucia & AS-Lawyers",
    website:
      "https://llucialawyers.co.uk/legal-advice-in-sevilla-and-cadiz-spain/",
    telephone: "+34954228149",
    address: "Plaza Godinez 4, 41001, Seville",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Sergio Molina Fernandez",
    lawFirmName: "M & S Molina Abogados",
    website: "http://www.msmolinaabogados.com",
    telephone: "+34659451263",
    address: "Calle Princesa Nº 5, 1º B, 29740, Torre del Mar, Velez-Malaga",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Health; Immigration; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Miguel Angel Manzanares Macias",
    lawFirmName: "Manzanares Abogados",
    website: "https://manzanareslawyers.com/",
    telephone: "+34952824112",
    address:
      "Avda. Ricardo Soriano No 34,  Edif. Portillo Pl. 2 - Ofic. 4, 29601, Marbella, Málaga",
    regionsServed: "Málaga province",
    legalPracticeAreas:
      "Corporate; Employment; Family; Immigration; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Francesco Luca Caronna",
    lawFirmName: "Martin-Caronna abogados y consultores",
    website: "http://www.martin-caronna.com",
    telephone: "+34658618276",
    address: "Calle Josè Galán Merino 6, 41015, Seville",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Criminal; Employment; Family; Immigration; Intellectual property; International; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Marie Claire Richardson",
    lawFirmName: "MCR Lawyers",
    email: "marieclaire.richardson@gmail.com",
    telephone: "+34661548733",
    address: "Avenida 28 de Febrero, 3D, Salobreña, 18680, Granada",
    regionsServed: "Granada, Málaga",
    legalPracticeAreas: "Family; Immigration; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Luis Mesa Vila",
    lawFirmName: "Mesa & Green Abogados/Lawyers",
    website: "https://mesagreen.com/",
    telephone: "+34952901133",
    address:
      "Centro de Negocios Tembo, bloque A, Oficina 1, 29602 Marbella, Málaga",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Alex Radford",
    lawFirmName: "My Lawyer in Spain",
    website: "http://www.mylawyerinspain.com",
    telephone: "+34951203094",
    address: "Calle JuanRamon Jimenez 10, Edificioa Marbeland 4B, Marbella",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Corporate; Employment; Family; Immigration; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Miguel Angel Peral Cortes",
    lawFirmName: "My Legal PA Associates & Gestoria Peral Cabello",
    website: "https://mylegalpaassociates.com/",
    telephone: "+34952810391",
    address:
      "C.C. Centro Plaza, Avd. Manolete s/n, Urb. Conjunto Casaño 7-3B, 29660 Nueva Andalucia, Marbella, Malaga",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Noemi Alarcon",
    lawFirmName: "Nav Consultores",
    email: "nalarcon@navconsultores.es",
    telephone: "+34675417771",
    address: "Plaza Arriola 1, 1, 29005, Málaga",
    regionsServed: "All regions",
    legalPracticeAreas: "Family; Immigration; International",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Javier Perez de Vargas Ruesdas",
    lawFirmName: "Perez De Vargas Abogados",
    website: "https://perezdevargas.co.uk/",
    telephone: "+34 952778848",
    address:
      "Calle Mª Auxiliadora Nº 2, edificio Pata-Pata 5ª Planta, Marbella",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Corporate; Family; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Amaya Luzuriaga Fernández",
    lawFirmName: "Prime Legal Spain",
    website: "https://www.primelegal.es/",
    telephone: "+34656438361",
    address: "Alonso de Bazan 6, 1st floor, Office 5, 29602 Marbella, Málaga",
    regionsServed:
      "Andalucia, Murcia & Valencia. Especially Marbella & Costa del Sol, Costa Cálida & Costa Blanca.",
    legalPracticeAreas: "Family; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Fernando De Andres Gaston",
    lawFirmName: "Professional Advice Spain SLU (Pro-Advice)",
    website: "https://www.pro-advice.es/",
    telephone: "+34609454650",
    address: "Calle General Segura, 12, 2nd floor 1st door. 04004 Almería",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Family; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Rebecca Philip Crowther",
    lawFirmName: "Puerta Vides SL",
    website: "http://www.puertavides.com",
    telephone: "+34952764181",
    address: "Edificio Sabadell, Avda Ricardo Soriano 22, 3-6, 29601, Marbella",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Corporate; Criminal; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Rafael Berdaguer",
    lawFirmName: "Rafael Berdaguer Abogados",
    website: "http://www.berdaguerabogados.com",
    telephone: "+34952823085",
    address:
      "Avenida Ricardo Soriano, 29, Edificio Azahara Oficinas, 4ª planta, 29601 Marbella",
    regionsServed: "Andalucía",
    legalPracticeAreas: "Corporate; Family; International; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Jose Luis Rodriguez",
    lawFirmName: "Ros Abogados",
    website: "http://WWW.ROSLEGAL.ES",
    telephone: "+34951592529",
    address:
      "Avenida Ricardo Soriano 29, Edificio Azahara Oficinas, Planta 1ª Oficinas 1 y 2 29601 Marbella",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Family; Health; Intellectual property; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Jesús Ruíz Ballesteros",
    lawFirmName: "Ruiz Ballesteros Economistas y Abogados, SL",
    website: "http://www.ruizballesteros.es",
    telephone: "+34952779874",
    address: "Calle Juan Ramón Jiménez S/N, Bajo 6. 29601, Marbella, Málaga",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Family; Immigration; Intellectual property; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Sacha David Ruiz Dickson",
    lawFirmName: "Ruiz-Dickson, Abogados",
    website: "http://www.ruiz-dickson.com",
    telephone: "+34952770426",
    address: "Calle Nuestra Señora de Gracia 5, 1º-3, 29602 Marbella, Malaga",
    regionsServed: "All regions",
    legalPracticeAreas: "Bankruptcy; Corporate; Family; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Javier Serrano",
    lawFirmName: "S&J Solicitors",
    website: "http://www.s-jsolicitors.com",
    telephone: "+34638106260",
    address: "Avda. Constitucion, 26, 41001, Seville",
    regionsServed: "Sevilla y Huelva",
    legalPracticeAreas:
      "Criminal; Family; Health; Immigration; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Lorenzo & Sebastian Sánchez-Stewart de Torres",
    lawFirmName: "Sánchez-Stewart Abogados",
    website: "https://www.sanchez-stewart.com/",
    telephone: "+34952770704",
    address: "Calle Nuestra Señora de Gracia, 1 - 1º, 29602 Marbella, Málaga",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Corporate; Family; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Ken Sasaki Bulpe",
    lawFirmName: "Sasaki Abogados",
    website: "https://sasakiabogados.com/en/",
    telephone: "+34956781345",
    address:
      "Calle Altamira, s/n, Edificio Ayala, 1st floor, office 26, 11311, Pueblo Nuevo de Guadiaro, San Roque, Cádiz",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Criminal; Family; Immigration; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Ines Barba",
    lawFirmName: "Sbj Abogados",
    website: "http://www.sbjabogados.com",
    telephone: "+34606990997",
    address: "Calle Nuestra Señora de Gracia 28 1D, Marbella",
    regionsServed: "All Regions",
    legalPracticeAreas: "Criminal; International; Personal injury",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Marina Rodriguez",
    lawFirmName: "Sotogrande-Solicitors",
    website: "http://www.sotogrande-solicitors.com/",
    telephone: "+34671093857",
    address: "Calle Reina Sofia, Apto Campo Polo, 6; 11310; San Roque; Cadiz",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Immigration; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Rosa Vega Delgado",
    lawFirmName: "Tejada Solicitors",
    website: "https://tejadasolicitors.com/",
    telephone: "+34676815262",
    address: "Calle Camino de Malaga 22A, Edificio Espejo,29700, Velez-Malaga",
    regionsServed: "Malaga",
    legalPracticeAreas:
      "Corporate; Employment; Family; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Juan Antonio Rodríguez García",
    lawFirmName: "Temple Cambria Lawyers",
    website: "https://www.templecambria.com/",
    telephone: "+34617073669",
    address:
      "Calle Virgen de la Luz, corner with Calle Poniente, S/N, 11100, Conil de la Frontera, Cádiz, Spain",
    regionsServed: "Andalucia",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Health; Immigration; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Maria Teresa Toscano Martin",
    lawFirmName: "Toscanolex",
    website: "http://www.toscanolex.es",
    telephone: "+34699154530",
    address: "Avda Salvador Allende Nº 18, 29620  Torremolinos, Málaga",
    regionsServed: "Torremolinos, Málaga.",
    legalPracticeAreas:
      "Bankruptcy; Criminal; Family; Health; Immigration; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Victorio Heras Garcia",
    lawFirmName: "Victorio Heras Abogados",
    website: "http://www.propertylawspain.com/",
    telephone: "+34647460099",
    address: "Calle Alhondiga 9, Baza, 18800 Granada",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Criminal; Employment; Family; Health; Immigration; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Victoria Eugenia Villalba Gonzalez",
    lawFirmName: "Villalba solicitors and accountants S.L.",
    website: "http://www.villalba-asesores.com/",
    telephone: "+34950431720",
    address: "Avenida 28 de Febrero, 7, Albox, 04800, Almeria",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Virginia Ramos Martos",
    lawFirmName: "Virginia Ramos Lawyer",
    website: "http://www.virginiaramos.com",
    telephone: "+34616243990",
    address:
      "Avenida de la Aeronautica 10, Edificio Helios, 7º floor, office 7, Seville",
    regionsServed: "All regions",
    legalPracticeAreas: "Immigration; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
];
