export default [
  {
    contactName: "Guillermo Besga Saenz de Magarola",
    lawFirmName: "Mallorca Law",
    website: "http://mallorcalaw.com/",
    telephone: "+34 689457006",
    address: "Paseo del Borne 17, 1A",
    postcode: "07012",
    city: "Palma de Mallorca",
    regionsServed: "Palma",
    legalPracticeAreas:
      "Real estate; property; private clients; inheritance & tax; corporate law",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Gabriel Buades",
    lawFirmName: "Bufete Buades",
    website: "https://www.bufetebuades.com/en/",
    telephone: "+34 971228500",
    address: "Av. Jaime III, 4",
    postcode: "07012",
    city: "Palma de Mallorca",
    regionsServed: "Balearic Islands",
    legalPracticeAreas:
      "Arbitration & mediation; tourism; technology & data protection; criminal; commercial & corporate; labour & social security; family succession & Balearic regional law; administrative &constitutional law; real estate investments; credit and bankruptcy law; property, building & planning law; civil responsibility & damages;",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Borja Casanovas",
    lawFirmName: "Casasnovas Abogados",
    website: "http://www.casasnovasabogados.com/es/",
    telephone: "+34 971723902",
    address: "Av.Jaime III 3, 2º-1a",
    postcode: "07001",
    city: "Palma de Mallorca",
    regionsServed: "Palma",
    legalPracticeAreas:
      "Family law; criminal law; extraditions; international adoptions; corporate; litigation; intellectual property; real estate; insolvency; aviation",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Margaret Anne Cunningham",
    lawFirmName: "Cunningham Associates",
    website: "http://www.maricunningham.com/",
    telephone: "+34 971591118",
    address: "Calle Miguel de los Santos Oliver, 10, local 3",
    postcode: "07181",
    city: "Palmanova",
    regionsServed: "All of Mallorca",
    legalPracticeAreas:
      "Conveyancing; inheritance; family law; resident & non-resident tax returns; business set up & tax returns;",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Elena Font Carvahal",
    lawFirmName: "Font Mora Sainz de Baranda",
    website: "http://www.fmsb.eu/",
    telephone: "+34 971456222",
    address: "Avenida Alejandro Rosselló, 40, 8º",
    postcode: "07002",
    city: "Palma de Mallorca",
    regionsServed: "Mallorca, Ibiza and Formentera",
    legalPracticeAreas:
      "Conveyancing; real estate; inheritance; litigation; insolvency proceedings; personal injuries; labour and social security law;",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Jose Frau Greenfield",
    lawFirmName: "Bufete Frau",
    website: "https://www.bufetefrau.com/",
    telephone: "+34 971228036",
    address: "Calle San Miguel 36, 1",
    postcode: "07002",
    city: "Palma de Mallorca",
    regionsServed: "Mallorca",
    legalPracticeAreas:
      "Property sales & purchase conveyance; legal tax representations; tax advice for residents and non-residents; maritime law; civil & family law",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Eugenia Garcias de España",
    lawFirmName: "Eugenia Garcias de España",
    telephone: "+34 971908100",
    address: "Avda Jaime III 17, Despacho 42",
    postcode: "07012",
    city: "Palma de Mallorca",
    regionsServed: "Palma",
    legalPracticeAreas: "Private & commercial law",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Gabriel Garcias Planas",
    lawFirmName: "Gabriel Garcias Planas",
    telephone: "+34 971710624",
    address: "Paseo Mallorca 10",
    postcode: "07012",
    city: "Palma de Mallorca",
    regionsServed: "Balearic Islands and Spain",
    legalPracticeAreas: "Criminal law",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Marga Matas",
    lawFirmName: "Your Lawyer in Palma",
    website: "http://yourlawyerinpalma.com/",
    telephone: "34971711105",
    address: "Calle Ca´n Maçanet 3 bajos izquierda",
    postcode: "07003",
    city: "Palma de Mallorca",
    regionsServed: "Spain",
    legalPracticeAreas:
      "Family law; conveyancing; wills; corporate law; charities; insurance; criminal law; insolvency",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Lucas Maura",
    lawFirmName: "Bufete Maura",
    website: "http://www.bufetemaura.com/",
    telephone: "+34 971710941",
    address: "Edificio Fénix, Paseo Marítimo Calle Aigua Dolça n1, 1 -6a",
    postcode: "07014",
    city: "Palma de Mallorca",
    regionsServed: "Palma",
    legalPracticeAreas:
      "Real estate; property; tenancy agreements; conveyance; inheritance & wills; tax consultancy & advice; legal tax representations & resident and non-resident tax advice; litigation & insolvency; administrative law; planning regulations & liability matters; corporate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Antonio Morell",
    lawFirmName: "Grimalt & Associates",
    website: "http://www.grassociates.es/",
    telephone: "+34 971719220",
    address: "Calle San Miguel, 30-5º",
    postcode: "07002",
    city: "Palma de Mallorca",
    regionsServed: "Palma",
    legalPracticeAreas:
      "Real estate; property; tenancy agreements; conveyance; inheritance & wills: tax consultancy & advice; legal tax representations &  resident and non-resident tax advice;  litigation & insolvency; administrative law; planning regulations & liability matters;  corporate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Gloria Olmos",
    lawFirmName: "Sistema Legal",
    website: "http://www.sistemalegal.net//",
    telephone: "+34 971764481",
    address: "Calle San Miguel 63-2º",
    postcode: "07002",
    city: "Palma de Mallorca",
    regionsServed: "All Balearic Islands and Spain.",
    legalPracticeAreas:
      "Criminal law; gender violence & human trafficking; juvenile law; human rights; prison specialist",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Rosa Torrandell",
    lawFirmName: "Rosa Torrandell",
    website:
      "https://advocateabroad.com/lawyers/spain/mallorca/palma-de-mallorca//",
    telephone: "+34 971098980",
    address: "Carrer de Josep Anselm Clavé, 8, 7º 2ª",
    postcode: "07002",
    city: "Palma de Mallorca",
    regionsServed: "Palma, Mainland Spain, Canary Islands",
    legalPracticeAreas:
      "Family law; inheritance; all property related matters; criminal law; contract law",
    legalAid: "No",
    proBonoService: "No",
  },
];
