export default [
  {
    contactName: "Fernando Caballero Visser",
    organisationName: "Sr. D. Fernando Caballero & Sr. Antonio Mercadel",
    email: "info@clmabogados.com",
    telephone: "+34 971 352572",
    address: "Calle Norte 12",
    postcode: "07702",
    city: "Mahón",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Frederic Fortuny Esbert",
    organisationName: "Sr. Frederic Fortuny",
    email: "info@fortunyabogado.com",
    telephone: "+34 971 378095",
    address: "Calle Ruiz y Pablo 15-1°",
    postcode: "07730",
    city: "Alaior",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Veronique Niessen",
    organisationName: "Menorca Legal",
    email: "v.niessen@menorcalegal.com",
    website: "https://www.menorcalegal.com",
    telephone: "+34 664 621313",
    address: "C/Murada d’Artrutx 10",
    postcode: "07760",
    city: "Ciutadella de Menorca",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Juana Belén Seguí Puig",
    organisationName: "Sra. Belen Segui",
    email: "belen@belensegui.es",
    website: "https://www.belensegui.es",
    telephone: "+34 971 360150",
    address: "Calle Anuncivay 19",
    postcode: "07702",
    city: "Mahón",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Fernando Ylla Gutierrez",
    organisationName: "M. Ylla Asociados",
    email: "ylla.advocats.menorca@icaib.org",
    telephone: "+34 971 351120",
    address: "Isabel II, 16 1-2°",
    postcode: "07001",
    city: "Mahón",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Joaquin Comas Angles",
    organisationName: "Sr. D. Joaquin Comas",
    email: "jcomas@infotelecom.es",
    telephone: "+34 971 365 461",
    address: "Calle S’Arravaleta, 3 - 4°",
    postcode: "07702",
    city: "Mahón",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Pablo Maceda de Olives",
    organisationName: "Sr. Pablo Maceda",
    email: "pablo@abogadosmaceda.com",
    telephone: "+34 971 368236",
    address: "Plaza Príncipe, 9 2°-1ª",
    postcode: "07702",
    city: "Mahón",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Pedro Monjo Cerda",
    organisationName: "Sr. D. Pedro Monjo Cerda & Sra. Cristina Monjo Florit",
    email: "monjo@infotelecom.es",
    telephone: "+34 971 364188/90",
    address: "Calle San Fernando, 34",
    postcode: "07702",
    city: "Mahón",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Jonathan Tula Cunillera",
    organisationName: "Jonathan Tula",
    email: "tulaabogados@icaib.org",
    telephone: "+34 971 368430",
    address: "Calle del Carmen,1 - 1°",
    postcode: "07701",
    city: "Mahón",
    legalAid: "No",
    proBonoService: "No",
  },
];
