export default [
  {
    contactName: "Karen Moorby",
    lawFirmName: "AB Solicitors",
    website: "https://www.mylawyer.es",
    telephone: "34966449666",
    address:
      "1 Calle Malaquita, Centro Comercial Costa Zenia, ground floor, office 26",
    postcode: "",
    city: "",
    regionsServed: "Andalucia, Comunidad Valenciana, Región de Murcia",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Isaac Abad Garrido",
    lawFirmName: "Abad & Asociados Abogados & Economistas",
    website: "http://www.abadabogados.com/",
    telephone: "34968583053",
    address: "301 Avenida de la Libertad, 1º",
    postcode: "",
    city: "Los Alcazares",
    regionsServed: "Alicante, Murcia",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Immigration; Intellectual property; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Adolfo Valor",
    lawFirmName: "Adolfo Valor, Abogado & Lawyer",
    email: "avalorgil@gmail.com",
    telephone: "34966804952",
    address: "6 Calle Gambo, Edificio Nuevo Astoria, 3º, 303",
    postcode: "03503",
    city: "Benidorm",
    regionsServed: "Alicante",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Health; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Alicia Gomez Ferrandez",
    lawFirmName: "Advanta Group",
    website: "https://advantagroup.com/",
    telephone: "34966796779",
    address: "5 Plaza Sierra Castilla, Urbanización Marina",
    postcode: "03177",
    city: "San Fulgencio",
    regionsServed: "Costa Blanca",
    legalPracticeAreas:
      "Criminal; Employment; Family; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Juan Torres De Miguel",
    lawFirmName: "Advocats Abogados",
    website: "https://www.advocatsabogados.es",
    telephone: "34630872316",
    address: "53-3ª Calle Joaquin Costa",
    postcode: "46005",
    city: "Valencia",
    regionsServed: "Alicante, Castellón, Valencia",
    legalPracticeAreas:
      "Corporate; Family; Immigration; International; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Inmaculada Albiñana Luján",
    lawFirmName: "Albiñana-Moscardó Lawyers",
    website: "http://lawyersinvalencia.com/",
    telephone: "34963287690",
    address: "1–2 Calle Padilla",
    postcode: "46005",
    city: "Valencia",
    regionsServed: "Alicante, Castellón, Valencia",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Monna Laakso-Sáez",
    lawFirmName: "Aniorte & Laakso SLP",
    website: "https://www.aniorte-laakso.com",
    telephone: "34965718549",
    address: "74 Calle Ramón Gallud 74, 3º",
    postcode: "03181",
    city: "Torrevieja",
    regionsServed: "Alicante, Costa Blanca, Murcia, Orihuela, Torrevieja",
    legalPracticeAreas: "Corporate; Family; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "John Chandler",
    lawFirmName: "AP Abogados",
    website: "https://www.ap-legal.es",
    telephone: "34620042601",
    address: "2 Avenida de Albatera",
    postcode: "03689",
    city: "Hondon de los Frailes",
    regionsServed: "Alicante, Murcia",
    legalPracticeAreas: "Bankruptcy; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Mariano Arias Winogradow",
    lawFirmName: "Arias & Winogradow Law Firm",
    website: "https://www.CostaLawyer.es",
    telephone: "34635295400",
    address: "3 Calle Orense, entresuelo D",
    postcode: "03003",
    city: "Alicante",
    regionsServed: "Alicante, Madrid, Murcia, Valencia",
    legalPracticeAreas:
      "Corporate; Criminal; Family; Immigration; Intellectual property; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Esther Arroyo Martinez",
    lawFirmName: "Arroyo Legal",
    website: "http://arroyolegal.com/",
    telephone: "34966697151",
    address: "9-11,3ºI Avenida Benito Perez Galdos",
    postcode: "03004",
    city: "Alicante",
    regionsServed: "Almeria, Comunidad Valenciana, Madrid, Murcia",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Immigration; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Carmen Ayela Samper",
    lawFirmName: "Ayela Abogados",
    website: "https://www.ayela-abogados.com",
    telephone: "34965205333",
    address: "3 entresuelo Avenida Juan Bautista Lafora",
    postcode: "03002",
    city: "Alicante",
    regionsServed: "Castilla la Mancha, Comunidad Valenciana, Madrid, Murcia",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Jose Bernal-Quiros",
    lawFirmName: "B&Q Abogados",
    website: "https://www.bqabogados.es",
    telephone: "34868912859",
    address: "9 Calle Gonzalez Adalid, 4ºA",
    postcode: "30001",
    city: "Murcia",
    regionsServed: "Murcia",
    legalPracticeAreas:
      "Family; Intellectual property; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Gonzalo Blanco",
    lawFirmName: "Blanco Abogados",
    website: "https://www.blancolawfirm.com",
    telephone: "34678873844",
    address: "58 Marqués de Campo, Flat 5 door 9",
    postcode: "46800",
    city: "Denia",
    regionsServed: "Alicante, Castellon, Valencia",
    legalPracticeAreas: "Real estate; Family",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Oscar Ricor Morales",
    lawFirmName: "BZN Lex International Lawyers",
    website: "https://bestsolicitorsinspain.com",
    telephone: "34687888873",
    address: "19 Avenida de las Cortes Valencianas, Local 5",
    postcode: "03182",
    city: "Torrevieja",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Health; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Sènakpon Gbassi",
    lawFirmName: "Cabinet Sènakpon Gbassi - Avocats",
    website: "http://www.gbassi.es/",
    telephone: "34965142999",
    address: "44-5ºB Rambla de Méndez Núñez",
    postcode: "03002",
    city: "Alicante",
    regionsServed: "Alicante",
    legalPracticeAreas:
      "Corporate; Family; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Gonzalo Calderón Chao",
    lawFirmName: "CC Lawyers",
    website: "http://https://spanish-lawyer.org",
    telephone: "34965134928",
    address: "3 Calle Alemania, 6º derecha",
    postcode: "03003",
    city: "Alicante",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Family; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Venancio Parra Torres",
    lawFirmName: "CIVIL SP S.L.",
    website: "https://civilsp.com/es/",
    telephone: "34965294005",
    address: "33 Calle Apolo, 5th floor - Door E",
    postcode: "03182",
    city: "Torrevieja",
    regionsServed: "Murcia, Valencian Community",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Family; International; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Hugo Gutiérrez Colás",
    lawFirmName: "Colas Abogados",
    website: "http://www.colas-abogados.com/",
    telephone: "34966868492",
    address: "9 Calle Mozart, El Albir, Alfaz Del Pi",
    postcode: "03581",
    city: "Alicante",
    regionsServed: "Alicante, Valencia",
    legalPracticeAreas: "Corporate; Criminal; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Nicolas Duru",
    lawFirmName: "DM Legal & Immobrokers",
    website: "https://dmimmobrokers.com/en/",
    telephone: "34674751813",
    address: "32 Avda Jaime I, Entresuelo A",
    postcode: "03550",
    city: "San Juan de Alicante",
    regionsServed: "Baleares, Comunidad Valenciana, Murcia",
    legalPracticeAreas: "Corporate; Criminal; Real estate",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Ignasi Costas",
    lawFirmName: "DWF-RCD (Rousaud Costas Duran S.L.P.U)",
    website: "http://dwf-rcd.law/",
    telephone: "34961134468",
    address: "17 Moratín",
    postcode: "46002",
    city: "Valencia",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Augusto Scerrato",
    lawFirmName: "European Lawyer",
    website: "http://www.european-lawyer.net",
    telephone: "34654340253",
    address: "76 Calle Cirilo Amoros, Floor 3 Door 5",
    postcode: "46004",
    city: "Valencia",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Antonio Ferrandez Amoros",
    lawFirmName: "Ferrandez Villena-Ferrandez Amoros-Abogados",
    website: "https://www.ferrandezvillena-ferrandezamorosabogados.es",
    telephone: "34965718218",
    address: "8, 2º-2, Calle María Parodi",
    postcode: "03181",
    city: "Torevieja",
    regionsServed: "Alicante, Murcia",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Health; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "0",
  },
  {
    contactName: "Guadalupe Sánchez Baena",
    lawFirmName: "GM Legal Experts, S.L.",
    website: "https://www.gmlegalexperts.com",
    telephone: "34965727295",
    address: "16 Bajo Avenida del mediterráneo",
    postcode: "03140",
    city: "Guardamar del Segura",
    regionsServed: "All regions",
    legalPracticeAreas: "Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Patricia Safont Gregori",
    lawFirmName: "Gregori Abogados",
    website: "https://www.gregori-abogados.com",
    telephone: "34964228212",
    address: "10 Caballeros, 3rd right",
    postcode: "12001",
    city: "Castellón",
    regionsServed: "Castellón, Tarragona, Teruel, Valencia",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Family; Health; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Emma Harvey Ryan",
    lawFirmName: "Harvey Lawyers & Associates",
    website: "https://www.harveylawyers.es",
    telephone: "34865615070",
    address: "Centro Comercial Arenal, 126 Avenida del Pla",
    postcode: "03730",
    city: "Javea",
    regionsServed: "Alicante, Castellón, Murcia, Valencia",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Juan Antonio Hernández Mora-Martínez",
    lawFirmName: "Hernández Mora Lawyers",
    website: "https://www.hernandezmora.com",
    telephone: "34699202140",
    address: "3 Calle Lepanto, Entlo, Derecha",
    postcode: "30008",
    city: "Murcia",
    regionsServed: "Costa Blanca South, Costa Cálida, Murcia, Orihuela Costa",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Isabel Montesinos",
    lawFirmName: "Imont Legal Services",
    website: "https://www.imontlegal.com",
    telephone: "34968195045",
    address: "82 Avda. de la Union, San Javier",
    postcode: "30730",
    city: "Murcia",
    regionsServed: "Costa Calida, Costa Blanca North, Costa Blanca South",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Health; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Jordi Mauri Solé",
    lawFirmName: "Jms Lawyer",
    website: "https://www.jmslawyer.es",
    telephone: "34966443446",
    address: "43 Avenida Alegría, 2.3",
    postcode: "03194",
    city: "La Marina",
    regionsServed: "Murcia, Communidad Valenciana",
    legalPracticeAreas: "Real estate; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Jonathan Lambert",
    lawFirmName: "Jonathan Lambert Lawyers",
    email: "jlambert@icali.es",
    telephone: "34654685190",
    address: "64-2B Calle Colon",
    postcode: "03700",
    city: "Denia",
    regionsServed: "Murcia, Valencian Community",
    legalPracticeAreas:
      "Corporate; Family; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Sophie Mercier",
    lawFirmName: "LCS Valencia - Perez Domingo",
    website: "https://www.lcs-valencia.eu",
    telephone: "34963446496",
    address: "2 Calle Caulla, Buzon 52, Urb. Galera de las Palmeras",
    postcode: "03599",
    city: "Altea",
    regionsServed: "Alicante, Valencia",
    legalPracticeAreas:
      "Corporate; Employment; International; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Ascension Gonzalez Berganza",
    lawFirmName: "Letralia Lawyers",
    website: "https://www.letralialawyers.com",
    telephone: "34965719298",
    address: "75 Calle Caballero de Rodas, 1º A",
    postcode: "03181",
    city: "Torrevieja",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Criminal; Employment; Family; Immigration; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Guillermo Hernández Calatayud",
    lawFirmName: "Lex Consilium Laywers & Tax Advisers",
    website: "https://www.lexconsilium.com",
    telephone: "34962838902",
    address: "2 Calle Juan Bautista Anyes, Mezzanine",
    postcode: "46780",
    city: "Oliva",
    regionsServed: "Valencian Community",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Immigration; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Miriam Arlandis Rosello",
    lawFirmName: "Luis Bajo Fernandez Abogados",
    website: "http://luisbajoabogados.com/",
    telephone: "34965853877",
    address: "Edificio Astoria A 4º -10, 3 Calle Dr. Perez Llorca",
    postcode: "03503",
    city: "Benidorm",
    regionsServed: "Albacete, Alicante, Murcia, Valencia",
    legalPracticeAreas:
      "Criminal; Family; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "José María Martínez-Abarca",
    lawFirmName: "MAM Solicitors (Martínes-Abarca & Muñoz)",
    website: "https://www.mamsolicitors.com",
    telephone: "34968334439",
    address: "1 Calle Monasterio de venta de baños",
    postcode: "30730",
    city: "San Javier",
    regionsServed: "Alicante, Almería, Murcia, Valencia",
    legalPracticeAreas:
      "Criminal; Family; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Margarita Manresa Clemente",
    lawFirmName: "Margarita Manresa Clemente",
    email: "manresa_clemente@hotmail.com",
    telephone: "34966923054",
    address: "21 Calle Virgen del Carmen, 1ºD, La Mata",
    postcode: "03188",
    city: "Torrevieja",
    regionsServed: "Alicante",
    legalPracticeAreas: "Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Maria Solana Segui",
    lawFirmName: "Maria Solana 360º Lawyers",
    website: "https://mariasolana.com/",
    telephone: "34649559022",
    address: "Edificio Marán, Oficina 7, 12 Calle Tridente",
    postcode: "04540",
    city: "Alicante",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Montse Gomez Ferreres",
    lawFirmName: "MB Gomez Lawyers",
    website: "https://www.mbgomezlawyers.com",
    telephone: "34649818363",
    address: "2 Calle Poeta Cano Pato, 7ºB",
    postcode: "30009",
    city: "Murcia",
    regionsServed: "Alicante, Almeria, Murcia",
    legalPracticeAreas:
      "Corporate; Family; International; Personal injury; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Manuel Martin",
    lawFirmName: "MB Martin",
    website: "https://www.spanish-solicitors.com/",
    telephone: "34965161606",
    address: "22 Calle Castaños, 5b",
    postcode: "03001",
    city: "Alicante",
    regionsServed: "Alicante",
    legalPracticeAreas: "Criminal; International; Real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Mercedes Cuevas Martínez",
    lawFirmName: "Mercedes Cuevas Abogados-Lawyers-Rechtsanwälte",
    website: "https://www.mercedescuevas.com",
    telephone: "34966433235",
    address: "61 Patricio Ferrándiz (First floor, second door)",
    postcode: "03700",
    city: "Denia",
    regionsServed: "Alicante,Valencia",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Miguel Ángel Colombo",
    lawFirmName: "Miguel Ángel Colombo",
    website: "https://www.miguelangelcolombo.com",
    telephone: "34965729853",
    address: "15 Calle Mayor, 3ºA",
    postcode: "03140",
    city: "Guardamar del Segura",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Corporate; Family; Intellectual property; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Pedro Manuel Molina López",
    lawFirmName: "Molina Solicitors",
    website: "https://www.molinasolicitors.com",
    telephone: "34965319905",
    address: "10 Avda. Escorpiones, Resid. La Ciñuelica, R3, No5",
    postcode: "03189",
    city: "Punta Prima",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Moncia Sanchis Gonzalez",
    lawFirmName: "MSG LEGAL",
    website: "https://www.msg.legal",
    telephone: "34965130341",
    address: "31 Calle Reyes Catolicos",
    postcode: "03003",
    city: "Alicante",
    regionsServed: "Alicante, Murcia, Valencia",
    legalPracticeAreas: "Family; Immigration; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "María Dolores Hernández Ruiz",
    lawFirmName: "NH Abogados",
    website: "http://www.nhabogados.com/en/index.html",
    telephone: "34966783167",
    address: "4 Calle Practicante Alberto Berenguer, ground floor",
    postcode: "03169",
    city: "Algorfa",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Criminal; Family; Health; Immigration; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Ignacio Pellicer Mollá",
    lawFirmName: "Pellicer & Heredia, C.B.",
    website: "https://www.pellicerheredia.com/",
    telephone: "34965480737",
    address: "46 Calle San Fernando 46, 1º izqda",
    postcode: "03001",
    city: "Alicante",
    regionsServed: "Alicante, Almería, Valencia",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Salud Andreo Navarro",
    lawFirmName: "Reuters Solicitors",
    website: "https://www.reuterssolicitors.com",
    telephone: "34686602953",
    address: "8 Calle Haiti, 1 A",
    postcode: "03600",
    city: "Elda",
    regionsServed: "Alicante",
    legalPracticeAreas: "Bankruptcy; Corporate; Criminal; Family; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Alessandro Scarante",
    lawFirmName: "Scarante & Partners Law Firm",
    website: "https://www.studiolegalescarante.info",
    telephone: "34648484389",
    address: "7 Plaza Ramon Ibars",
    postcode: "46920",
    city: "Mislata",
    regionsServed: "Balearic Islands (Mallorca & Ibiza), Valencia Region",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Health; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "José Sempere",
    lawFirmName: "Sempere-Gelardo Abogados",
    website: "http://sempere-gelardoabogados.es",
    telephone: "34626947014",
    address: "31 Avenida Salamanca",
    postcode: "03005",
    city: "Alicante",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Family; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Silvia Galve Marti",
    lawFirmName: "SGM Abogados",
    website: "https://sgmlegalspain.com/",
    telephone: "34965724871",
    address: "34 Avenida Federico Garcia Lorca",
    postcode: "03178",
    city: "Benijofar",
    regionsServed: "Coastal areas",
    legalPracticeAreas: "Employment; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Martin James Hayes",
    lawFirmName: "SWAN Partners",
    website: "https://swanpartners.es",
    telephone: "34963348983",
    address: "1 Calle Pizarro, PTA 15",
    postcode: "46004",
    city: "Valencia",
    regionsServed: "Alicante, Castellon, Valencia",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Andrea San Román",
    lawFirmName: "Valero San Román SLP",
    website: "https://valerosanroman.com/en/the-office/",
    telephone: "34965985451",
    address: "38 Calle Suero de Quiñones, 2º izquierda",
    postcode: "28002",
    city: "Madrid",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Family; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Salvador Vives Pons",
    lawFirmName: "Vives Pons & Asociados, S.L.P.",
    website: "https://www.vivespons.com",
    telephone: "34966432624",
    address: "9 bajos Calle Pare Pere, Dénia",
    postcode: "03700",
    city: "Alicante",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Corporate; Employment; Family; Immigration; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Carlos Baos Torregrosa",
    lawFirmName: "White Baos Legal S.L.",
    website: "https://www.white-baos.com",
    telephone: "34966426185",
    address: "19 Calle Diana, 2º D",
    postcode: "03700",
    city: "Denia",
    regionsServed: "All Regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Family; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
];
