export default [
  {
    contactName: "Ardines y Asociados",
    organisationName: "Ardines y Asociados",
    website: "http://ardinessampedro.com/",
    telephone: "(+34) 922 751 196 & (+34) 658 828 687",
    address:
      "Avenida de Los Playeros, nº 25 - 1º Derecha. Los Cristianos, Arona",
    postcode: "38650",
    city: "Tenerife",
    regionsServed: "Santa Cruz de Tenerife province",
    legalPracticeAreas: "Family, criminal, civil & real estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Cabrera y Ravina Abogados",
    organisationName: "Cabrera y Ravina Abogados",
    website: "http://www.cabrerayravina.com",
    telephone: "(+34) 922 243 890",
    address: "Calle General Gutiérrez, nº 4 - 1º. Santa Cruz de Tenerife",
    postcode: "38002",
    city: "Tenerife",
    regionsServed: "Santa Cruz de Tenerife province",
    legalPracticeAreas:
      "Banking & finance, constructions & engineering, corporate, criminal, family & divorce, property",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "De Cotta Law",
    organisationName: "De Cotta Law",
    website: "http://www.decottalaw.com",
    telephone: "(+34) 922 719 520",
    address:
      "Avenida de España, s/n. Centro Comercial Terranova, Locales 312-313, San Eugenio. Costa Adeje",
    postcode: "38660",
    city: "Tenerife",
    regionsServed: "Santa Cruz de Tenerife province",
    legalPracticeAreas:
      "Conveyancing, Inheritance & tax, commericial, civil, criminal, family law, wills & probate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Hodgson Abogados",
    organisationName: "Hodgson Abogados",
    website: "http://www.hodgson.es",
    telephone: "(+34) 922 247 365",
    address: "Calle Pilar, nº 5 - 2º. Santa Cruz de Tenerife",
    postcode: "38002",
    city: "Tenerife",
    regionsServed: "Santa Cruz de Tenerife province",
    legalPracticeAreas:
      "Corporate, mercantile, maritime, civil, property, family, personal injury defence",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Humberto Conçalves Abogado",
    telephone: "(+34) 653 679 154",
    address: "Calle Aguere, nº 15, Local Bajo-B. -Santa Cruz de Tenerife",
    postcode: "38005",
    city: "Tenerife",
    regionsServed: "Santa Cruz de Tenerife province",
    legalPracticeAreas:
      "Inheritance, wills, personal injury, family, Property & real estate, immigration, banking & finance, litigation & dispute resolution, corporate, commercial and employment law",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Lawten Lawyers",
    organisationName: "Lawten Lawyers",
    website: "http://www.lawtenlawyers.com",
    telephone: "(+34) 735 937 & (+34) 652 293 325",
    address:
      "Avenida Claudio Delgado Díaz, nº 99. Oficina 1ºB. Polígono Las Chafiras. San Miguel de Abona",
    postcode: "38639",
    city: "Tenerife",
    regionsServed: "Santa Cruz de Tenerife province",
    legalPracticeAreas:
      "Family, criminal, extradition, international, Property, will & affidavits",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Lawyers Network International",
    organisationName: "Lawyers Network International",
    website: "http://www.avvo.es",
    telephone: "(+34) 922 751 524",
    address:
      "Boulevard Chajofe, nº 3, Edificio Edén, Local 109. Los Cristianos, Arona",
    postcode: "38650",
    city: "Tenerife",
    regionsServed: "Santa Cruz de Tenerife province",
    legalPracticeAreas: "Family, criminal, civil, taxation & property",
    legalAid: "No",
    proBonoService: "Only in special child custody cases, or involving minors.",
  },
  {
    contactName: "Luis Sánchez García-Yanes (L.S. Abogados)",
    organisationName: "Website under construction",
    telephone: "(+34) 822 143 647 & (+34) 605 879 124",
    address:
      "Avenida de Moscú, nº 38. Centro Comercial Aquamall, local 10. -Costa Adeje",
    postcode: "38679",
    city: "Tenerife",
    regionsServed: "Santa Cruz de Tenerife province",
    legalPracticeAreas:
      "Civil, mercantile, criminal, family & divorce, personal injury, timeshare, real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Tenerife Solicitors",
    organisationName: "Tenerife Solicitors",
    website: "http://www.tenerifesolicitors.com",
    telephone: "(+34) 922 717 845 & 0871 218 0063",
    address:
      "Calle Colón, Urbanización Club Atlantis, Local 1. San Eugenio. -Costa Adeje",
    postcode: "38660",
    city: "Tenerife",
    regionsServed: "Santa Cruz de Tenerife province, England & Wales",
    legalPracticeAreas:
      "Property, wills and probate, divorce, family, litigation and dispute resolution, business, timeshare",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Vercellone & Asociados",
    organisationName: "Vercellone & Asociados",
    website: "http://www.vercelloneyasociados.es",
    telephone: "(+34) 922 717 202",
    address:
      "Avenida Los Pueblos, nº 20. Centro Comercial San Eugenio, Local 72. -Costa Adeje",
    postcode: "38660",
    city: "Tenerife",
    regionsServed: "Santa Cruz de Tenerife province",
    legalPracticeAreas:
      "Company commercial, conveyancing, inheritance, tax, family",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Wildpret Abogados",
    organisationName: "Wildpret Abogados",
    website: "http://www.wildpret.es",
    telephone: "(+34) 922 718 020",
    address: "Centro Comercial San Eugenio, local 97. -Costa Adeje",
    postcode: "38670",
    city: "Tenerife",
    regionsServed: "Canary Islands",
    legalPracticeAreas:
      "Conveyance, litigations, inheritance, wills, family, investments, civil, contracts, taxes",
    legalAid: "Yes",
    proBonoService: "No",
  },
];
