export default [
  {
    contactName: "Alejandro Bonet Templeton",
    lawFirmName: "ALMAR LAWYERS",
    website: "https://www.almarlawyers.com/",
    telephone: "+34 686382537 / +34 971 313 421",
    address: "Paseo Vara de Rey 20, 1°, 2ª, 07800 Eivissa, Illes Balears",
    regionsServed: "Balearic Islands",
    legalPracticeAreas: "Maritime; Commercial; International",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Nadine Schroeder",
    lawFirmName: "ALMAR LAWYERS",
    website: "https://www.almarlawyers.com/",
    telephone: "+34 649 400 424 / +34 971 313 421",
    address: "Paseo Vara de Rey 20, 1°, 2ª, 07800 Eivissa, Illes Balears",
    regionsServed: "Balearic Islands and Catalonia",
    legalPracticeAreas:
      "Traffic Offences; Criminal; Procedural; Civil; Family; Minors",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Vicente Cardona Serapio",
    lawFirmName: "SERAPIO ABOGADOS",
    telephone: "+34 634 141 550",
    address: "Plaza Enrique Fajarnés Nº 6, 07800 Eivissa, Illes Balears",
    regionsServed: "Balearic Islands",
    legalPracticeAreas: "Criminal; Civil; Traffic Offences; Real Estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Jesús Herrero Antón",
    lawFirmName: "JESÚS ANTÓN ABOGADO",
    telephone: "+34 971 390 562 / +34 699 491 601",
    address: "Paseo Vara de Rey 18,1A, 07800 Eivissa, Illes Balears",
    regionsServed: "Balearic Islands",
    legalPracticeAreas: "Criminal; Family; Taxes; International; Real Estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Francisco Lorente Ramírez",
    lawFirmName: "ABOGADOS IBIZA",
    website: "http://www.abogadosibiza.com/",
    telephone: "(+34) 971 394 725 / (+34)667 555 585",
    address: "C/ Carlos V, 27, 1ºC, 07800, Ibiza",
    regionsServed: "Balearic Islands",
    legalPracticeAreas: "Civil; Criminal; Real Estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Lucas Prats Ribas",
    lawFirmName: "LUCAS PRATS RIBAS ABOGADO",
    telephone: "+34 97119 86 73 / +34 609 300 938",
    address: "Agroturismo Can Lluc, Ctra. Santa Inés km2, 07816 San Rafael",
    regionsServed: "Balearic Islands",
    legalPracticeAreas: "Real Estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Jaime Roig Riera",
    lawFirmName: "JAIME ROIG RIERA AND ASSOCIATES",
    website: "https://www.ibizalawyers.com/en/jaime-roig.php",
    telephone: "+34 971 19 15 85 / +34 971 19 15 86 / +34 629 214 213",
    address: "Avda. Bartolomé Vicente Ramón 1, 1º 1ª, 07800 Ibiza",
    regionsServed: "Balearic Islands",
    legalPracticeAreas: "Crimal; Administrative; Real Estate and Corporate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Elisa Rosselló Mayans",
    lawFirmName: "ELISA ROSELLÓ ABOGADOS",
    website: "http://elisarosselloabogados.com/",
    telephone: "+34 971 39 97 20 / +34 665 364 505",
    address: "Avda. Espanya, nº 59, 1º piso 7ª 8ª - 07800 Eivissa",
    regionsServed: "Balearic Islands",
    legalPracticeAreas:
      "Criminal; Civil; Family; Administrative; Labor; Real Estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Roger Sales Jimenez",
    lawFirmName: "ROGER SALAS JIMENEZ",
    telephone: "+34 971 39 99 53 / +34 616 789 126",
    address: "Avenida España nº 27, bajo 1ª, 07800 Ibiza",
    regionsServed: "Balearic Islands",
    legalPracticeAreas:
      "Criminal; Civil; Family; Sexual Offences; Immigration; Real Estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Cristina Samaan Joaniquet",
    lawFirmName: "CRISTINA SAMAAN JOANIQUET",
    telephone: "+34 971 31 51 63 / +34 665 83 37 55",
    address: "Carrer Carlos III, 10 – 12, 6th Floor, Door no 4., 07800 Ibiza",
    regionsServed: "Balearic Islands",
    legalPracticeAreas: "Criminal; Civil; Sexual Offences; Taxes",
    legalAid: "No",
    proBonoService: "No",
  },
];
