export default [
  {
    contactName: "Jiraporn Thongphong",
    lawFirmName: "Chaninat & Leeds",
    website: "http://www.chaninatandleeds.com",
    telephone: "+66 (0)2168 7001-3",
    address:
      "10/154 Trendy Office Building, Sukhumvit Road Soi 13, Klongtoey Nua, Vadhana",
    postcode: "10110",
    city: "Bangkok",
    regionsServed: "Thailand, other regions are upon agreement",
    legalPracticeAreas:
      "Criminal; Employment; Family; Health; Intellectual property; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Garn Tuntasatityanond",
    lawFirmName: "Garn Tuntasatityanond & Associates",
    website: "http://www.thailand-lawyer-bangkok.com",
    telephone: "+66 (0)2648 5041",
    address:
      "989 Siam Piwat Tower, 12A Floor, UnitB1-B2, Office no.1253, Rama 1 Road, Pathumwan",
    postcode: "10330",
    city: "Bangkok",
    regionsServed: "Thailand, other regions are upon agreement",
    legalPracticeAreas: "Criminal; Family; Health; Immigration; International",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Jetsada Jamallsawat",
    lawFirmName: "Sutin and Friends International Law Office",
    website: "http://www.sutinlawkrabi.com",
    telephone: "+66 (0)81778 6969",
    address: "171/80-82 Krabi Road, Paknam, Muang",
    postcode: "81000",
    city: "Krabi",
    regionsServed:
      "Bangkok, Krabi, Phang Nga, Phuket, Surat Thani and other regions on case to case basis",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Kitsanachai Kraibavornwish",
    lawFirmName: "Bangkok Lawyer Co.,Ltd.",
    website: "http://www.thailand-english-speaking-lawyer.com",
    telephone: "+66 (0)81899 1604",
    address:
      "965/9 Soi 3 Rangsit - Nakornayok Road, Pachatibut Thanyaburee District",
    postcode: "12130",
    city: "Pathumthanee",
    regionsServed: "Thailand, other regions are upon agreement",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Immigration; Maritime; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Nattaphol Chinawong",
    lawFirmName: "Natipatana Law Office",
    website: "http://www.natipatana.com",
    telephone: "+66 (0)81775 7695",
    address: "CNW Office & Residence 827/1, Ladprao 87, Klongchan, Bangkapi",
    postcode: "10240",
    city: "Bangkok",
    regionsServed: "Thailand, other regions are upon agreement",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Prachaya Vijitpokin",
    lawFirmName: "Prachaya International Law Firm",
    website: "http://www.prachayainternationallaw.com",
    telephone: "+66 (0)81453 8800",
    address: "10 Soi 20 Mithuna Yaek 5, Suthisan Road, Samsen Nok, Huai Khwang",
    postcode: "10310",
    city: "Bangkok",
    regionsServed:
      "Bangkok, Pattaya, Hua Hin, Chiang Mai, Phuket, Samui and other regions on case to case basis",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Immigration; International; Personal injury",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Thammarong Bootlert",
    lawFirmName: "Thailand Family Law Partners",
    website: "https://www.thailandfamilylaw.com/",
    telephone: "+66 (0)85539 3675",
    address: "97/5 Bang Phlab 2 Road, Bang Phlab, Pak Kret",
    postcode: "11120",
    city: "Nonthaburi",
    regionsServed: "Thailand, other regions are upon agreement",
    legalPracticeAreas: "Family; International; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Trib Danaitangtrakul",
    lawFirmName: "Legal Unit Company Limited",
    website: "https://www.legalunit.co.th",
    telephone: "+66 (0)81684 2228",
    address: "Italthai Tower Building, New Petchburi Road",
    postcode: "10310",
    city: "Bangkok",
    regionsServed: "Thailand, other regions are upon agreement",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Immigration; Intellectual property",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Vorathum Jirananda",
    lawFirmName: "Bangkok Legal Associates Law Office",
    email: "blalaw@hotmail.com",
    telephone: "+66 (0)2391 6099",
    address:
      "1000/88 Liberty Plaza Building 3rd Floor, Sukhumvit 55 Road (Soi Thonglor), Klongton-nua, Wattana",
    postcode: "10110",
    city: "Bangkok",
    regionsServed: "Bangkok, other regions on case to case basis",
    legalPracticeAreas:
      "Criminal; Employment; Family; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
];
