export default [
  {
    contactName: "Andrew Wynne",
    lawFirmName: "Price Sanond",
    website: "https://www.pricesanond.com/",
    telephone: "+66(0)26791844",
    address: "16F, Q House Sathorn, 11 South Sathorn Road",
    postcode: "10120",
    city: "Bangkok",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Immigration; Intellectual property; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Carlo Filippo (Charles) CIAMBRELLI",
    lawFirmName: "The Socia Lawyers",
    website: "http://www.thesociallawyers.com",
    telephone: "0901296101 - 0926921844 - 033 640005 (landline)",
    address: "29/25 moo 9, Nongprue, Banglamung",
    postcode: "",
    city: "Chonburi",
    regionsServed:
      "All regions for criminal and succession law, Bankgok -  Easern Seaboard - Bankgok - Krabi",
    legalPracticeAreas:
      "Corporate; Criminal; Family; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "David Ross Martin",
    lawFirmName: "Legal Services Hua Hin",
    website: "https://www.legalserviceshuahin.com",
    telephone: "+66(0)818469193",
    address: "Unit 1, Makro Food Services Hua Hin",
    postcode: "77110",
    city: "Prachaup Khiri Khan",
    regionsServed: "Hua Hin,Phetchaburi, Prachaup Khiri Khan",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Immigration; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Edward Thiravej Ploysongsang",
    lawFirmName: "Ployprathip International Law Office (PILO)",
    website: "http://www.ployprathip.com",
    telephone: "+66(0)26782995",
    address: "11/15-16 Ratchadaphisek Road, Chong Nonsi, Yannawa",
    postcode: "10120",
    city: "Bangkok",
    regionsServed: "Thailand",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Jetsada Jamallsawat",
    lawFirmName: "Sutin and Friends International Law Office",
    website: "http://www.sutinlawkrabi.com",
    telephone: "+66(0)817786969",
    address: "171/80-82 Krabi Rd., Paknam, Muang",
    postcode: "81000",
    city: "Krabi",
    regionsServed:
      "Bangkok, Krabi, Phang Nga, Phuket, Surat Thani and other regions of the Kingdom of Thailand",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Jirasak Taosiri",
    lawFirmName: "Siam Attorney International",
    website: "http://www.siam-attorney.com",
    telephone: "+66 (0) 95 750 0888",
    address:
      "No.1 Vasu 1 Building, Room 1501/3, 15th Floor, Sukhumvit 25 Alley, Sukhumvit Road, North Klongtoey, Wattana District",
    postcode: "10310",
    city: "Bangkok",
    regionsServed: "Bangkok and Neighboring Provinces, and Phuket",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Immigration; Intellectual property; International; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "John Lewis",
    lawFirmName: "Anglo-Thai Legal",
    website: "http://www.anglothailegal.com",
    telephone: "+66(0)27142968",
    address: "133 Sukhumvit 57 Road, Klongton Nua, Wattana",
    postcode: "10110",
    city: "Bangkok",
    regionsServed:
      "All regions with offices in Bangkok, Pattaya, Phuket, Chiang Mai, Koh Samui, Hua Hin, Buriram, Hat Yai",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Kitsanachai Kraibavornwish",
    lawFirmName: "Bangkok Lawyer Co.,Ltd",
    website: "http://www.Thailand-English-speaking-lawyer.com",
    telephone: "+66(0)818991604",
    address:
      "965/9 Rangsit Nakornayok Rd. Pachatibut Thanyaburee District Pathumthnai Province",
    postcode: "12130",
    city: "",
    regionsServed:
      "Cover all Thailand except Yala, Pattanee, and Naratiwat Provinces",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Immigration; Intellectual property; Maritime; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Nattaphol Chinawong",
    lawFirmName: "Natipatana Law Office",
    website: "https://www.natipatana.com",
    telephone: "+66(81)7757695",
    address:
      "827/1, CNW Office and Residence, Ladprao 87, Klong-chan, Bangkapi",
    postcode: "10240",
    city: "Bangkok",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Maritime; Personal injury; Real estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Navin Chaiyakul",
    lawFirmName: "Silk Legal",
    website: "https://www.silklegal.com",
    telephone: "+66(0)21072007",
    address: "#805 RSU Tower, 571 Sukhumvit Road",
    postcode: "10110",
    city: "Bangkok",
    regionsServed: "All Regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Health; Immigration; Intellectual property; International; Personal injury; Real estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Prachaya Vijitpokin",
    lawFirmName: "Prachaya International law firm",
    website: "http://www.prachayainternationallaw.com",
    telephone: "+66 814538800",
    address:
      "10 Soi 20 Mithuna Yaek 5, Sutthisan Road, Samsen Nok, Huai Khwang",
    postcode: "10310",
    city: "Bangkok",
    regionsServed:
      "Bangkok, Chiang Mai,  Hua Hin, Pattaya, Phuket, Samui and other regions of the Kingdom of Thailand",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Immigration; International; Personal injury",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Thammarong Bootlert",
    lawFirmName: "Thailand Family Law Partners",
    website: "http://www.thailandfamilylaw.com/",
    telephone: "+66(0)855393675",
    address: "97/5 Bang Phlab 2 Road, Bang Phlab, Pak Kret, Nonthaburi",
    postcode: "11120",
    city: "Bangkok",
    regionsServed: "All regions of Thailand.",
    legalPracticeAreas: "Family; International; Real estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
];
