export default [
  {
    contactName: "Jean-Claude Alle",
    lawFirmName: "Alle Avocats",
    website: "https://91degres.fr/",
    telephone: "+33(0)467065393",
    address: "18 rue Joe Dassin",
    postcode: "34000",
    city: "Montpellier",
    regionsServed: "Midi Pyreness Languedoc Rousillon - PACA",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Employment; Family; Health; Intellectual; International; Tax; Personal Injury; Real Estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Etienne Arnaud",
    lawFirmName: "Cabinet Étienne ARNAUD",
    website: "https://www.etiennearnaud.com",
    telephone: "+33(0)184790956",
    address: "32 rue Jouffroy d’Abbans",
    postcode: "75017",
    city: "Paris",
    regionsServed: "All regions in France",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual Property; International; Maritime; Personal Injury; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Stéphane Babonneau",
    lawFirmName: "Stéphane Babonneau",
    website: "https://www.sba-avocats.com/",
    telephone: "+33(0)186954310",
    address: "262 boulevard Saint-Germain",
    postcode: "75007",
    city: "Paris",
    regionsServed: "All regions and French overseas territories",
    legalPracticeAreas: "Criminal",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "France Bedois-Bekissa",
    lawFirmName: "BEXXIS Legal",
    website: "http://bexxislegal.com/",
    telephone: "+33(0)977199500",
    address: "10, rue Mohamed V",
    postcode: "34080",
    city: "Montpellier",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Real Estate; Corporate; Health; Immigration; Personal Injury",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Patrick Berjaud",
    lawFirmName: "KGA Avocats",
    website: "https://kga-avocats.fr/web/",
    telephone: "+33(0)144952000",
    address: "44 Avenue des Champs-Elysées",
    postcode: "75008",
    city: "Paris",
    regionsServed: "all regions",
    legalPracticeAreas:
      "Bankruptcy; Employment; Immigration; Intellectual Property; International; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Avi Bitton",
    lawFirmName: "Avi Bitton Law Firm",
    website: "https://www.avibitton.com",
    telephone: "+33(0)146476842",
    address: "72 Boulevard de Picpus",
    postcode: "75012",
    city: "Paris",
    regionsServed: "France",
    legalPracticeAreas: "Criminal; Employment; International; Personal Injury",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Sarah Bright Thomas",
    lawFirmName: "BRIGHT AVOCATS",
    website: "http://www.brightavocats.com",
    telephone: "+33(0)561579086",
    address: "16, place Saint Georges",
    postcode: "31000",
    city: "Toulouse",
    regionsServed: "All Regions",
    legalPracticeAreas:
      "Coporate; Criminal; Construction; Family; Contract; Inheritance; Property purchace, International; Personal Injury; Real Estate Law",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Gildas Brochen",
    lawFirmName: "CABINET BROCHEN GOEMINNE",
    website: "http://avocats-roubaix.fr",
    telephone: "+33(0)320280340",
    address: "113 Avenue Jean Leabs",
    postcode: "59100",
    city: "Roubaix",
    regionsServed: "Hauts de France",
    legalPracticeAreas: "Criminal; Family; Helath; Personal Injury",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Prune Calonne-Davies",
    lawFirmName: "Calonne & Adoue-Dugast",
    website: "https://www.cad-avocats.com",
    telephone: "+33(0)674161112",
    address: "61 rue Pierre Cazeneuve",
    postcode: "31200",
    city: "Toulouse",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Criminal; Employment; Family; International; Real Estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Faten Chafi-Shalak",
    lawFirmName: "Faten CHAFI-SHALAK",
    website: "https://www.avocat-chafi-roubaix.fr",
    telephone: "+33(0)320258489",
    address: "35, rue du maréchal Foch",
    postcode: "59100",
    city: "Roubaix",
    regionsServed: "France",
    legalPracticeAreas: "Family; Real estate; Criminal; Corporate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Véronique Chauveau",
    lawFirmName: "Véronique Chauveau & Associés",
    website: "https://www.chauveau-associes.com/",
    telephone: "+33(0)155425525",
    address: "62 rue de Maubeuge",
    postcode: "75009",
    city: "Paris",
    regionsServed: "France",
    legalPracticeAreas: "Family; International",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Karim Chebbani",
    lawFirmName: "CABINET CHEBBANI",
    website: "https://www.cabinet-chebbani.com",
    telephone: "+33(0)140060924",
    address: "30 rue Cambacérès",
    postcode: "75008",
    city: "Paris",
    regionsServed: "Paris, South of France, Toulouse",
    legalPracticeAreas:
      "Bankrupty; Criminal:Employment; Family; Health; Personal Injury",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Julian Cockain-Barère",
    lawFirmName: "Morvilliers Sentenac & Associés",
    website: "http://www.ms-associes.com",
    telephone: "+33(0)562275053",
    address: "Morvilliers Sentenac & Associés, 18 rue Lafayette",
    postcode: "31000",
    city: "Toulouse",
    regionsServed: "All France",
    legalPracticeAreas:
      "Bankruptcy; Coporate; Criminal; Employment; Family; Health;Immigration; Intellectual Property; International; Maritime; Personal Injury; Real Estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Fabien Cordiez",
    lawFirmName: "Cordiez Avocats & Solicitors",
    website: "https://www.solicitor.fr",
    telephone: "+33(0)486688968",
    address: "4 Cours Mirabeau",
    postcode: "13100",
    city: "Aix-en-Provence",
    regionsServed: "All regions",
    legalPracticeAreas: "Real estate; Estate and Probate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Aurore Cressent",
    lawFirmName: "Cressent Avocats",
    website: "http://cressent-avocats.com",
    telephone: "+33(0)185765092",
    address: "79, bd Malesherbes",
    postcode: "75008",
    city: "Paris",
    regionsServed: "France, All regions",
    legalPracticeAreas: "Family; International",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Julie Daniel",
    lawFirmName: "Castance Avocats",
    website: "http://www.castance-avocats.fr/en/",
    telephone: "+33(0)648305606",
    address: "14 rue Rabelais",
    postcode: "69003",
    city: "Lyon",
    regionsServed: "All Regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Intellectual; International; Maritime Tax; Personal Injury; Real Estate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Samira Denfer",
    lawFirmName: "Denfer",
    email: "samira.denfer@wanadoo.fr",
    telephone: "+33(0)320652842",
    address: "Residence du Palais, 57b Rue du Grand Chemin",
    postcode: "59100",
    city: "Roubaix",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Criminal; Employment; Family; Health; Immigration; International; Personal injury",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Elisa Gatto Warbington",
    lawFirmName: "Gatto Warbington",
    email: "contact@egwlegal.com",
    telephone: "+33(0)144293370",
    address: "5 rue Saint Philippe du Roule",
    postcode: "75008",
    city: "Paris",
    regionsServed: "All regions",
    legalPracticeAreas:
      "International; Coporate and Commercial; Real Estate; Family",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Caterina Giudiceandrea",
    lawFirmName: "Cabinet Giudiceandrea",
    website: "http://www.legal-gc.com",
    telephone: "+33(0)144882929",
    address: "65 rue Montmartre",
    postcode: "75002",
    city: "Paris",
    regionsServed: "All regions",
    legalPracticeAreas: "International; Family",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Antoine Giraudet",
    lawFirmName: "Cabinet Giraudet",
    website:
      "https://consultation.avocat.fr/avocat-paris/antoine-giraudet-41970.html",
    telephone: "+33(0)185080069",
    address: "9 rue Lagrange",
    postcode: "75005",
    city: "Paris",
    regionsServed: "All regions",
    legalPracticeAreas: "Criminal; Family",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Gregory Hanson",
    lawFirmName: "AARPI FGLH AVOCATS",
    website: "http://gregoryhansonavocat.com",
    telephone: "+33(0)466282245",
    address: "1, rue Général Perrier",
    postcode: "30000",
    city: "Nîmes",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Criminal; Family; Immigration; International; Personal Injury; Real Estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Sophia Harris",
    lawFirmName: "SHS Avocats",
    email: "sophia@shs-avocats.eu",
    telephone: "+33(0)629156482",
    address: "16 rue Beauvau",
    postcode: "13001",
    city: "Marseille",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Corporate; Criminal; Immigration; International; Personal Injury",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Christophe Jolk",
    lawFirmName: "BMH",
    website: "https://bmhavocats.com/",
    telephone: "+33(0)142666319",
    address: "29 rue du Faubourg Saint-Honoré",
    postcode: "75008",
    city: "Paris",
    regionsServed: "France",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual; International; Maritime; Personal; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Edouard Knoll",
    lawFirmName: "Knoll",
    email: "avocat.edouardknoll@outlook.fr",
    telephone: "+33(0)145481688",
    address: "179 bd Saint Germain",
    postcode: "75007",
    city: "Paris",
    regionsServed: "Paris, Ile de France Bordeaux, Gironde,Dordogne",
    legalPracticeAreas:
      "Criminal, Employment, Family, Health, Personal Injury, Real Estate",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Benoit Lafourcade",
    lawFirmName: "DELCADE AVOCATS & SOLICITORS",
    website: "https://www.delcade.com",
    telephone: "+33(0)175431856",
    address: "19 rue du Colisée",
    postcode: "75008",
    city: "Paris",
    regionsServed: "Paris-North and South West France",
    legalPracticeAreas:
      "Banruptcy; Corporate; Employment; Intellectual; International; Tax; Real Estate; Personal Injury",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Sébastien Leguay",
    lawFirmName: "Leguay",
    email: "leguay.s.avocat@orange.fr",
    telephone: "+33(0)468251445",
    address: "72 rue d’Alsace",
    postcode: "11000",
    city: "Carcassonne",
    regionsServed: "France",
    legalPracticeAreas:
      "Corporate; Criminal; Employment; Family; Health; International; Personal Injury; Real Estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Philippe L’Hoiry",
    lawFirmName: "SELARL L’HOIRY-VELASCO",
    website: "http://lhoiry-velasco-avocats.com/",
    telephone: "+33(0)559422052",
    address: "15 rue Raoul Perpère “Le Forum”",
    postcode: "64100",
    city: "Bayonne",
    regionsServed: "France",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Personal; Real Estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Olivier Mingasson",
    lawFirmName: "Les Avocats du Thélème",
    website: "https://www.avocatsdutheleme.com",
    telephone: "+33(0)467642724",
    address: "500 rue Léon Blum",
    postcode: "34000",
    city: "Montpellier",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Heritage; Corporate; Criminal; Employment; Family; Bankruptcy; Insurance; Real Estate; International; Tax; Personal Injury; Social Security; Banking",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Julien Neveux",
    lawFirmName: "NSC AVOCATS",
    email: "j.neveux@nsavocats.fr",
    telephone: "+33(0)320158460",
    address: "228, avenue de la République",
    postcode: "59110",
    city: "La Madeleine",
    regionsServed: "Hauts de France, Ile de France",
    legalPracticeAreas:
      "Criminal; Family; Health; Personal Injury; Real Estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Armelle Omnes",
    lawFirmName: "Cabinet Armelle OMNES",
    website: "https://www.cabinetomnesavocat.fr",
    telephone: "+33(0)299783308",
    address: "78 C, rue Saint Hélier",
    postcode: "35000",
    city: "Rennes",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual; International; Maritime; Personal; Real Estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Emmanuel Picq",
    lawFirmName: "PwC Société d’Avocats",
    website: "http://www.pwcavocats.com",
    telephone: "+33(0)156574969",
    address: "61 rue de Villiers",
    postcode: "92208",
    city: "Neuilly sur Seine",
    regionsServed: "All of France",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Health; Immigration; Intellectual; International; Maritime; Personal; Real Estate; Tax",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Jehanne Pornon-Weidknnet",
    lawFirmName: "JPW Avocats",
    website: "https://www.pornonweidknnet-avocat.com",
    telephone: "+33(0)782736088",
    address: "2ème étage, 4 Rue des Trois Conils",
    postcode: "33000",
    city: "Bordeaux",
    regionsServed: "All regions of France",
    legalPracticeAreas: "Immigration; Family, International",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "OLIVIER RANGEON",
    lawFirmName: "CABINET RANGEON",
    website: "http://www.avocat-rangeon.com",
    telephone: "+33(0)321300506",
    address: "8 Place de La Résistance",
    postcode: "62200",
    city: "Boulogne-sur-Mer",
    regionsServed: "France (NORD ET PAS DE CALAIS)",
    legalPracticeAreas:
      "Criminal; Employment; Family; International; Personal Injury",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Julie Ritaine",
    lawFirmName: "BBDR AVOCATS",
    website: "http://www.avocatsbbdr.fr",
    telephone: "+33(0)321990550",
    address: "28 rue Saint Jean",
    postcode: "62200",
    city: "Boulogne-sur-Mer",
    regionsServed: "France",
    legalPracticeAreas:
      "Criminal; Employment; Family; International; Personal injury; Real Estate; Commercial and Litigation",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Philippe Roger",
    lawFirmName: "KPDB",
    website: "https://www.kpdb.fr",
    telephone: "+33(0)556006270",
    address: "353, Boulevard du Président Wilson",
    postcode: "33000",
    city: "Bordeaux",
    regionsServed: "All regions",
    legalPracticeAreas: "Employment; Health; Personal Injury; Real Estate",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Olivier Rosato",
    lawFirmName: "Cabinet d’avocats ROSATO",
    website: "http://rosato-avocats.com/",
    telephone: "+33(0)491912203",
    address: "3 quai de la Joliette",
    postcode: "13002",
    city: "Marseille",
    regionsServed: "France",
    legalPracticeAreas:
      "Bankruptcy; Corporate; Criminal; Employment; Family; Immigration; Intellectual Property; International",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Etienne Rosenthal",
    lawFirmName: "Archipelago Law Office",
    website: "http://www.archipelago.law",
    telephone: "+33(0)251840084",
    address: "1, boulevard George Pompidou",
    postcode: "44200",
    city: "Nantes",
    regionsServed: "All regions",
    legalPracticeAreas:
      "Commercial; International;  Transport and Tourism; Personal Injury law; Real Estate law",
    legalAid: "Yes  Yes",
    proBonoService: "No",
  },
  {
    contactName: "Jill Schofield Thommeret",
    lawFirmName: "Douma Schofield Sibenaler",
    website: "http://avocats-douma-schofield-sibenaler.com/",
    telephone: "+33(0)144693550",
    address: "80 Boulevard Haussmann",
    postcode: "75008",
    city: "Paris",
    regionsServed: "Ile de France",
    legalPracticeAreas: "Family; International; Reat Estate; Tax",
    legalAid: "No",
    proBonoService: "No",
  },
  {
    contactName: "Inna Shveda",
    lawFirmName: "SHVEDA Inna Lawyer’ Cabinet",
    website: "http://www.innaavocat.com",
    telephone: "+33(0)473908052",
    address: "56 avenue Julien",
    postcode: "63000",
    city: "Clermont Ferrand",
    regionsServed: "All regions, but preferably in Auvergne Rhône Alpes",
    legalPracticeAreas:
      "Corporate; Criminel; Employment; Family; Imigration; International; Personal Injury; Real Estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Julie Soudaz",
    lawFirmName: "Julie Soudaz",
    website: "https://avocat-soudaz.com/",
    telephone: "+33(0)631688291",
    address: "20 Avenue de l’Opéra",
    postcode: "75001",
    city: "Paris",
    regionsServed: "France",
    legalPracticeAreas: "Corporate",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Jean-Michel Sourdin",
    lawFirmName: "Sourdin",
    email: "sourdin.avoc@wanadoo.fr",
    telephone: "+33(0)299405867",
    address: "2 Place Chateaubriand",
    postcode: "35400",
    city: "Saint-Malo",
    regionsServed: "Bretagne - France",
    legalPracticeAreas:
      "Family; Criminal; Bankruptcy; Corporate; Health; Personal Injury: Real Estate; Maritime",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Aurore Tonnellier",
    lawFirmName: "Utopia law firm",
    website: "https://www.utopia-avocats.com",
    telephone: "+33(0)185088000",
    address: "120 avenue des Champs Elysées",
    postcode: "75008",
    city: "Paris",
    regionsServed: "France all regions",
    legalPracticeAreas:
      "Corporate; Employment; Family; Intellectual; Personal Injury; Art",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
  {
    contactName: "Dominique Tricaud",
    lawFirmName: "TRICAUD AVOCATS",
    website: "https://tricaudavocats.fr/en/home-3/",
    telephone: "+33(0)140640025",
    address: "4 place Denfert Rochereau",
    postcode: "75014",
    city: "Paris",
    regionsServed: "All",
    legalPracticeAreas:
      "Criminal; Employment; Family; Health; Immigration; Intellectual property; International; Personal injury",
    legalAid: "No",
    proBonoService: "Yes",
  },
  {
    contactName: "Sharon Wilson-Dutin",
    lawFirmName: "Wilson-Dutin",
    email: "%20sharon.wilson.dutin@orange.fr",
    telephone: "+33(0)616078001",
    address: "139 boulevard du President Wilson",
    postcode: "33200",
    city: "Bordeaux  All regions",
    regionsServed: "Family; Criminal; Imigration; Property; Employment",
    legalPracticeAreas: "Yes",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Sebastian Van Teslaar",
    lawFirmName: "Van Teslaar Avocats",
    website: "http://www.vanteslaar.com",
    telephone: "+33(0)144900222",
    address: "32, rue Le Peletier",
    postcode: "75009",
    city: "Paris",
    regionsServed: "All regions",
    legalPracticeAreas: "Personal Injury",
    legalAid: "Yes",
    proBonoService: "No",
  },
  {
    contactName: "Mickaelle Verdier",
    lawFirmName: "SCP Plaisant Fourmond Verdier",
    email: "contact@avocatspfv.fr",
    telephone: "+33(0)243284765",
    address: "32 avenue François Mitterrand",
    postcode: "72000",
    city: "Le Mans",
    regionsServed: "Indre et Loire, Orne, Maine et Loire, Sarthe",
    legalPracticeAreas:
      "Bankruptcy; Criminal; Employment; Family; Health; Personal Injury; Real Estate",
    legalAid: "Yes",
    proBonoService: "Yes",
  },
];
