export const legalPracticeAreasList = [
  "Bankruptcy",
  "Corporate",
  "Criminal",
  "Employment",
  "Family",
  "Health",
  "Immigration",
  "Intellectual property",
  "International",
  "Maritime",
  "Personal injury",
  "Real estate",
  "Tax",
];

export const countriesList = [
  { text: "Afghanistan", value: "Afghanistan" },
  { text: "Albania", value: "Albania" },
  { text: "Algeria", value: "Algeria" },
  { text: "American Samoa", value: "American Samoa" },
  { text: "Andorra", value: "Andorra" },
  { text: "Angola", value: "Angola" },
  { text: "Anguilla", value: "Anguilla" },
  { text: "Antigua and Barbuda", value: "Antigua and Barbuda" },
  { text: "Argentina", value: "Argentina" },
  { text: "Armenia", value: "Armenia" },
  { text: "Aruba", value: "Aruba" },
  { text: "Australia", value: "Australia" },
  { text: "Austria", value: "Austria" },
  { text: "Azerbaijan", value: "Azerbaijan" },
  { text: "Bahamas", value: "Bahamas" },
  { text: "Bahrain", value: "Bahrain" },
  { text: "Bangladesh", value: "Bangladesh" },
  { text: "Barbados", value: "Barbados" },
  { text: "Belarus", value: "Belarus" },
  { text: "Belgium", value: "Belgium" },
  { text: "Belize", value: "Belize" },
  { text: "Benin", value: "Benin" },
  { text: "Bermuda", value: "Bermuda" },
  { text: "Bhutan", value: "Bhutan" },
  { text: "Bolivia", value: "Bolivia" },
  {
    text: "Bonaire, Sint Eustatius and Saba",
    value: "Bonaire,  Sint Eustatius and Saba",
  },
  { text: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
  { text: "Botswana", value: "Botswana" },
  { text: "Brazil", value: "Brazil" },
  {
    text: "British Indian Ocean Territory",
    value: "British Indian Ocean Territory",
  },
  { text: "British Virgin Islands", value: "British Virgin Islands" },
  { text: "Brunei", value: "Brunei" },
  { text: "Bulgaria", value: "Bulgaria" },
  { text: "Burkina Faso", value: "Burkina Faso" },
  { text: "Burma", value: "Burma" },
  { text: "Burundi", value: "Burundi" },
  { text: "Cambodia", value: "Cambodia" },
  { text: "Cameroon", value: "Cameroon" },
  { text: "Canada", value: "Canada" },
  { text: "Cape Verde", value: "Cape Verde" },
  { text: "Cayman Islands", value: "Cayman Islands" },
  {
    text: "Central African Republic",
    value: "Central African Republic",
  },
  { text: "Chad", value: "Chad" },
  { text: "Chile", value: "Chile" },
  { text: "China", value: "China" },
  { text: "Colombia", value: "Colombia" },
  { text: "Comoros", value: "Comoros" },
  { text: "Congo", value: "Congo" },
  {
    text: "Congo, Democratic Republic",
    value: "Congo, Democratic Republic",
  },
  { text: "Cook Islands", value: "Cook Islands" },
  { text: "Costa Rica", value: "Costa Rica" },
  {
    text: "Côte d'Ivoire",
    value: "Côte d'Ivoire",
  },
  { text: "Croatia", value: "Croatia" },
  { text: "Cuba", value: "Cuba" },
  { text: "Curaçao", value: "Curaçao" },
  { text: "Cyprus", value: "Cyprus" },
  { text: "northern Cyprus", value: "northern Cyprus" },
  { text: "Czech Republic", value: "Czech Republic" },
  { text: "Denmark", value: "Denmark" },
  { text: "Djibouti", value: "Djibouti" },
  { text: "Dominica", value: "Dominica" },
  { text: "Dominican Republic", value: "Dominican Republic" },
  { text: "Ecuador", value: "Ecuador" },
  { text: "Egypt", value: "Egypt" },
  { text: "El Salvador", value: "El Salvador" },
  { text: "Equatorial Guinea", value: "Equatorial Guinea" },
  { text: "Eritrea", value: "Eritrea" },
  { text: "Estonia", value: "Estonia" },
  { text: "Ethiopia", value: "Ethiopia" },
  { text: "Falkland Islands", value: "Falkland Islands" },
  { text: "Fiji", value: "Fiji" },
  { text: "Finland", value: "Finland" },
  { text: "France", value: "France" },
  { text: "French Guiana", value: "French Guiana" },
  { text: "French Polynesia", value: "French Polynesia" },
  { text: "Gabon", value: "Gabon" },
  { text: "Gambia", value: "Gambia" },
  { text: "Georgia", value: "Georgia" },
  { text: "Germany", value: "Germany" },
  { text: "Ghana", value: "Ghana" },
  { text: "Gibraltar", value: "Gibraltar" },
  { text: "Greece", value: "Greece" },
  { text: "Grenada", value: "Grenada" },
  { text: "Guadeloupe", value: "Guadeloupe" },
  { text: "Guatemala", value: "Guatemala" },
  { text: "Guinea", value: "Guinea" },
  { text: "Guinea-Bissau", value: "Guinea-Bissau" },
  { text: "Guyana", value: "Guyana" },
  { text: "Haiti", value: "Haiti" },
  { text: "Honduras", value: "Honduras" },
  { text: "Hong Kong", value: "Hong Kong" },
  { text: "Hungary", value: "Hungary" },
  { text: "Iceland", value: "Iceland" },
  { text: "India", value: "India" },
  { text: "Indonesia", value: "Indonesia" },
  { text: "Iran", value: "Iran" },
  { text: "Iraq", value: "Iraq" },
  { text: "Ireland", value: "Ireland" },
  { text: "Israel", value: "Israel" },
  { text: "Italy", value: "Italy" },
  { text: "Jamaica", value: "Jamaica" },
  { text: "Japan", value: "Japan" },
  { text: "Jordan", value: "Jordan" },
  { text: "Kazakhstan", value: "Kazakhstan" },
  { text: "Kenya", value: "Kenya" },
  { text: "Kiribati", value: "Kiribati" },
  { text: "Kosovo", value: "Kosovo" },
  { text: "Kuwait", value: "Kuwait" },
  { text: "Kyrgyzstan", value: "Kyrgyzstan" },
  { text: "Laos", value: "Laos" },
  { text: "Latvia", value: "Latvia" },
  { text: "Lebanon", value: "Lebanon" },
  { text: "Lesotho", value: "Lesotho" },
  { text: "Liberia", value: "Liberia" },
  { text: "Libya", value: "Libya" },
  { text: "Liechtenstein", value: "Liechtenstein" },
  { text: "Lithuania", value: "Lithuania" },
  { text: "Luxembourg", value: "Luxembourg" },
  { text: "Macao", value: "Macao" },
  { text: "Madagascar", value: "Madagascar" },
  { text: "Malawi", value: "Malawi" },
  { text: "Malaysia", value: "Malaysia" },
  { text: "Maldives", value: "Maldives" },
  { text: "Mali", value: "Mali" },
  { text: "Malta", value: "Malta" },
  { text: "Marshall Islands", value: "Marshall Islands" },
  { text: "Martinique", value: "Martinique" },
  { text: "Mauritania", value: "Mauritania" },
  { text: "Mauritius", value: "Mauritius" },
  { text: "Mayotte", value: "Mayotte" },
  { text: "Mexico", value: "Mexico" },
  { text: "Micronesia", value: "Micronesia" },
  { text: "Moldova", value: "Moldova" },
  { text: "Monaco", value: "Monaco" },
  { text: "Mongolia", value: "Mongolia" },
  { text: "Montenegro", value: "Montenegro" },
  { text: "Montserrat", value: "Montserrat" },
  { text: "Morocco", value: "Morocco" },
  { text: "Mozambique", value: "Mozambique" },
  { text: "Namibia", value: "Namibia" },
  { text: "Nauru", value: "Nauru" },
  { text: "Nepal", value: "Nepal" },
  { text: "Netherlands", value: "Netherlands" },
  { text: "New Caledonia", value: "New Caledonia" },
  { text: "New Zealand", value: "New Zealand" },
  { text: "Nicaragua", value: "Nicaragua" },
  { text: "Niger", value: "Niger" },
  { text: "Nigeria", value: "Nigeria" },
  { text: "Niue", value: "Niue" },
  { text: "North Korea", value: "North Korea" },
  { text: "North Macedonia", value: "North Macedonia" },
  { text: "Norway", value: "Norway" },
  { text: "Oman", value: "Oman" },
  { text: "Pakistan", value: "Pakistan" },
  { text: "Palau", value: "Palau" },
  { text: "Panama", value: "Panama" },
  { text: "Papua New Guinea", value: "Papua New Guinea" },
  { text: "Paraguay", value: "Paraguay" },
  { text: "Peru", value: "Peru" },
  { text: "Philippines", value: "Philippines" },
  { text: "Pitcairn Island", value: "Pitcairn Island" },
  { text: "Poland", value: "Poland" },
  { text: "Portugal", value: "Portugal" },
  { text: "Qatar", value: "Qatar" },
  { text: "Réunion", value: "Réunion" },
  { text: "Romania", value: "Romania" },
  { text: "Russia", value: "Russia" },
  { text: "Rwanda", value: "Rwanda" },
  { text: "Saint Barthélemy", value: "Saint Barthélemy" },
  {
    text: "Saint Helena, Ascension and Tristan da Cunha",
    value: "Saint Helena, Ascension and Tristan da Cunha",
  },
  { text: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
  { text: "Saint Lucia", value: "Saint Lucia" },
  {
    text: "Saint Vincent and the Grenadines",
    value: "Saint Vincent and the Grenadines",
  },
  { text: "Samoa", value: "Samoa" },
  { text: "San Marino", value: "San Marino" },
  { text: "São Tomé and Príncipe", value: "São Tomé and Príncipe" },
  { text: "Saudi Arabia", value: "Saudi Arabia" },
  { text: "Senegal", value: "Senegal" },
  { text: "Serbia", value: "Serbia" },
  { text: "Seychelles", value: "Seychelles" },
  { text: "Sierra Leone", value: "Sierra Leone" },
  { text: "Singapore", value: "Singapore" },
  { text: "Slovakia", value: "Slovakia" },
  { text: "Slovenia", value: "Slovenia" },
  { text: "Solomon Islands", value: "Solomon Islands" },
  { text: "Somalia", value: "Somalia" },
  { text: "South Africa", value: "South Africa" },
  {
    text: "South Georgia and South Sandwich Islands",
    value: "South Georgia and South Sandwich Islands",
  },
  { text: "South Korea", value: "South Korea" },
  { text: "South Sudan", value: "South Sudan" },
  { text: "Spain", value: "Spain" },
  { text: "Sri Lanka", value: "Sri Lanka" },
  { text: "St Maarten", value: "St Maarten" },
  { text: "St Martin", value: "St Martin" },
  {
    text: "St. Pierre and Miquelon",
    value: "St. Pierre and Miquelon",
  },
  { text: "Sudan", value: "Sudan" },
  { text: "Suriname", value: "Suriname" },
  { text: "Eswatini", value: "Eswatini" },
  { text: "Sweden", value: "Sweden" },
  { text: "Switzerland", value: "Switzerland" },
  { text: "Syria", value: "Syria" },
  { text: "Taiwan", value: "Taiwan" },
  { text: "Tajikistan", value: "Tajikistan" },
  { text: "Tanzania", value: "Tanzania" },
  { text: "Thailand", value: "Thailand" },
  {
    text: "The Occupied Palestinian Territories",
    value: "The Occupied Palestinian Territories",
  },
  { text: "Timor-Leste", value: "Timor-Leste" },
  { text: "Togo", value: "Togo" },
  { text: "Tokelau", value: "Tokelau" },
  { text: "Tonga", value: "Tonga" },
  { text: "Trinidad and Tobago", value: "Trinidad and Tobago" },
  { text: "Tunisia", value: "Tunisia" },
  { text: "Turkey", value: "Turkey" },
  { text: "Turkmenistan", value: "Turkmenistan" },
  {
    text: "Turks and Caicos Islands",
    value: "Turks and Caicos Islands",
  },
  { text: "Tuvalu", value: "Tuvalu" },
  { text: "Uganda", value: "Uganda" },
  { text: "Ukraine", value: "Ukraine" },
  { text: "United Arab Emirates", value: "United Arab Emirates" },
  { text: "United Kingdom", value: "United Kingdom" },
  { text: "United States", value: "United States" },
  { text: "Uruguay", value: "Uruguay" },
  { text: "Uzbekistan", value: "Uzbekistan" },
  { text: "Vanuatu", value: "Vanuatu" },
  { text: "Vatican City", value: "Vatican City" },
  { text: "Venezuela", value: "Venezuela" },
  { text: "Vietnam", value: "Vietnam" },
  {
    text: "Wallis and Futuna Islands",
    value: "Wallis and Futuna Islands",
  },
  { text: "Western Sahara", value: "Western Sahara" },
  { text: "Yemen", value: "Yemen" },
  { text: "Zambia", value: "Zambia" },
  { text: "Zimbabwe", value: "Zimbabwe" },
] as const;

export const fcdoLawyersPagesByCountry = {
  Afghanistan:
    "https://www.gov.uk/government/publications/afghanistan-list-of-lawyers",
  Albania:
    "https://www.gov.uk/government/publications/albania-list-of-lawyers--2",
  Algeria: "https://www.gov.uk/government/publications/algeria-list-of-lawyers",
  Angola: "https://www.gov.uk/government/publications/angola-list-of-lawyers",
  "Antigua and Barbuda":
    "https://www.gov.uk/government/publications/antigua-list-of-lawyers--2",
  Argentina:
    "https://www.gov.uk/government/publications/argentina-list-of-lawyers",
  Armenia: "https://www.gov.uk/government/publications/armenia-list-of-lawyers",
  Australia:
    "https://www.gov.uk/government/publications/australia-list-of-lawyers",
  Austria: "https://www.gov.uk/government/publications/austria-list-of-lawyers",
  Azerbaijan:
    "https://www.gov.uk/government/publications/azerbaijan-list-of-lawyers--2",
  Bahrain: "https://www.gov.uk/government/publications/bahrain-list-of-lawyers",
  Bahamas: "https://www.gov.uk/government/publications/bahamas-list-of-lawyers",
  Bangladesh:
    "https://www.gov.uk/government/publications/bangladesh-list-of-lawyers",
  Barbados:
    "https://www.gov.uk/government/publications/barbados-list-of-lawyers",
  Belarus: "https://www.gov.uk/government/publications/belarus-list-of-lawyers",
  Belgium: "https://www.gov.uk/government/publications/belgium-list-of-lawyers",
  Belize: "https://www.gov.uk/government/publications/belize-list-of-lawyers",
  Bolivia: "https://www.gov.uk/government/publications/bolivia-list-of-lawyers",
  "Bosnia and Herzegovina":
    "https://www.gov.uk/government/publications/bosnia-and-herzegovina-list-of-lawyers",
  Botswana:
    "https://www.gov.uk/government/publications/botswana-list-of-lawyers",
  Brazil: "https://www.gov.uk/government/publications/brazil-list-of-lawyers",
  Brunei: "https://www.gov.uk/government/publications/brunei-list-of-lawyers",
  Bulgaria:
    "https://www.gov.uk/government/publications/bulgaria-list-of-lawyers",
  Burma: "https://www.gov.uk/government/publications/myanmar-list-of-lawyers",
  Burundi: "https://www.gov.uk/government/publications/burundi-list-of-lawyers",
  Cambodia:
    "https://www.gov.uk/government/publications/cambodia-list-of-lawyers--2",
  Cameroon:
    "https://www.gov.uk/government/publications/cameroon-list-of-lawyers",
  Canada: "https://www.gov.uk/government/publications/canada-list-of-lawyers",
  "Cape Verde":
    "https://www.gov.uk/government/publications/cape-verde-list-of-lawyers",
  Chile: "https://www.gov.uk/government/publications/chile-list-of-lawyers",
  China: "https://www.gov.uk/government/publications/china-list-of-lawyers",
  Colombia:
    "https://www.gov.uk/government/publications/colombia-list-of-lawyers",
  "Costa Rica":
    "https://www.gov.uk/government/publications/costa-rica-list-of-lawyers",
  "Cote d’Ivoire":
    "https://www.gov.uk/government/publications/cote-divoire-list-of-lawyers",
  Croatia: "https://www.gov.uk/government/publications/croatia-list-of-lawyers",
  Cuba: "https://www.gov.uk/government/publications/cuba-list-of-lawyers--2",
  Cyprus: "https://www.gov.uk/government/publications/cyprus-list-of-lawyers",
  "northern Cyprus":
    "https://www.gov.uk/government/publications/cyprus-list-of-lawyers",
  "Czech Republic":
    "https://www.gov.uk/government/publications/czech-republic-list-of-lawyers",
  "Democratic Republic of Congo":
    "https://www.gov.uk/government/publications/democratic-republic-of-congo-list-of-lawyers",
  Denmark: "https://www.gov.uk/government/publications/denmark-list-of-lawyers",
  Dominica:
    "https://www.gov.uk/government/publications/dominica-list-of-lawyers",
  "Dominican Republic":
    "https://www.gov.uk/government/publications/dominican-republic-list-of-lawyers",
  Ecuador: "https://www.gov.uk/government/publications/ecuador-list-of-lawyers",
  Egypt: "https://www.gov.uk/government/publications/egypt-list-of-lawyers",
  "El Salvador":
    "https://www.gov.uk/government/publications/el-salvador-list-of-lawyers",
  Eritrea: "https://www.gov.uk/government/publications/eritrea-list-of-lawyers",
  Estonia: "https://www.gov.uk/government/publications/estonia-list-of-lawyers",
  Ethiopia:
    "https://www.gov.uk/government/publications/ethiopia-list-of-lawyers",
  Fiji: "https://www.gov.uk/government/publications/fiji-list-of-lawyers",
  Finland: "https://www.gov.uk/government/publications/finland-list-of-lawyers",
  France: "https://www.gov.uk/government/publications/france-list-of-lawyers",
  Gambia: "https://www.gov.uk/government/publications/gambia-list-of-lawyers",
  Georgia: "https://www.gov.uk/government/publications/georgia-list-of-lawyers",
  Germany: "https://www.gov.uk/government/publications/germany-list-of-lawyers",
  Ghana: "https://www.gov.uk/government/publications/ghana-list-of-lawyers",
  "Cayman Islands":
    "https://www.gov.uk/government/publications/grand-cayman-list-of-lawyers",
  Greece: "https://www.gov.uk/government/publications/greece-list-of-lawyers",
  Grenada: "https://www.gov.uk/government/publications/grenada-list-of-lawyers",
  Guatemala:
    "https://www.gov.uk/government/publications/guatemala-list-of-lawyers",
  Guinea: "https://www.gov.uk/government/publications/guinea-list-of-lawyers",
  Guyana:
    "https://www.gov.uk/government/publications/guyana-list-of-lawyers-and-translators",
  Haiti: "https://www.gov.uk/government/publications/haiti-list-of-lawyers",
  Honduras:
    "https://www.gov.uk/government/publications/list-of-lawyers-and-translators-for-honduras",
  "Hong Kong":
    "https://www.gov.uk/government/publications/hong-kong-list-of-lawyers",
  Hungary: "https://www.gov.uk/government/publications/hungary-list-of-lawyers",
  Iceland: "https://www.gov.uk/government/publications/iceland-list-of-lawyers",
  India: "https://www.gov.uk/government/publications/india-list-of-lawyers",
  Indonesia:
    "https://www.gov.uk/government/publications/indonesia-list-of-lawyers",
  Iran: "https://www.gov.uk/government/publications/iran-list-of-lawyers",
  Iraq: "https://www.gov.uk/government/publications/iraq-list-of-lawyers",
  Ireland: "https://www.gov.uk/government/publications/ireland-list-of-lawyers",
  Israel: "https://www.gov.uk/government/publications/israel-list-of-lawyers",
  Italy: "https://www.gov.uk/government/publications/italy-list-of-lawyers",
  Jamaica:
    "https://www.gov.uk/government/publications/list-of-lawyers-in-jamaica",
  Japan: "https://www.gov.uk/government/publications/japan-lawyers",
  Jordan: "https://www.gov.uk/government/publications/jordan-list-of-lawyers",
  Kazakhstan:
    "https://www.gov.uk/government/publications/kazakhstan-list-of-lawyers-translators",
  Kenya: "https://www.gov.uk/government/publications/kenya-list-of-lawyers",
  "North Korea":
    "https://www.gov.uk/government/publications/democratic-peoples-republic-of-korea-list-of-lawyers",
  Kosovo: "https://www.gov.uk/government/publications/kosovo-list-of-lawyers",
  Kuwait: "https://www.gov.uk/government/publications/kuwait-list-of-lawyers",
  Kyrgyzstan:
    "https://www.gov.uk/government/publications/kyrgyzstan-list-of-lawyers-translators",
  Laos: "https://www.gov.uk/government/publications/laos-list-of-lawyers",
  Latvia: "https://www.gov.uk/government/publications/latvia-list-of-lawyers",
  Lebanon: "https://www.gov.uk/government/publications/lebanon-list-of-lawyers",
  Liberia: "https://www.gov.uk/government/publications/liberia-list-of-lawyers",
  Lithuania:
    "https://www.gov.uk/government/publications/lithuania-list-of-lawyers",
  Luxembourg:
    "https://www.gov.uk/government/publications/luxembourg-list-of-lawyers",
  Macao: "https://www.gov.uk/government/publications/macao-list-of-lawyers",
  Madagascar:
    "https://www.gov.uk/government/publications/madagascar-list-of-lawyers",
  Malawi: "https://www.gov.uk/government/publications/malawi-list-of-lawyers",
  Malaysia:
    "https://www.gov.uk/government/publications/malaysia-list-of-lawyers",
  Maldives:
    "https://www.gov.uk/government/publications/maldives-list-of-lawyers",
  Mali: "https://www.gov.uk/government/publications/mali-list-of-lawyers",
  Malta: "https://www.gov.uk/government/publications/malta-list-of-lawyers",
  Mauritius:
    "https://www.gov.uk/government/publications/mauritius-list-of-lawyers",
  Mexico: "https://www.gov.uk/government/publications/mexico-list-of-lawyers",
  Moldova: "https://www.gov.uk/government/publications/moldova-list-of-lawyers",
  Monaco:
    "https://www.gov.uk/government/publications/monaco-list-of-english-speaking-lawyers",
  Mongolia:
    "https://www.gov.uk/government/publications/mongolia-list-of-lawyers",
  Montenegro:
    "https://www.gov.uk/government/publications/montenegro-list-of-lawyers",
  Morocco: "https://www.gov.uk/government/publications/morocco-list-of-lawyers",
  Mozambique:
    "https://www.gov.uk/government/publications/mozambique-list-of-lawyers",
  Namibia: "https://www.gov.uk/government/publications/namibia-list-of-lawyers",
  Nepal: "https://www.gov.uk/government/publications/nepal-list-of-lawyers",
  Netherlands:
    "https://www.gov.uk/government/publications/netherlands-list-of-lawyers",
  "New Zealand":
    "https://www.gov.uk/government/publications/new-zealand-list-of-lawyers",
  Nicaragua:
    "https://www.gov.uk/government/publications/nicaragua-list-of-lawyers",
  Nigeria: "https://www.gov.uk/government/publications/nigeria-list-of-lawyers",
  "North Macedonia":
    "https://www.gov.uk/government/publications/north-macedonia-lawyers",
  Norway: "https://www.gov.uk/government/publications/norway-list-of-lawyers",
  "The Occupied Palestinian Territories":
    "https://www.gov.uk/government/publications/the-occupied-palestinian-territories-list-of-lawyers",
  Pakistan:
    "https://www.gov.uk/government/publications/pakistan-list-of-lawyers",
  Panama: "https://www.gov.uk/government/publications/panama-list-of-lawyers",
  "Papua New Guinea":
    "https://www.gov.uk/government/publications/papua-new-guinea-list-of-lawyers",
  Paraguay:
    "https://www.gov.uk/government/publications/list-of-english-speaking-lawyers-and-translators-in-paraguay",
  Peru: "https://www.gov.uk/government/publications/peru-list-of-lawyers",
  Philippines:
    "https://www.gov.uk/government/publications/philippines-list-of-lawyers",
  Poland: "https://www.gov.uk/government/publications/poland-list-of-lawyers",
  Portugal:
    "https://www.gov.uk/government/publications/portugal-list-of-lawyers",
  Qatar: "https://www.gov.uk/government/publications/qatar-list-of-lawyers",
  Romania: "https://www.gov.uk/government/publications/romania-list-of-lawyers",
  Russia: "https://www.gov.uk/government/publications/russia-list-of-lawyers",
  Rwanda: "https://www.gov.uk/government/publications/rwanda-list-of-lawyers",
  Samoa: "https://www.gov.uk/government/publications/samoa-lawyers-list",
  "Saudi Arabia":
    "https://www.gov.uk/government/publications/saudi-arabia-list-of-lawyers",
  Senegal: "https://www.gov.uk/government/publications/senegal-list-of-lawyers",
  Serbia: "https://www.gov.uk/government/publications/serbia-list-of-lawyers",
  Seychelles:
    "https://www.gov.uk/government/publications/seychelles-list-of-lawyers",
  "Sierra Leone":
    "https://www.gov.uk/government/publications/sierra-leone-list-of-lawyers",
  Singapore:
    "https://www.gov.uk/government/publications/singapore-list-of-lawyers",
  Slovakia:
    "https://www.gov.uk/government/publications/slovakia-list-of-lawyers",
  Slovenia:
    "https://www.gov.uk/government/publications/slovenia-list-of-lawyers",
  "Solomon Islands":
    "https://www.gov.uk/government/publications/solomon-islands-list-of-lawyers",
  Somalia: "https://www.gov.uk/government/publications/somalia-list-of-lawyers",
  "South Africa":
    "https://www.gov.uk/government/publications/south-africa-list-of-lawyers",
  "South Korea":
    "https://www.gov.uk/government/publications/south-korea-list-of-lawyers",
  Spain: "https://www.gov.uk/government/publications/spain-list-of-lawyers",
  "Sri Lanka":
    "https://www.gov.uk/government/publications/sri-lanka-list-of-lawyers",
  "Saint Kitts and Nevis":
    "https://www.gov.uk/government/publications/st-kitts-and-nevis-list-of-lawyers",
  "Saint Lucia":
    "https://www.gov.uk/government/publications/stlucia-list-of-lawyers",
  "Saint Vincent and the Grenadines":
    "https://www.gov.uk/government/publications/st-vincent-list-of-lawyers",
  Sudan: "https://www.gov.uk/government/publications/sudan-list-of-lawyers",
  Suriname: "https://www.gov.uk/government/publications/suriname-lawyers",
  Sweden: "https://www.gov.uk/government/publications/sweden-list-of-lawyers",
  Switzerland:
    "https://www.gov.uk/government/publications/switzerland-list-of-lawyers",
  Liechtenstein:
    "https://www.gov.uk/government/publications/switzerland-list-of-lawyers",
  Taiwan: "https://www.gov.uk/government/publications/taiwan-list-of-lawyers",
  Tajikistan:
    "https://www.gov.uk/government/publications/tajikistan-list-of-lawyers",
  Tanzania:
    "https://www.gov.uk/government/publications/tanzania-list-of-lawyers",
  Thailand:
    "https://www.gov.uk/government/publications/thailand-list-of-lawyers",
  "Trinidad and Tobago":
    "https://www.gov.uk/government/publications/trinidad-and-tobago-list-of-lawyers--2",
  Tunisia: "https://www.gov.uk/government/publications/tunisia-list-of-lawyers",
  Turkey: "https://www.gov.uk/government/publications/turkey-list-of-lawyers",
  Turkmenistan:
    "https://www.gov.uk/government/publications/turkmenistan-list-of-lawyers",
  Uganda: "https://www.gov.uk/government/publications/uganda-list-of-lawyers",
  Ukraine: "https://www.gov.uk/government/publications/ukraine-list-of-lawyers",
  "United Arab Emirates":
    "https://www.gov.uk/government/publications/united-arab-emirates-list-of-lawyers",
  "United States":
    "https://www.gov.uk/government/publications/usa-list-of-lawyers",
  Uruguay: "https://www.gov.uk/government/publications/uruguay-list-of-lawyers",
  Uzbekistan:
    "https://www.gov.uk/government/publications/uzbekistan-list-of-lawyers",
  Vanuatu: "https://www.gov.uk/government/publications/vanuatu-list-of-lawyers",
  Venezuela:
    "https://www.gov.uk/government/publications/venezuela-list-of-lawyers",
  Vietnam:
    "https://www.gov.uk/government/publications/vietnam-lists-of-interpretation-and-translation-companies",
  Yemen: "https://www.gov.uk/government/publications/yemen-list-of-lawyers",
  Zambia: "https://www.gov.uk/government/publications/zambia-list-of-lawyers",
  Zimbabwe:
    "https://www.gov.uk/government/publications/zimbabwe-list-of-lawyers",
};

export const listOfCountriesWithLegalAid = [
  // based on https://www.gov.uk/legal-aid/legal-problems-abroad
  "Albania",
  "Austria",
  "Azerbaijan",
  "Belgium",
  "Bosnia and Herzegovina",
  "Bulgaria",
  "Cyprus",
  "northern Cyprus",
  "Czech Republic",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Georgia",
  "Greece",
  "Ireland",
  "Italy",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Montenegro",
  "Netherlands",
  "North Macedonia",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Serbia",
  "Spain",
  "Sweden",
  "Switzerland",
  "Turkey",
  "Ukraine",
];
