/*
  Warnings:

  - The values [ANNUAL_REVIEW_START_ONE_DAY_REMINDER_EMAIL_SENT,ANNUAL_REVIEW_START_ONE_WEEK_REMINDER_EMAIL_SENT,ANNUAL_REVIEW_START_ONE_MONTH_REMINDER_EMAIL_SENT,UNPUBLISH_ONE_DAY_POST_REMINDER_EMAIL_SENT,UNPUBLISH_WEEKLY_POST_REMINDER_EMAIL_SENT,UNPUBLISH_ONE_DAY_PROVIDER_REMINDER_EMAIL_SENT,UNPUBLISH_WEEKLY_PROVIDER_REMINDER_EMAIL_SENT] on the enum `ListItemEvent` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AuditEvent" ADD VALUE 'ANNUAL_REVIEW_START_ONE_DAY_REMINDER_POST_EMAIL_SENT';
ALTER TYPE "AuditEvent" ADD VALUE 'ANNUAL_REVIEW_START_ONE_WEEK_REMINDER_POST_EMAIL_SENT';
ALTER TYPE "AuditEvent" ADD VALUE 'ANNUAL_REVIEW_START_ONE_MONTH_REMINDER_POST_EMAIL_SENT';
ALTER TYPE "AuditEvent" ADD VALUE 'ANNUAL_REVIEW_STARTED_POST_EMAIL_SENT';
ALTER TYPE "AuditEvent" ADD VALUE 'ANNUAL_REVIEW_STARTED_PROVIDER_EMAIL_SENT';
ALTER TYPE "AuditEvent" ADD VALUE 'UNPUBLISHED_POST_EMAIL_SENT';
ALTER TYPE "AuditEvent" ADD VALUE 'UNPUBLISH_ONE_DAY_REMINDER_POST_EMAIL_SENT';
ALTER TYPE "AuditEvent" ADD VALUE 'UNPUBLISH_WEEKLY_REMINDER_POST_EMAIL_SENT';
ALTER TYPE "AuditEvent" ADD VALUE 'UNPUBLISHED_PROVIDER_EMAIL_SENT';
ALTER TYPE "AuditEvent" ADD VALUE 'UNPUBLISH_ONE_DAY_REMINDER_PROVIDER_EMAIL_SENT';
ALTER TYPE "AuditEvent" ADD VALUE 'UNPUBLISH_WEEKLY_REMINDER_PROVIDER_EMAIL_SENT';

-- AlterEnum
BEGIN;
CREATE TYPE "ListItemEvent_new" AS ENUM ('NEW', 'OUT_WITH_PROVIDER', 'EDITED', 'UNPUBLISHED', 'PUBLISHED', 'PINNED', 'UNPINNED', 'DELETED', 'UNDEFINED', 'ANNUAL_REVIEW_STARTED', 'CHECK_ANNUAL_REVIEW', 'ARCHIVED', 'UNPUBLISH_ONE_DAY_REMINDER_PROVIDER_EMAIL_SENT', 'UNPUBLISH_WEEKLY_REMINDER_PROVIDER_EMAIL_SENT');
ALTER TABLE "Event" ALTER COLUMN "type" TYPE "ListItemEvent_new" USING ("type"::text::"ListItemEvent_new");
ALTER TYPE "ListItemEvent" RENAME TO "ListItemEvent_old";
ALTER TYPE "ListItemEvent_new" RENAME TO "ListItemEvent";
DROP TYPE "ListItemEvent_old";
COMMIT;

-- AlterTable
ALTER TABLE "List" ALTER COLUMN "nextAnnualReviewStartDate" SET DEFAULT NOW() + interval '1 year';
