name: Branch QA

on:
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Prisma generate
        run: npm run prisma:generate

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Install Form Runner
        run: npm run form-runner:install

      - name: Test
        run: npm run test
